### ISSUE TITLE
EPIC: SCDR CLI executable

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#1017]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>cloud pilot team member</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>see whether the OneStop API can meet the needs of STAR's SCDR client</td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>reduce overlapping systems and associated operation and maintenance costs</td>
  </tr>
</table>

### Background
SCDR is a system to provide search and discovery of STAR satellite imagery. It has an existing command line interface (CLI), an html client, and a web-api all backed by a Postgres SQL database.

### Scope
This effort is to pilot the development of a new SCDR command line client, that uses search and discovery capabilities available through an API available from OneStop. HTML clients and supporting a SCDR specific web-api are not in scope. 

Implement a new scdr-files command line tool such that
It is backed by the OneStop API instead of the SCDR DB
It supports as many of the current options as possible with the existing OneStop API
It is designed to fit well in a container, i.e. doesn't require a large number of perl libraries, ideally is a small, standalone executable
It can be worked on collaboratively by both the OneStop and SCDR teams, e.g. uses a language comfortable for both

### Tasks
- [ ] Identify language to use to support development of new SCDR CLI utility (ALL)
- [ ] Develop standalone executable that can be containerized (Dev team at NCEI)
- [ ] Get list of collections currently available in SCDR (STAR)
- [ ] Get sample outputs from existing scdr-files utility for options below. (STAR)
- [ ] Identify changes needed OneStop API to fully support existing scdr-file utility options. (Dev team at NCEI)

### References
https://docs.google.com/document/d/1kU7Nql27bOjku_eiDip0hCN1cAkJtRH-OFCDcVWnNHQ/edit
