### ISSUE TITLE
Update OneStop search docs

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#1018]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>developer</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       have up to date OpenAPI and docs examples
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>speed the development of my thin portal</td>
  </tr>
</table>

### Background
The top level URL has changed from /onestop/ to /onestop-search.  Add granule API changes based on filename search other?

### Doc Coverage
- UI features vs API features
  - API capable of supporting more than UI allows, so we need some demonstrations of these (e.g., more detailed time/space filters; collections with parent ids, etc.)
- Tips for most accurate search matches? (e.g., collection filters vs matching fileId/title with regex to find all granules)
 
### Tasks
- [x] Add operationId to our OpenAPI spec
- [x] Update OneStop OpenAPI docs
- [x] Update docs in repo
- [x] Review and update if needed doc request from feedback repo - https://github.com/cedardevs/feedback/issues/3 comment and close after updates.

**Comment by StrayCat1** [comment]
The OpenAPI spec in the search module is now the source of truth. We still validate incoming requests against the schemas defined in the spec by de-referencing the request.json. Only now the request.json references the openapi.yaml instead of component json schemas. e.g. https://github.com/cedardevs/onestop/blob/1020-OneStopCLI/search/schema/request.json#L12

Unfortunately, we have lost some ability to validate Points. Notice that in these tests, we had to remove validation of failing points - https://github.com/cedardevs/onestop/blob/1020-OneStopCLI/search/src/test/groovy/org/cedar/onestop/api/search/controller/JsonValidatorSpec.groovy#L228

We were able to remove speccy and the json component schemas. 

As far as updating the docs - 
- update server base url - https://github.com/cedardevs/onestop/blob/1020-OneStopCLI/search/schema/openapi.yml#L3

- updated external docs and linked - https://github.com/cedardevs/onestop/blob/1020-OneStopCLI/docs/README.md#external-docs

- added service link metadata to the open api spec. https://github.com/cedardevs/onestop/blob/6af92e00891c21cf663892602c1fc197a759d781/search/schema/openapi.yml#L619
