### ISSUE TITLE
EPIC: First Pass SME function

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#1023]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>common data services platform</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>provide a way for datastream specific functions to interact with IM</td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>build science specific functionality</td>
  </tr>
</table>

### Assumptions
- Indexer assumes analysis block is present in payload

### Tasks
- [x] Add top level discoveryPopulated flag
- [x] Add minimally searchable info from granules into indexer
- [ ] Write a function that can parse netcdf header based on ACDD standard and update discovery info during ingest
- [ ] Migrate above functions an external process (outside of OneStop Indexer) to a FAAS integrated with IM
- [x] Coud Pilot example CSB-> S3 -> Lamda -> IM

**Comment by dneufeldcu** [comment]
kafka-sqs merged to master
