### ISSUE TITLE
EPIC: Merge PSI Code

### ISSUE THREAD

**Issue by mcquinne** [cedardevs/onestop#1035]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>PSI/OneStop developer</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>work on code from both systems in the same repo</td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>more easily manage all the existing PSI and OneStop components as part of a single, holistic system</td>
  </tr>
</table>

### Description
*Wherein*:
1. There is a significant amount of duplicated boilerplate between our two projects
2. Many of our stakeholders already view PSI and OneStop as a single system called OneStop
3. Significant code simplifications could be made by combining the components of the two systems
*We propose that*:
The code from the two repositories be combined.

### Assumptions
- Both PSI and OneStop have tagged functioning releases as independent systems with all of their 1.x and 2.x features implemented, respectively

### Tasks
- [x] Determine a branch management strategy, e.g. merge psi directly into master, merge it into a 3.x branch so we can continue 2.x work on master, etc. (#1024)
- [x] Merge the master branch from cedardevs/psi into the branch determined above, *putting all psi code under a new directory `psi/` to avoid initial merge conflicts* (#1025)
- [x] Move psi components `registry`, `stream-manager`, and `common` up to root dir, renaming and updating gradle build as needed (#1026)
- [x] Consolidate the following from both systems into a unified result at the root level:
    - [x] Helm charts, skaffold settings (#1027)
    - [x] CircleCI build config (#1029)
    - [x] GitHub issue templates (#1032)
    - [ ] ~Documentation (#1033)~ (evolved into #1049)
    - [x] Root files like readme, license (#1031)
- [x] Ensure that *nothing* is left under the `psi/` subdirectory and remove it (#1034)

**Comment by mcquinne** [comment]
All done!
