### ISSUE TITLE
EPIC: Factor indexing out into standalone kafka streams app

### ISSUE THREAD

**Issue by mcquinne** [cedardevs/onestop#1036]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>onestop developer</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>create a separate microservice to handle kafka ingest and elastic indexing</td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>isolate the indexing into its own context, scale the processing independently, etc.</td>
  </tr>
</table>

### Summary
The goal is to pull the logic which pulls from kafka and indexes documents into elasticsearch out into a standalone, headless, kafka streams applications.

**NOTE**: For this epic, we want to **leave the admin submodule** in place to support existing deployments of that artifact.

### Tasks
- First, implement updates to the existing indexing logic in `admin`
    - [x] improve bulk loading logging (#1012)
    - [x] improve index creation logic (#1013)
    - [x] improve DefaultParser logic (cedardevs/schemas#23)
    - [x] update DefaultParser usage (#1045)
- Then, create the `indexer` app, including the logic above
    - [x] create a new indexer app (#1051)
    - [x] resulting indexer tests should be significantly simpler (#989)
