### ISSUE TITLE
Refactor header / button space

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#1039]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>user</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       see a clean, concise header
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>my screen real estate is not wasted!</td>
  </tr>
</table>

### Tasks
- [ ] Wireframe look and feel 
- [ ] Revisit center justified vs right justified
- [ ] Number formatting
- [ ] Smaller foot print for icons

**Comment by dneufeldcu** [comment]
Covered in list view #359.
