### ISSUE TITLE
EPIC: Update Documentation

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#1049]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>open source developer/user</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>rely on up to date and accurate documentation</td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>can contribute to the project</td>
  </tr>
</table>

### Description
Need to add to our documentation for PSI and OneStop. Look at reorganizing, and adding support for client developer examples.

### Tasks
- [ ] Merge docs from PSI
- [ ] Add documentation from OER video support work
- [ ] Move metadata indexing from design to usage
