### ISSUE TITLE
EPIC: Data Catalog Support

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#1050]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>data catalog user</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>ensure I'm not losing important functionality</td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>continue to support my Line Office data search and discovery needs.</td>
  </tr>
</table>

### Description
Associate data catalog stories with this epic

### Tasks
- [ ] first task required to complete this epic
- [ ] second task required to complete this epic
- [ ] third task required to complete this epic

### References
<table>
  <tr>
    <td><b>Point of contact</b></td>
    <td>{name|email|room#|phone}</td>
  </tr>
  <tr>
    <td><b>Doc, Spreadsheet, etc.</b></td>
    <td>{link}</td>
  </tr>
</table>
