### ISSUE TITLE
SCDR Client Test with STAR granule metadata

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#1064]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>demo jockey</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       Show the SCDR client working with granule metadata generated by STAR
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>demonstrate success of the OneStop client!</td>
  </tr>
</table>

###Tasks
- [x] Remove JSON from the scdr-files response output
- [x] Confirm metadata from Weiguo is loading into OneStop
- [x] Add granule metadata to the ~psi-os-nesdis-demo~ onestop-test-data repo
- [x] Confirm loading based on manifest populates OneStop as expected
- [x] Try out the client against the test data

**Comment by StrayCat1** [comment]
"Remove JSON from the scdr-files response output"

Sadly I dont think that is possible.

**Comment by StrayCat1** [comment]
Coming up with some examples for the demo.

To follow along, set up the CLI as explained here - https://github.com/cedardevs/onestop/blob/1020-OneStopCLI/docs/public-user/cli/quickstart.md

Return number of available for collection - 
```
$ go run . scdr-files --available="doi:10.7289/V5BV7DSR" --server http://acf3425c8d41b11e9a12912cf37a7528-1694331899.us-east-1.elb.amazonaws.com/onestop-search
```

Get count with type and time range - 
```
$ go run . scdr-files  --stime 2019/07/01 --etime 2019/07/02 --available="doi:10.7289/V5BV7DSR" --server http://acf3425c8d41b11e9a12912cf37a7528-1694331899.us-east-1.elb.amazonaws.com/onestop-search
```

Search for metadata containing "ABI-L1b-RadF" (like a free text search) 
```
$ go run . scdr-files --metadata="ABI-L1b-RadF" --server http://acf3425c8d41b11e9a12912cf37a7528-1694331899.us-east-1.elb.amazonaws.com/onestop-search
```

Search for files with data between 2019/07/01 and 2019/07/02 of specific ABI type 
```
$ go run . scdr-files --date 07/01 --type="doi:10.7289/V5BV7DSR" --server http://acf3425c8d41b11e9a12912cf37a7528-1694331899.us-east-1.elb.amazonaws.com/onestop-search  
```

**Comment by mcquinne** [comment]
FYI the granule metadata from STAR is:
- added to the `onestop-test-data` repo
- loaded into the cloud psi-regsitry via the manifest checked into the repo
- available through OneStop under a new [SCDR File Demo collection](http://acf3425c8d41b11e9a12912cf37a7528-1694331899.us-east-1.elb.amazonaws.com/onestop/collections/details/5b58de08-afef-49fb-99a1-9c5d5c003bde)

**Comment by StrayCat1** [comment]
Check available files for collection - 
```
$ go  run . scdr-files --available="5b58de08-afef-49fb-99a1-9c5d5c003bde" --server http://acf3425c8d41b11e9a12912cf37a7528-1694331899.us-east-1.elb.amazonaws.com/onestop-search
{
  "count": 70875
}
```
Define a date range
```
$ cli scdr-files --available="5b58de08-afef-49fb-99a1-9c5d5c003bde" --server http://acf3425c8d41b11e9a12912cf37a7528-1694331899.us-east-1.elb.amazonaws.com/onestop-search --stime 2019/10/11 --etime 2019/10/12
{
  "count": 2320
}
```
Which is the same as- 
```
$ cli scdr-files --available="5b58de08-afef-49fb-99a1-9c5d5c003bde" --server http://acf3425c8d41b11e9a12912cf37a7528-1694331899.us-east-1.elb.amazonaws.com/onestop-search --date 2019/10/11
{
  "count": 2320
}
```
Get a list instead of count, use --type
```
scdr-files --type="5b58de08-afef-49fb-99a1-9c5d5c003bde" --server http://acf3425c8d41b11e9a12912cf37a7528-1694331899.us-east-1.elb.amazonaws.com/onestop-search
```

**Comment by StrayCat1** [comment]
Okay,  so we made some changes to match the input/output syntax a little more closely.  Available no longer takes args, but is a boolean flag (true if flag is present). 

`scdr-files --available`

Now users can specify a configuration for types to UUIDs. 

`scdr-files --available -t ABI-L1b-Rad --server http://acf3425c8d41b11e9a12912cf37a7528-1694331899.us-east-1.elb.amazonaws.com/onestop-search`

The output when `--available` flag is passed has also changed. 

```
OneStop ID  | FileIdentifier                     | Total files  | Description                                                                           |
----------- | ---------------------------------- | ------------ | ------------------------------------------------------------------------------------- |
abi-l1b-rad | gov.noaa.ncdc:C01501:ScdrFilesDemo |        71376 | SCDR Files Demo: NOAA GOES-R Series Advanced Baseline Imager (ABI) Level 1b Radiances
```

**Comment by StrayCat1** [comment]
Here is a new list of example commands (replace `go run .` with binary name, `cli` by default,  or `docker run cedardevs/onestop-cli:2.4.0-1020-OneStop-CLI`) 

List available STAR collections - 
```
$ go run .  scdr-files --available  --server http://acf3425c8d41b11e9a12912cf37a7528-1694331899.us-east-1.elb.amazonaws.com/onestop-search
OneStop ID                           | FileIdentifier        | Description                                                                                       |
------------------------------------ | --------------------- | ------------------------------------------------------------------------------------------------- |
135d2ebb-6bcd-47aa-8655-1be9d100c898 | gov.noaa.nodc:0122596 | Ocean Surface Topography Mission (OSTM) /Jason-3: Ancillary Files, 2015- (NCEI Accession 0122596)
11111111-1111-1111-1111-111111111111 | gov.noaa.ncdc:C01501 | NOAA GOES-R Series Advanced Baseline Imager (ABI) Level 1b Radiances
11111111-1111-1111-1111-222222222222 | gov.noaa.ncdc:C00864 | NOAA JPSS Visible Infrared Imaging Radiometer Suite (VIIRS) Sensor Data Record (SDR) from IDPS
99999999-9999-9999-9999-999999999999 | gov.noaa.ncdc:C01438 | NOAA JPSS Visible Infrared Imaging Radiometer Suite (VIIRS) Ice Thickness and Age Environmental Data Records (EDRs) from NDE
abi-l1b-rad | gov.noaa.ncdc:C01501:ScdrFilesDemo | SCDR Files Demo: NOAA GOES-R Series Advanced Baseline Imager (ABI) Level 1b Radiances
55555555-5555-5555-5555-555555555555 | gov.noaa.ncdc:C01433 | NOAA JPSS Visible Infrared Imaging Radiometer Suite (VIIRS) Cloud Type and Phase Environmental Data Record (EDR) from NDE
5dff9024-c9fb-4c70-809e-25dd1fa77764 | gov.noaa.nodc:0122597 | Ocean Surface Topography Mission (OSTM) /Jason-3: Auxiliary Files, 2015- (NCEI Accession 0122597)
66666666-6666-6666-6666-666666666666 | gov.noaa.ncdc:C01434 | NOAA JPSS Visible Infrared Imaging Radiometer Suite (VIIRS) Cloud Mask Environmental Data Record (EDR) from NDE
abi-l2-cmip | gov.noaa.ncdc:C01502 | NOAA GOES-R Series Advanced Baseline Imager (ABI) Level 2 Cloud and Moisture Imagery Products (CMIP)
dddddddd-dddd-dddd-dddd-dddddddddddd | gov.noaa.ncdc:C01445 | NOAA JPSS Visible Infrared Imaging Radiometer Suite (VIIRS) Aerosol Detection Environmental Data Record (EDR) from NDE
aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa | gov.noaa.ncdc:C01440 | NOAA JPSS Visible Infrared Imaging Radiometer Suite (VIIRS) Cloud Height (Top and Base) Environmental Data Record (EDR) from NDE
eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee | gov.noaa.ncdc:C01446 | NOAA JPSS Visible Infrared Imaging Radiometer Suite (VIIRS) Aerosol Optical Depth and Aerosol Particle Size Distribution Environmental Data Record (EDR) from NDE
glm-l2-lcfa | gov.noaa.ncdc:C01527 | NOAA GOES-R Series Geostationary Lightning Mapper (GLM) Level 2 Lightning Detection: Events, Groups, and Flashes
bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb | gov.noaa.ncdc:C01441 | NOAA JPSS Visible Infrared Imaging Radiometer Suite (VIIRS) Volcanic Ash Detection and Height Environmental Data Record (EDR) from NDE
ffffffff-ffff-ffff-ffff-ffffffffffff | gov.noaa.ncdc:C01447 | NOAA JPSS Visible Infrared Imaging Radiometer Suite (VIIRS) Ice Concentration and Ice Surface Temperature Environmental Data Records (EDRs) from NDE
11111111-1111-1111-1111-333333333333 | gov.noaa.ncdc:C01432 | NOAA JPSS Visible Infrared Imaging Radiometer Suite (VIIRS) Land Surface Albedo Environmental Data Record (EDR) from NDE
77777777-7777-7777-7777-777777777777 | gov.noaa.ncdc:C01436 | NOAA JPSS Visible Infrared Imaging Radiometer Suite (VIIRS) Snow Cover Environmental Data Record (EDR) from NDE
cccccccc-cccc-cccc-cccc-cccccccccccc | gov.noaa.ncdc:C01444 | NOAA JPSS Visible Infrared Imaging Radiometer Suite (VIIRS) Nighttime Cloud Optical Microphysical Properties (NCOMP) Environmental Data Record (EDR) from NDE
88888888-8888-8888-8888-888888888888 | gov.noaa.ncdc:C01437 | NOAA JPSS Visible Infrared Imaging Radiometer Suite (VIIRS) Daytime Cloud Optical and Microphysical Properties (DCOMP) from NDE
abi-l2-fdc | gov.noaa.ncdc:C01520 | NOAA GOES-R Series Advanced Baseline Imager (ABI) Level 2 Fire/Hot Spot Characterization (FDC)
```

Get detailed summary (w/ count)  by using type shortname - 
```
$ go run .  scdr-files --available -t abi-l1b-rad  --server http://acf3425c8d41b11e9a12912cf37a7528-1694331899.us-east-1.elb.amazonaws.com/onestop-search
OneStop ID  | FileIdentifier                     | Total files  | Description                                                                           |
----------- | ---------------------------------- | ------------ | ------------------------------------------------------------------------------------- |
abi-l1b-rad | gov.noaa.ncdc:C01501:ScdrFilesDemo |        71376 | SCDR Files Demo: NOAA GOES-R Series Advanced Baseline Imager (ABI) Level 1b Radiances
```

List those granules - 
```
$ go run .  scdr-files -t ABI-L1B-RAD  --server http://acf3425c8d41b11e9a12912cf37a7528-1694331899.us-east-1.elb.amazonaws.com/onestop-search
```

Filter using --date (see docs for behavior) 
```
go run .  scdr-files -t ABI-L1B-RAD  --date 2019/10/11 --server http://acf3425c8d41b11e9a12912cf37a7528-1694331899.us-east-1.elb.amazonaws.com/onestop-search 
```

Define a start and end time 
```
go run .  scdr-files -t ABI-L1B-RAD  --stime 2019/10/11 --etime 2019/10/12 --server http://acf3425c8d41b11e9a12912cf37a7528-1694331899.us-east-1.elb.amazonaws.com/onestop-search 
```

**Comment by StrayCat1** [comment]
You can now use `--cloud` and `--test` to hit the aws instances and the sciapps instances respectively.
