### ISSUE TITLE
SCDR client demo prep

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#1069]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>demo jockey</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       demonstrate the onestop client scdr-files command
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>demonstrate the value of OneStop's OpenAPI and tech stack</td>
  </tr>
</table>

###Tasks
- [x] Load/confirm GOES16 ABI Radiance collection record in OS cloud
- [x] Load granules for SCDR in OS cloud
- [x] identify tests to compare legacy CLI and new CLI performance
- [x] Document gaps between legacy CLI and new CLI
- [x] Be prepared to demo client

**Comment by StrayCat1** [comment]
Demo commands for AWS instance - 
Here is a new list of example commands (replace `go run .` with binary name, `cli` by default,  or `docker run cedardevs/onestop-cli:2.4.0-1020-OneStop-CLI`) - 

List available STAR collections - 
```
$ go run .  scdr-files --available  --server http://acf3425c8d41b11e9a12912cf37a7528-1694331899.us-east-1.elb.amazonaws.com/onestop-search
OneStop ID                           | FileIdentifier        | Description                                                                                       |
------------------------------------ | --------------------- | ------------------------------------------------------------------------------------------------- |
135d2ebb-6bcd-47aa-8655-1be9d100c898 | gov.noaa.nodc:0122596 | Ocean Surface Topography Mission (OSTM) /Jason-3: Ancillary Files, 2015- (NCEI Accession 0122596)
11111111-1111-1111-1111-111111111111 | gov.noaa.ncdc:C01501 | NOAA GOES-R Series Advanced Baseline Imager (ABI) Level 1b Radiances
11111111-1111-1111-1111-222222222222 | gov.noaa.ncdc:C00864 | NOAA JPSS Visible Infrared Imaging Radiometer Suite (VIIRS) Sensor Data Record (SDR) from IDPS
99999999-9999-9999-9999-999999999999 | gov.noaa.ncdc:C01438 | NOAA JPSS Visible Infrared Imaging Radiometer Suite (VIIRS) Ice Thickness and Age Environmental Data Records (EDRs) from NDE
abi-l1b-rad | gov.noaa.ncdc:C01501:ScdrFilesDemo | SCDR Files Demo: NOAA GOES-R Series Advanced Baseline Imager (ABI) Level 1b Radiances
55555555-5555-5555-5555-555555555555 | gov.noaa.ncdc:C01433 | NOAA JPSS Visible Infrared Imaging Radiometer Suite (VIIRS) Cloud Type and Phase Environmental Data Record (EDR) from NDE
5dff9024-c9fb-4c70-809e-25dd1fa77764 | gov.noaa.nodc:0122597 | Ocean Surface Topography Mission (OSTM) /Jason-3: Auxiliary Files, 2015- (NCEI Accession 0122597)
66666666-6666-6666-6666-666666666666 | gov.noaa.ncdc:C01434 | NOAA JPSS Visible Infrared Imaging Radiometer Suite (VIIRS) Cloud Mask Environmental Data Record (EDR) from NDE
abi-l2-cmip | gov.noaa.ncdc:C01502 | NOAA GOES-R Series Advanced Baseline Imager (ABI) Level 2 Cloud and Moisture Imagery Products (CMIP)
dddddddd-dddd-dddd-dddd-dddddddddddd | gov.noaa.ncdc:C01445 | NOAA JPSS Visible Infrared Imaging Radiometer Suite (VIIRS) Aerosol Detection Environmental Data Record (EDR) from NDE
aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa | gov.noaa.ncdc:C01440 | NOAA JPSS Visible Infrared Imaging Radiometer Suite (VIIRS) Cloud Height (Top and Base) Environmental Data Record (EDR) from NDE
eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee | gov.noaa.ncdc:C01446 | NOAA JPSS Visible Infrared Imaging Radiometer Suite (VIIRS) Aerosol Optical Depth and Aerosol Particle Size Distribution Environmental Data Record (EDR) from NDE
glm-l2-lcfa | gov.noaa.ncdc:C01527 | NOAA GOES-R Series Geostationary Lightning Mapper (GLM) Level 2 Lightning Detection: Events, Groups, and Flashes
bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb | gov.noaa.ncdc:C01441 | NOAA JPSS Visible Infrared Imaging Radiometer Suite (VIIRS) Volcanic Ash Detection and Height Environmental Data Record (EDR) from NDE
ffffffff-ffff-ffff-ffff-ffffffffffff | gov.noaa.ncdc:C01447 | NOAA JPSS Visible Infrared Imaging Radiometer Suite (VIIRS) Ice Concentration and Ice Surface Temperature Environmental Data Records (EDRs) from NDE
11111111-1111-1111-1111-333333333333 | gov.noaa.ncdc:C01432 | NOAA JPSS Visible Infrared Imaging Radiometer Suite (VIIRS) Land Surface Albedo Environmental Data Record (EDR) from NDE
77777777-7777-7777-7777-777777777777 | gov.noaa.ncdc:C01436 | NOAA JPSS Visible Infrared Imaging Radiometer Suite (VIIRS) Snow Cover Environmental Data Record (EDR) from NDE
cccccccc-cccc-cccc-cccc-cccccccccccc | gov.noaa.ncdc:C01444 | NOAA JPSS Visible Infrared Imaging Radiometer Suite (VIIRS) Nighttime Cloud Optical Microphysical Properties (NCOMP) Environmental Data Record (EDR) from NDE
88888888-8888-8888-8888-888888888888 | gov.noaa.ncdc:C01437 | NOAA JPSS Visible Infrared Imaging Radiometer Suite (VIIRS) Daytime Cloud Optical and Microphysical Properties (DCOMP) from NDE
abi-l2-fdc | gov.noaa.ncdc:C01520 | NOAA GOES-R Series Advanced Baseline Imager (ABI) Level 2 Fire/Hot Spot Characterization (FDC)
```

Get detailed summary (w/ count)  by using type shortname - 
```
$ go run .  scdr-files --available -t abi-l1b-rad  --server http://acf3425c8d41b11e9a12912cf37a7528-1694331899.us-east-1.elb.amazonaws.com/onestop-search
OneStop ID  | FileIdentifier                     | Total files  | Description                                                                           |
----------- | ---------------------------------- | ------------ | ------------------------------------------------------------------------------------- |
abi-l1b-rad | gov.noaa.ncdc:C01501:ScdrFilesDemo |        71376 | SCDR Files Demo: NOAA GOES-R Series Advanced Baseline Imager (ABI) Level 1b Radiances
```

List those granules - 
```
go run .  scdr-files -t ABI-L1B-RAD  --server http://acf3425c8d41b11e9a12912cf37a7528-1694331899.us-east-1.elb.amazonaws.com/onestop-search
```

Filter using --date (see docs for behavior) 
```
go run .  scdr-files -t ABI-L1B-RAD  --date 2019/10/11 --server http://acf3425c8d41b11e9a12912cf37a7528-1694331899.us-east-1.elb.amazonaws.com/onestop-search 
```

Define a start and end time 
```
go run .  scdr-files -t ABI-L1B-RAD  --stime 2019/10/11 --etime 2019/10/12 --server http://acf3425c8d41b11e9a12912cf37a7528-1694331899.us-east-1.elb.amazonaws.com/onestop-search 
```

**Comment by StrayCat1** [comment]
Doc with onestop-cli scdr-files comparison 
https://docs.google.com/document/d/10ksaOcSl8lUag6Y0hFQhj5Lqnd4l2fB8ghq8x0Xg7AE/edit?usp=sharing

**Comment by StrayCat1** [comment]
Benchmark CLI - 
https://docs.google.com/document/d/17NX3zJ-A2QuTFMkWqLbdMGPyESdSZKhao2-IjYMq4a8/edit?usp=sharing

**Comment by StrayCat1** [comment]
```
docker run cedardevs/onestop-cli:2.4.0 scdr-files --help

docker run  cedardevs/onestop-cli:2.4.0 scdr-files --available --cloud
docker run cedardevs/onestop-cli:2.4.0 scdr-files  -t  ABI-L1b-Rad --available --cloud 

docker run cedardevs/onestop-cli:2.4.0  scdr-files --cloud --file OR_ABI-L1b-RadF-M6C02_G16_s20192791130286_e20192791139594_c20192791140045.nc

docker run cedardevs/onestop-cli:2.4.0  scdr-files --cloud --re-file .*_s201903270306350_e201903270308000_c201904110024560.*

docker run cedardevs/onestop-cli:2.4.0  scdr-files --metadata "Land Surface Albedo Environmental Data Record"

docker run cedardevs/onestop-cli:2.4.0  scdr-files --date 10/01 --cloud

docker run cedardevs/onestop-cli:2.4.0 scdr-files --area "POLYGON(( 22.686768 34.051522, 30.606537 34.051522, 30.606537 41.280903,  22.686768 41.280903, 22.686768 34.051522 ))"


docker run cedardevs/onestop-cli:2.4.0  scdr-files --satname GOES-16

docker run cedardevs/onestop-cli:2.4.0  scdr-files --label "ABI > Advanced Baseline Imager" --cloud

docker run cedardevs/onestop-cli:2.4.0 scdr-files  -t  ABI-L1b-Rad --stime "October 1st 2019 at 17:30" --etime "2019-10-01 17:30:30"  --cloud
```

**Comment by StrayCat1** [comment]
re: identify tests to compare legacy CLI and new CLI performance

Meeting with Weiguo to get metrics and other statistics on usage from Weiguo next week.
