### ISSUE TITLE
EPIC: Search for Services

### ISSUE THREAD

**Issue by zebdelk** [cedardevs/onestop#1076]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>Data manager or public user</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>find other services and portals directly</td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>use advanced features that don't apply to all collections/granules, but specific projects</td>
  </tr>
</table>

### Description

Design a service index, and allow parsing and loading of metadata about services. Create search endpoints for these services, and make them available through the UI.

Out of scope: designing a mechanism to connect collections and granules to services, so that services can be linked as suggested results.

### Assumptions

- We can determine a reasonable definition and standard for service metadata

### Tasks
- [ ] determine what services metadata input looks like
    - [ ] consult with Jesse and Anna about if we have any iso metadata for services that we should be supporting, or other standards
    - [ ] consider the UMM model, which distinguishes services into two groups: UMM-tools for web-based services and downloadable tools, and UMM-services for back end services to connect systems together
- [ ] create avro schemas and index mappings for services
- [ ] parse and ingest services through inventory manager, creating new topics to parallel collection and granules
- [ ] index service metadata into ES
- [ ] add rest endpoints to the search API for services, including full documentation in the openapi.yaml
- [ ] (possibly out of scope / tied to direct UI searches of granules) design and add UI support for direct searches against granules
