### ISSUE TITLE
Public user API docs update

### ISSUE THREAD

**Issue by ajakz** [cedardevs/onestop#1084]
### Tasks
- [x] Add table of contents
- [x] Add content to QuickStart
~- [ ] Reorganize for good navigational flow~
- [x] revisit Query Syntax doc to focus on answering "How do I...?", with features explanations being a sort of appendix
- [x] Fill in any holes
- [x] Fill in table contents on https://cedardevs.github.io/onestop/public-user.html for the Search API

### Reference top level directory
https://github.com/cedardevs/onestop/tree/master/docs/public-user/api

**Comment by erinreeves** [comment]
Added more tasks for things noticed need to update.
Also discovered urls to internal docs need to be /onestop/public-user like <a href="/onestop/public-user">Public User Navigation Guide Home</a>

Github Jenkyll webpage generation:
https://github.com/cedardevs/onestop/blob/master/docs/_config.yml

In our repo at https://github.com/cedardevs/onestop/blob/master/docs/_config.yml
https://guides.github.com/features/pages/#changes

And here's the settings for it!
https://github.com/cedardevs/onestop/settings

**Comment by erinreeves** [comment]
1084-public_user_api_docs_update
