### ISSUE TITLE
Create endpoint for searchable/attributes fields information

### ISSUE THREAD

**Issue by ajakz** [cedardevs/onestop#1088]
## Summary
Anytime we make changes to our search index, the searchable fields (attributes in response) documentation needs to be updated. This is a tedious task that's easy to forget and makes our documentation hard to keep up to date.

## Tasks
- [x] Create self-describing endpoint(s?) on search api that GETs the current mappings from Elasticsearch and creates something to explain field searchability like this https://github.com/cedardevs/onestop/blob/v2.3.1/docs/usage/search-api-responses.md#attributes-fields 
  - [x] Create a new DocumentationController? Future endpoints can then be added as we support more self-documenting endpoints. Possible URL for this user story: `{host}/docs/{type}/attributes`
- [x] Update query-syntax documentation to refer to the correct URL(s)

## Extras
- Consider STAC spec in how this is built https://stacspec.org/STAC-api.html#tag/Capabilities

Note on this: 
We have some conflicting terminology with STAC and the defined endpoints are somewhat vague at the moment. Also, STAC is still not at v1.0 and their github repo is warning about major changes being likely in the near future. These things considered, we may want to consider supporting this with a wrapper around our API, which would be part of a separate story (since that's more involved).
