### ISSUE TITLE
Document workflow for metadata manager

### ISSUE THREAD

**Issue by ajakz** [cedardevs/onestop#1092]
## Tasks
- [x] Make sure all top level folders that should have a readme in them are linked in root README (API, internal developer, metadata-manager, operator, public-user)
- [x] Change link to yaml endpoints to https://app.swaggerhub.com/apis/cedarbot/OneStop/2.4.0
- [x] Add comment in developer guide quick tips that Kubernetes keeps state in its secrets. Need to do kubernetes cleanup when you see "<chart-name> has no deployed releases" plus "and it turns out that helm ls -a reveals that chart was stuck in "uninstalling""
https://kubernetes.io/docs/tasks/configmap-secret/managing-secret-using-kubectl/#clean-up
- [x] Create outline for use case workflow through documentation
- [x] Create outline for use case workflow through documentation
- [ ] change sciapps references (or general test system) to cedardevs.org
- [x] Remove v2 references and folders
- [x] Develop collection level metadata record example, or link to one if exists externally.
- [x] Ensure granule metadata states the granule's parentIdentifier should be its collection record's id (a UUID)
- [x] How to post record via IM using XML
- [x] How to post record via IM using JSON
- [x] Remove Previous/Next links
- [x] Make sure documentation home link on top of all docs to what their particular subcategory is.
- [x] Added Top link at bottom of all docs
- [x] Migrate existing docs to the right location
- [x] Update existing docs where there are gaps
- [x] Create new documents where there are gaps
- [ ] Give a demonstration to metadata group (Amanda/Paula and Debby Brahm)

**Comment by erinreeves** [comment]
Should all docs have time estimate?

**Comment by erinreeves** [comment]
Should all docs need the subcategory home link? Asking 'cuz some subcategories are now linking to other ones, so browser history wouldn't work to get to it. The user would have to analyze the url and change it.

Finding a lot of duplicate docs on metadata uploading and indexing. Allowing for more complex information to be in the developer area.

**Comment by erinreeves** [comment]
We have a document inmetadata-mgr describing how to upload data to OneStop via kafka. Is this method of upload okay to mention/encourage?
I wanted to make sure it wasn't surpassing anything we do in Registry.
