### ISSUE TITLE
Document workflow for Internal (OS) Developer

### ISSUE THREAD

**Issue by ajakz** [cedardevs/onestop#1093]
## Summary
We have two developer types that would need access to our docs -- this user story covers the internal developer that is contributing to our codebase. Someone new to our team should be able to get setup and on the road to happy coding from these docs! 

https://cedardevs.github.io/onestop/developer/

## Tasks
- [x] Create outline/table contents for use case workflow through documentation
- [x] Update existing docs where there are gaps
- [x] Create new documents where there are gaps(created README's for the developer, testing, and integration-testing directories so they would show up as index.html when going to that directory)
- [x] Create a table of contents to all docs at this level + other semi external docs (https://github.com/cedardevs/onestop-clients/tree/master/docs)
- [x] Updated quickstart; reorganized to be clearer and more in order of steps to perform (removed 2 separate setup categories) and simplified
- [x] Add a link to client docs

**Comment by erinreeves** [comment]
Create outline for use case workflow through documentation: where is this and isn't this the quickstart?

Migrate existing docs to the right location, which is where?

  - [ ] Figure where OneStop client docs should go - Dave, what this?

**Comment by erinreeves** [comment]
Is the api-versioning still valid?
https://github.com/cedardevs/onestop/blob/1093-doc_internal_dev/docs/developer/api-versioning.md

Is Cas still relevant for our system?

**Comment by erinreeves** [comment]
Response:
dave:
Nothing has changes with CAS on-prem so yes still using that to secure registry
/v1 and /v2 should be testable right?
No changes that I'm aware of on hot fix or publishing tags (edited)

**Comment by erinreeves** [comment]
We've already got a client doc locally in docs/developer. Should we remove in favor of pointing to client docs in client app?

There is Previous/Tope of Page/Next links at the bottom of each page. But the next/previous point to random docs. Should we remove? Or have order reflect table of contents?

**Comment by erinreeves** [comment]
We've got cli docs duplicated in docs/developer/cli and the onestop-clients repo. what to do? which should be the source of truth?

**Comment by dneufeldcu** [comment]
Reviewing updating testing docs.
