### ISSUE TITLE
Document workflow for Operator

### ISSUE THREAD

**Issue by ajakz** [cedardevs/onestop#1094]
## Tasks
- [ ] Create outline for use case workflow through documentation
- [ ] Migrate existing docs to the right location
- [ ] Update existing docs where there are gaps
  - [ ] TBD
  - [ ] TBD
- [ ] Create new documents where there are gaps
  - [ ] TBD
  - [ ] TBD
