### ISSUE TITLE
Document workflow for external developer

### ISSUE THREAD

**Issue by ajakz** [cedardevs/onestop#1096]
## Summary
We have two developer types that would need access to our docs -- this user story covers the external developer that is building a tool that has to interface with OneStop somewhere. 

A lot of the documentation that these types of users would need will probably already exist throughout the Public User and Metadata Manager paths, but there are some definite gaps in those two user types that we'll need to populate info for here. We will want to point to existing docs where we can.

## Tasks
- [ ] Create outline for use case workflow through documentation
- [ ] Create documents for developer types 
  - [ ] Thin portal creator
  - [ ] Someone pushing data into registry (kafka in)
  - [ ] Someone pulling data from registry (kafka out)

**Comment by erinreeves** [comment]
Reference OneStop/api docs? 
Or is this only the python-client?

**Comment by erinreeves** [comment]
Suspect this is more "update readmes/docs for python-client". So working on that.

**Comment by erinreeves** [comment]
Followed steps in the python-client/scripts readme.
Need more info on what the next steps would be. Such as which scripts a SME user should/would use. Perhaps 1 line summary of each script in there.
