### ISSUE TITLE
Tag and Release version 2.4.2

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#1117]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>users</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       Use the list view and WCAG improvements that have been made to master.
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>be more productive in my Earth Science research activities</td>
  </tr>
</table>

### Tasks
- [x] Tag a release
- [x] Push it to sciapps
- [x] Perform internal checklist
- [x] Push to dev/test 
- [x] Request security review

**Comment by dneufeldcu** [comment]
Pushed to dev and test succussfully. Having issues with JIRA at the moment so still need to request security review.

**Comment by dneufeldcu** [comment]
Vicke has tagged the code for security review.
