### ISSUE TITLE
EPIC: SCDR-files (2nd pass)

### ISSUE THREAD

**Issue by StrayCat1** [cedardevs/onestop#1120]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>User of the OneStop CLI / STAR user</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>use all of the flags supported by scdr-files in the OneStop CLI</td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>migrate from SCDR files to OneStop</td>
  </tr>
</table>

### Description
We need to continue our efforts to support the STAR SCDR-files use case. Before we can do that, there are a few additional fields we need to add to the ES indices. 

### Assumptions
* Not ALL flags and syntaxes need to be supported. Get usage stats from STAR. 
* Sorting is implemented or staged date it indexed  (to support --since)  
* File level metadata is added to search indices

### Tasks
- [x] Get scdr-files usage stats 
- [x] Sorting is implemented or staged date it indexed/searchable (to support --since)  
- [x] Support --since
- [x] Support --gap 
- [ ] Support date filters (--year, --month,--day) 
- [ ] --sha1
- [ ] --doy

### References
<table>
  <tr>
    <td><b>Point of contact</b></td>
    <td>Chris (StrayCat1) / Dave N / Weiguo</td>
  </tr>
  <tr>
    <td><b>Doc, Spreadsheet, etc.</b></td>
    <td>https://docs.google.com/document/d/10ksaOcSl8lUag6Y0hFQhj5Lqnd4l2fB8ghq8x0Xg7AE/edit?usp=sharing</td>
  </tr>
  <tr>
    <td><b>Cloud IPT</b></td>
    <td>https://docs.google.com/document/d/1tXFllcGmHnDUqlz6pQKTGkW61MnMYRksstlbWiUZQ2o/edit</td>
  </tr>
</table>
