### ISSUE TITLE
EPIC: Saved Search

### ISSUE THREAD

**Issue by zebdelk** [cedardevs/onestop#1121]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>Person with login.gov</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>save my searches within the app</td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>{use-case}</td>
  </tr>
</table>

### Description

Create a login-based feature that can be expanded and built from in the future. This feature requires no roles, as anyone with a public login is allowed to use it.

### Tasks
- [ ] user service backend (DB) required
    - [ ] table that saves `userid`, `name`, `url`, where name is a user-provided label for the saved search and url contains the context (collection vs granules) and query parameters needed to recreate the search
- [ ] replace spring security with pac4j
- [ ] UI mockups for user landing page, and separate page/sections for:
    - saved searches
    - cart
    - CAS-features (dashboards)
- [ ] a star button or similar at the top of searches to save (prompts to log in? only available if logged in?)
- [ ] a way to view saved searches (see mockups for user / saved search page ideas, or via hamburger menu?)
- [ ] a way to delete saved searches

**Comment by forgo** [comment]
User Features
-----------------

# Authentication Mechanism
- user api, micronaut, pac4j integration with OpenID client / login.gov api
- check out [this tutorial](https://medium.com/sqooba/securing-a-single-page-app-through-openid-connect-sso-using-an-explicit-flow-with-play2-and-pac4j-7f6c4f46e31a) for some guidance on proper SPA security
- follow these examples for:
  - [using pac4j in a new framework (micronaut)](https://www.pac4j.org/docs/how-to-implement-pac4j-for-a-new-framework.html)
  - and [using the OpenID Connect protocol supported by login-gov with pac4j](https://www.pac4j.org/docs/clients/openid-connect.html)

Consider storing our own user states in the following ways:
```
USER.USERS
id | login_gov_id | createdDate | updatedDate | lastLoginDate | 

USER.AUTHORIZATIONS
id | roles | 
```

Features requiring a `login-gov` authn/authz:

# Saved Searches
- First rough-pass could simply save the url (or the JSON serialized filter state which derives it)
- one of these "saved" could be as simple as a row in a PostGreSQL for the login-gov id (not email)

```
USER.SAVED_SEARCHES (LIMIT per user_id = 100)
id  | user_id       | name             | description?                                        | filter
123   456             "Jurassic Park"    "OneStop Search for Michael-Crichton-related data"  | { JSON }

```
--------
# Stretch Goals / Future Considerations
## Cart (limited login?)
- Do we want to make this filter-based instead of putting individual granules in the cart?
  - if so, we would want to make a "FilterSummary" Component that can be used to visually display a search filter
  - we can still allow for selecting individual granules, but instead of "add all to cart" individually, there can be an "add filter to cart"

## Favorites 
- Favorites (equivalent of Amazon "wish list" for Collections and Granules)
  - Star icon (checkbox equivalent) on the following components to toggle:
    - List View / Grid View Collection Item, Collection Details Page
  - Dedicated `/favorites` and/or user `/dashboard` with all user-specific state

```
USER.FAVORITES (LIMIT per user_id = 100)
id  | user_id       | collectionIds
678   456             [ JSON ]

```

```
// UI reducers for logged in features (synced to local storage and to backend store):
userFavorites: {
    collections: [id1, id2, ...],
    granules: [id1, id2, ...]
}
```

## Trending
- Track clicks on cart download links?
  - limit to collection IDs, so if a filter is using collections = ['a'] or collections = ['a','b',...]
    - 1) onClick -> publish event to user service w/those ids
    - 2) user service retrieves from backing store the "trending" collections:
         e.g. - let trending = { 'a': 0, 'b', 3, ... }
    - 3) user service merges the event's collections as an increment
         e.g. - event.downloadedCollections.forEach { cid -> trending[cid] = trending[cid] + 1 }

- Machine Learning?

## Autocomplete
- Leverage Elasticsearch's built-in [Completion Suggester](https://www.elastic.co/guide/en/elasticsearch/reference/7.5/search-suggesters.html#completion-suggester)

## Notifications

Ideas:
```
// pseudo-code

// on login, retrieve the remote user information and hydrate into redux


// otherwise, 

const favoriteCollectionIds = [ "h8_id", ... ] // state.userFavorites.collections
const favoriteCollections = getCollections(favoriteCollectionIds)
// -> [ { id: "h8_id", title: "Himawari 8", ... }, ...]
const notifications = favoriteCollections.forEach(c => {
    return `The "${c.title}" collection has X (more|less) granules since your last login on ${lastLoginDate}`
})
```

## Multi-Authentication Mechanisms
Allow NOAA users to login via CAS and leverage actual Authorization to do administrative things via the UI...

**Comment by dneufeldcu** [comment]
Working on CORS support
