### ISSUE TITLE
EPIC: Subject Matter Expert Function Support

### ISSUE THREAD

**Issue by mcquinne** [cedardevs/onestop#1132]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>subject matter expert</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>trigger custom functions based on granule metadata</td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>extract rich metadata, populate custom DBs, etc.</td>
  </tr>
</table>

### Description
At long last! Time to support SME functions!

### Use Cases
1. GIS: Populate a spatial DB with granule-level metadata to support map services
2. PAD: Support arbitrary, numerical fields for filtering, either in OneStop itself or a downstream DB
3. OER: Tag incoming files such that they can be easily found in the search API by a thin portal
4. CI: Trigger custom metadata extraction functions based on ingest stream and/or collection

### Assumptions
- We have a mechanism for grouping sets of granules together (#1124)
- We are operating in an environment where serverless functions are available (e.g. AWS Lambda)

### Tasks
- [ ] Design a granule grouping mechanism with these use cases in mind (see #1124)
- [ ] Determine how functions will be executed
- [ ] Design data interface going to and from functions
- [ ] Provide support for testing, e.g. test harness, dry-run capability, etc.

### References
<table>
  <tr>
    <td><b>Point of contact</b></td>
    <td>Jesse Varner (GIS), Charles Anderson (PAD)</td>
  </tr>
  <tr>
    <td><b>Doc, Spreadsheet, etc.</b></td>
    <td>TODO: get example file detail fields from Chuck</td>
  </tr>
</table>

**Comment by dneufeldcu** [comment]
A new project level GCMD keyword has been established for PAD:
SanctSound > NOAA-Navy Sanctuary Soundscapes Monitoring Project

Perhaps this can be used as the initial grouping.
