### ISSUE TITLE
Drop support for IE

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#1133]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>modern browser based web application</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       balance support for legacy browsers alongside of  driving new features available in ES6 and maintenance costs
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>continue to have a great user experience for the majority of users</td>
  </tr>
</table>

### Tasks
- [x] Drop support for IE (not edge) - Update docs here
https://github.com/cedardevs/onestop/blob/eb15c93e6bbe6f1179ced131d76d2de26443fe16/docs/public-user/ui/quickstart.md
- [x] Provide message in the UI when browser IE is used recommending upgrading to one of the supported browser versions.
this is a javascript browser detection function to determine client browser and provide pop-up warning they are using an unsupported browser and we recommend switching to a supported browser - list supported versions.
- [x] Update existing message of unsupported browsers to point to new document location: https://cedardevs.github.io/onestop/public-user/ui/quickstart.html

### Reference
For OneStop last quarter of calendar 2019 only 65 users out of 2100 (~3%) used the legacy browser IE11. For this reason and the LOE associated with ongoing support for IE11, and the impacts to the web bundle size, we will drop support for IE11 by our version 3.0 release.

**Comment by erinreeves** [comment]
For reference:
elliott:chewie:  11:46 AM
@erin.reeves and @dave there is an existing isBrowserUnsupported function in our browserUtils.js file being used in the Root component. Right now it does vanilla JavaScript checks to see if “flex” is available to determine compatibility, but if we want to add checks for specific browsers using some tool, that would be the place to put it, since we already have an unsupported message component <BrowserUnsupportedWarning />
11:48
all you gotta do is make a:
if( checkBrowser !== supported) {
  unsupported = true
(edited)
11:49
and then that function will do the rest by returning unsuppoted=true at the end if anything was caught
