### ISSUE TITLE
Add Derived Field Info to Attributes Documentation Endpoint

### ISSUE THREAD

**Issue by ajakz** [cedardevs/onestop#1137]
## Background
Users want to know how parsed fields correspond to fields in the index, but this can be difficult for us to maintain with an evolving index. Enter: more automated documentation controls!

## Tasks
- [ ] Add [a _meta object](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-meta-field.html) for the fields to the 3 mappings that, at a minimum, describes if and how that search field is derived from a ParsedRecord field
- [ ] Add support for the new `_meta` information in the DocumentationService in the Search API
- [ ] At a minimum, add a test that verifies every field in the mapping has a populated `_meta` field. This way new fields will cause a test to fail, helping us stay on top of documentation.
