### ISSUE TITLE
HIP: Rewrite ISO Parser in Java

### ISSUE THREAD

**Issue by ajakz** [cedardevs/onestop#1138]
## Background
Since Java 11 is pretty cool and Groovy is getting outdated, we will eventually need to rewrite the ISO Parser in Java. The pain of this could be alleviated by using [JSoup](https://jsoup.org/).

## Tasks
- [ ] Do the thing!
- [ ] Bonus round: While we're here in the weeds, it might be a good time to revist #527 and implement a key-value config, with key as the field we're storing and value being the path. This could potentially be an easier solution than replicating what the groovy code is doing anyway.
- [ ] Extra bonus round: If we pursue the key-value config solution, another self-documenting endpoint could be added around it... 🤔

**Comment by ajakz** [comment]
Wrong repo -- cedardevs/schemas#28
