### ISSUE TITLE
2.x Metadata feature requests

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#1147]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>metadata SME</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       ensure a seemless transition from the data catalog to onestop
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>continue to support the NOAA community</td>
  </tr>
</table>

### Tasks

- [x] links/service links (This is critical since some links are not being displayed and users won't have access https://github.com/cedardevs/onestop/issues/985)
- [ ] ~keywords (initially it might be sufficient to have a plan for future releases)~
- [x] evaluate default search fields
- [ ] ~credit (should be displayed and queryable)~
- [ ] ~contacts (should be displayed and queryable)~

### Assumptions

- Works with 2.x code, i.e. with `admin` instead of `indexer`
- IM will not be deployed to support this
- Metadata will not be reindexed to support this 

### Notes

- Just displaying keywords in a tab on the collection landing pages is good enough for now
- Optional: clicking on a keyword does a search for collections with that keyword?
- Consider adding additional text fields into the default search fields, e.g. `individualNames`. See: https://github.com/cedardevs/onestop/blob/master/search/src/main/resources/application.yml#L34

**Comment by ajakz** [comment]
As part of #1011, default file boosts will now be:

```yaml
  fields:
    title: 4
    filename: 4
    keywords: 3
    individualNames: 3
    description: 2
    fileIdentifier: 1
    parentIdentifier: 1
    doi: 1
```

....unless something critical is missed in that list

**Comment by zebdelk** [comment]
Thinking thin portal for keywords in 2.x timeframe

**Comment by zebdelk** [comment]
planning on holding off on keywords until we have a overall plan, and working on service links on both master and 2.4 release paths
