### ISSUE TITLE
EPIC: Source-Based Roles

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#1149]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>administrator</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>authorize users to modify metadata based on its source</td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>limit read/write access to metadata</td>
  </tr>
</table>

### Description
We want to limit read/write access to metadata so that only authorized users are allowed to modify the set of metadata which they are managing. E.G. Justin and Nico can only modify the metadata that they are responsible for.

### Assumptions
- Our permissions will be based around the `source` field, as it is part of the registry URL and also the input topic names
- This will replace the hard-coded source names that we have today like "common-ingest" and "comet"

### Tasks
- [ ] Create a mechanism to dynamically CRUD sources
- [ ] Associate roles with sources
- [ ] Associate users with roles

### Notes
- We should probably constrain the characters that can be used in the name of a source (e.g. no question marks, etc.)
