### ISSUE TITLE
EPIC: {name}

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#1154]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>{stakeholder role}</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>{feature}</td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>{use-case}</td>
  </tr>
</table>

### Description
{description}

### Assumptions
- {assumption 1}

### Tasks
- [ ] first task required to complete this epic
- [ ] second task required to complete this epic
- [ ] third task required to complete this epic

### References
<table>
  <tr>
    <td><b>Point of contact</b></td>
    <td>{name|email|room#|phone}</td>
  </tr>
  <tr>
    <td><b>Doc, Spreadsheet, etc.</b></td>
    <td>{link}</td>
  </tr>
</table>

**Comment by dneufeldcu** [comment]
Demo template not real story
