### ISSUE TITLE
Index analysis + error information

### ISSUE THREAD

**Issue by mcquinne** [cedardevs/onestop#1156]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>metadata manager</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       see analysis and error information in a dashboard
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>observe information about the metadata inventory to identify errors and potential improvements</td>
  </tr>
</table>

### Background

We already collect both `analysis` and `errors` information from each `ParsedRecord` that flows through our system, e.g. whether or not it has a title or if some value could not be parsed. This information should be indexed in Elasticsearch so it can be easily observed through Kibana. At the moment, you can only retrieve all this information by explicitly GETing a given record from the registry's REST API. We've demonstrated pushing some of this information into Elasticsearch via Kafka Connect, but we'd prefer to index it using the new indexer module so that:

- We no longer need to deploy Kafka Connect
- We can control the related Elasticsearch index mapping(s)
- You get the analysis and error information for free when you deploy the OSIM system

### Tasks
- [ ] Decide how to organize analytical and error information in Elasticsearch, e.g. should they be in separate indices?
- [ ] Add Elasticsearch index mappings for the record-level analysis and error information and apply them with `indexer`
- [ ] Index the `analysis` block of information for every incoming record
- [ ] Index any `errors` for every incoming record (and remove them from ES if there aren't any anymore)
- [ ] (optional) Expand application config / ES client logic to support sending this info to a separate ES cluster than the search info
- [ ] (optional) Index OneStop validation errors in addition to to the `analysis` block so users can discover why records are not discoverable

**Comment by ajakz** [comment]
- [x] Refine analysis & errors index mappings
- [x] Split IndexingHelpers into classes for record transformation, validation, and elasticsearch indexing
- [ ] Migrate topic --> index hard-coded config into an indexing util that supports new indices
- [ ] Modify IndexingInput to utilize new topic --> index util 
- [ ] Fix old IndexingHelpers tests to reflect new classes
- [ ] Create Kibana dashboard for A&E
