### ISSUE TITLE
EPIC: Error reporting once a week based on login.gov identity

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#1159]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>{stakeholder role}</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>{feature}</td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>{use-case}</td>
  </tr>
</table>

### Description
{description}

### Assumptions
- {assumption 1}

### Tasks
- [ ] first task required to complete this epic
- [ ] second task required to complete this epic
- [ ] third task required to complete this epic

### References
<table>
  <tr>
    <td><b>Point of contact</b></td>
    <td>{name|email|room#|phone}</td>
  </tr>
  <tr>
    <td><b>Doc, Spreadsheet, etc.</b></td>
    <td>{link}</td>
  </tr>
</table>

**Comment by ajakz** [comment]
closing due to lack of details and movement; seems like it might be handled through #1240 though (at least a first pass to get us toward user-specific views for non-public information)
