### ISSUE TITLE
Support AWS Open Data Program for CSB

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#1169]
### Summary
<table>
  <tr>
    <td><b>As a CSB</b></td>
    <td>data manager</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
      meet AWS quarterly Open Data Program deadline of March 12th
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>be sure the data is available to public via an object store as soon as possible</td>
  </tr>
</table>

### Tasks
- [x] Modify CSB2Cloud crawler to upload all csb data to the ODP s3 bucket
- [x] Add a manifest style log of what has been uploaded and when to speed upload process in the future
  - [x] Design suggestion, create manifest files representing leaf directories to limit the file scanning of large manifests over time.
- [x] ODP set-up steps for AWS keyword registry

### Reference
- https://github.com/cedardevs/csbCrawler2Cloud

**Comment by kenhtanaka** [comment]
Started a fork to add new CSB related entries to [tags.yaml](https://github.com/awslabs/open-data-registry/compare/master...kenhtanaka:patch-1)

**Comment by dneufeldcu** [comment]
Met with Jenn to discuss timeline, decided to wait until next quarter for the public release to ensure data has been filtered.

**Comment by kenhtanaka** [comment]
For reference, using some of the links forwarded in this email:

> ---------- Forwarded message ---------
From: Flamig, Zac <zlf@amazon.com>
Date: Mon, Feb 10, 2020 at 1:40 PM
Subject: Officially welcoming Crowd Sourced Bathymetry to AWS Public Dataset Program
To: David Neufeld <david.neufeld@noaa.gov>
Cc: opendata <opendata@amazon.com>, Wimmer, Deb <wimmed@amazon.com>


David:
This email confirms that AWS will host the dataset, Crowd Sourced Bathymetry, to be shared as an AWS Public Dataset in partnership with the NOAA Big Data Project. We would like to start working with you immediately to prepare to launch the dataset. If we can't prepare in time, we can aim for one of our next launches, which happen every three months.
Here's what we need from you by March 12:
- A .yaml file that contains metadata describing your dataset at a high level. Instructions on how to create this file are at https://github.com/awslabs/open-data-registry/blob/master/README.md. At this point, don't worry about the “Resources” or “DataAtWork" sections of the file; we will fill that in when you get ready to launch. When this dataset is ready to go live, we ask that you make a Pull Request to https://github.com/awslabs/open-data-registry/issues to have the data included in https://registry.opendata.aws/.
- A document describing how the data is organized and how users can find the data they need. An example of what we're looking for is at https://cornelllabofornithology.github.io/ebirdst/articles/ebirdst-introduction.html. We ask that when the dataset is live, you host this documentation at a publicly available location.
- You will be receiving a separate email from Four Points Technology with the details for your AWS account. If you don’t receive this email within a week please let us know. When you're ready to create a public S3 bucket that will be used to share the data, please follow these steps:
0. Log in to your account.
1. Paste the following URL (note you can change the region 'us-east-1' to whichever region you would like to work in) into your browser and hit enter: https://console.aws.amazon.com/cloudformation/home?region=us-east-1#/stacks/new?stackName=pds-buckets&templateURL=http://awsopendata.s3.amazonaws.com/pds-cf-v5.yml. For geospatial datasets, unless there is a compelling reason to use a different region, we would recommend you use us-west-2.
2. Hit the ‘next’ button.
3. In the Parameters section, enter the name of the S3 bucket that you’d like to use for the dataset. Note that it may only contain lowercase letters, numbers, and ., -, or _ characters. Also note that S3 bucket names are unique, so you will get an error if you choose a name already in use by another bucket.
4. Hit ‘next’ two more times, and then hit “Create.”
5. In the top-right of the next window, you should see a “refresh” button that uses a circular arrow icon. Hit that a few times over the next minute or so to track progress.
6. Once it says the stack has been created, go to https://console.aws.amazon.com/s3/ and you should see the bucket there (along with some others). It will have the right permissions for public sharing and will have logging enabled.
Please let us know if you have any questions or issues as you go about this!

**Comment by kenhtanaka** [comment]
Update: Using pipenv to manage dependencies, but this isn't working as well as expected. Still working on it some.

A basic manifest is being written. The 'manifest-generation' branch of csbCrawler2Cloud contains this work.

**Comment by kenhtanaka** [comment]
An existing manifest file causes the program to stop. A pull request to merge 'manifest-generation' into master was made.

**Comment by kenhtanaka** [comment]
Prepared a new version of manifest file handling that breaks out manifest files into leaf nodes. Created a pull request for new changes.

**Comment by dneufeldcu** [comment]
Pull request merged, branch deleted.
