### ISSUE TITLE
Present UI options for granule 'filename' search

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#1174]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>software team</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       request feedback on multiple UI options
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>meet and exceed customer expectations</td>
  </tr>
</table>

### Tasks
- [ ] Screen snapshots of examples gmail, amazon, other?
- [ ] UI mockups of filter vs search bar
- [ ] Poll to receive feedback
