### ISSUE TITLE
Refactor the gradle build process across build environment

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#1175]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>devops guy</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       consistently build, version, and publish artifacts 
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>deploy onestop across operational environments</td>
  </tr>
</table>

###Tasks
- [ ] Detect CI environment is it gitlab or circleci
- [ ] Modify scripts based on CI environment
- [ ] Spike gitlab.com in aws marketplace
