### ISSUE TITLE
EPIC: Internal only search and access

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#1177]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>a satellite SME</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>search for data from satellites that may not be public</td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>preform my analysis or generated a new data product</td>
  </tr>
</table>

### Description
Currently OneStop has been focused on support public discovery and access needs.  Our recent work with STAR and the scdr-files client has exposed a more internal use case supporting STAR SMEs

### Tasks
- [ ] Review internal search and discover needs for scdr-files
- [ ] Come up with a design that meets the internal needs and is secure
- [ ] Generate supporting implementation stories
