### ISSUE TITLE
OER Video Portal CLASS filename support

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#1179]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>thin portal developer</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       access CLASS filenames
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>order files from CLASS</td>
  </tr>
</table>

### Tasks
- [ ] Review metadata xpaths is use
- [ ] Determine approach to storing filenames
- [ ] Ensure content is delivered in response
