### ISSUE TITLE
Make temporal search component 508 compliant

### ISSUE THREAD

**Issue by ajakz** [cedardevs/onestop#118]
- [x] Fields are editable
- [x] Calendar use is screen-reader accessible
- [ ] When date fields have default fields populated (like month & day set to Jan 1 when only given year), screen readers must receive alert that this change was performed

- [ ] error message should be specific enough for a screen reader to know which date is wrong and why, since the visual checkmark is not used by the screen reader
- [ ] clear button should have aria-label that specifies 'clear start and end date filters'
- [ ] apply button should have aria-label that specifies 'apply start and end date filters'

**Comment by mcquinne** [comment]
Should be done as part of epic #236

**Comment by zebdelk** [comment]
See #233 for more context.

Relative structure:
```
<h3>Temporal</h3>
<a>Show/Hide Temporal Filters</a>
<!-- The following elements are invisible when hidden -->
<h4>Standard-Format Date Range</h4>
<a>Show/Hide Standard-Format Date Range</a>
<form>
<input>MM/DD/YYYY</input> <CalendarButton> <a>clear</a>
<input>MM/DD/YYYY</input> <CalendarButton> <a>clear</a>
<button>Apply</button>
</form>
<h4>Paleo Date Range</h4>
<a>Show Paleo Date Range</a>
```

- [ ] Sections have appropriate headers
- [ ] Use links styled to look like buttons
- [ ] (TBD) Show/Hide links notify screen readers
- [ ] Link behavior is clear to screen reader users (links may be navigated out of context)
- [ ] Links names are not too long / over-descriptive
- [ ] Input / form labels are used correctly identify fields to screen readers
- [ ] Date format validation is clear to screen readers
- [ ] Validation errors are understood by screen readers
- [ ] The calendar button is skipped by screen readers, unless it is possible to navigate and interact
- [ ] "clear" buttons behavior make sense (which field is cleared, and if apply needs to be hit to take effect)
- [ ] (TBD) Filter Section behavior is consistent (apply filter on change vs apply button)

**Comment by mcquinne** [comment]
This issue is outdated. We will assess the current accessibility of the time filter and generate new issues if needed.
