### ISSUE TITLE
Python code integration with IM

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#1181]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>geospatial developer</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
      access geometries associated with granules to allow inserts into a spatial database
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>developer a web mapping client relying on the spatialDB</td>
  </tr>
</table>

### Background
Chuck has existing code that opens up files and gets geometry and attributes and puts it into Oracle Spatial

### Scope
- [x] Listen only client
- [x] Determine how to filter out messages for a first pass

### Tasks
- [x] Python client that listens to a kafka topic and receives metadata from IM
- [x] Python writes to stdout parsed metadata message

### Concerns
What is the execution framework for this? (Out of scope for this story)

**Comment by StrayCat1** [comment]
Python consumer - 
https://pypi.org/project/kafka-python/

**Comment by dneufeldcu** [comment]
Prints out filenames from granules topic.

**Comment by StrayCat1** [comment]
Alrighty, made the change to the example script so that it can consume from collections or granule topics. It prints the fileId for collections and filename for granules. The updated pyconsumer-pod.yml now passes a granule topic.

**Comment by StrayCat1** [comment]
https://github.com/cedardevs/onestop-clients
