### ISSUE TITLE
Add REST endpoints for saved search

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#1184]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>public user</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       save my search
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>quickly re-run the search as needed</td>
  </tr>
</table>

### Tasks by user
- [x] Try API first design
- [x] Endpoint to save searches 
- [x] Endpoint to edit search
- [x] Endpoint to delete search
- [x] Endpoint to get search
- [x] Endpoint to list searches

**Comment by Ghebrechristos** [comment]
- [x] Add integration test

**Comment by Ghebrechristos** [comment]
- [x] unit testing
