### ISSUE TITLE
Provide public access point for full metadata record

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#1188]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>metadata sme and OneStop API developer</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       the full XML metadata associated with a granule or collection
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>review the information when needed or develop custom landing pages based on the content</td>
  </tr>
</table>

### Tasks
- [ ] Provide a get full XML record endpoint in OneStop
- [ ] Confirm integration with Inventory manager to support feature
- [ ] Integrate with Onestop UI

**Comment by erinreeves** [comment]
* Typo in the method name retrieveRaxXml in MetadataRestController, Rax to Raw.

**Comment by erinreeves** [comment]
- In other similar methods we validate the id is valid with UUIDValidator.isValid(id) should we do that here?
- I guess it's okay we'll return null if the record isn't found? As it is we call result.rawXml on result=null when a record isn't found.... I'm adding a test to see what this comes to as but I'm guessing it isn't good.
- In metadataStore retrieveInput doesn't need source. Can we refactor that as part of this story? 
- Do we need 2 endpoints when the variance of source actually isn't used for the result?

**Comment by erinreeves** [comment]
Should the endpoint be 
/metadata/{type}/{id}/raw/xml
or
/metadata/{type}/{id}/xml

**Comment by YangusKhan** [comment]
>     * In other similar methods we validate the id is valid with UUIDValidator.isValid(id) should we do that here?
> 
>     * I guess it's okay we'll return null if the record isn't found? As it is we call result.rawXml on result=null when a record isn't found.... I'm adding a test to see what this comes to as but I'm guessing it isn't good.

I made these changes 👍 

>     * In metadataStore retrieveInput doesn't need source. Can we refactor that as part of this story?
> 
>     * Do we need 2 endpoints when the variance of source actually isn't used for the result?

I don't know what the background is with the `source` parameter for `retrieveInput`, but it seems like it's intended to be future functionality that hasn't been implemented yet? I gather it's there so that you can query metadata for different Kafka topics rather than just the default topic, but I'm not sure why that isn't implemented.

> Should the endpoint be
> /metadata/{type}/{id}/raw/xml
> or
> /metadata/{type}/{id}/xml

I only went with /raw/xml because of an offhand comment Evan made once, but I think I like /xml better, so it's changed.

**Comment by erinreeves** [comment]
404 if not found
groovy null safe ? which will return empty if input is null?

**Comment by erinreeves** [comment]
Add test for retrieved input null:
1 * mockMetadataStore.retrieveInput(testType, testSource, testId) >> null

**Comment by erinreeves** [comment]
Per Evan:
invalid uuid => 400
null record => 404
no xml => 404
else => 200 + xml body

**Comment by erinreeves** [comment]
Reviewed Restful api
