### ISSUE TITLE
Collection detail view accessibility

### ISSUE THREAD

**Issue by ajakz** [cedardevs/onestop#120]
Going away from modal to new page view for collection detail.
- [ ] New URL/query string
- [ ] Ensure 508 compliant

**Comment by zebdelk** [comment]
Our current proposed design:

Clicking on a result expands collection detail into the existing view.

508 considerations:
- [ ] alert user that the page has changed
- [ ] detail has a header at the appropriate level for overall document structure
- [ ] map images are ignored by screen reader, as there is nothing useful to describe there
- [ ] relative order of detail document elements makes sense
- [ ] links make sense both in and out of context (non-linear navigation)
- [ ] links are links and not buttons

**Comment by zebdelk** [comment]
Some additional things to keep in mind:
- [ ] links such as "show all" need a little more context for a screen reader to identify what is being shown (for example "show all themes" "show full title" would be clearer)
- [ ] there are aria roles for tabs that identify what tabs are available, with additional information such as "1 of 3", what the tab status is "open/close" and marking the tab content.
- [ ] we should make sure the tab order makes sense, and hits all the interactive elements correctly
- [ ] we should make sure all the matching files links are accessible, and have enough information (relative to what we have available to provide)
- [ ] we should make sure navigating through the list of granules doesn't trigger strange map actions that disrupt screen readers
- [ ] if there are any external links that pop up a warning about leaving the site, we should verify that it works for screen reader users

**Comment by zebdelk** [comment]
The boxes I checked off are now covered by other stories linked to the $440 collection tlc epic. I left some of the more generic ones here to double check that we didn't miss something such as the overall tab order.

**Comment by zebdelk** [comment]
Closing in favor of #440 and more focused #463.
