### ISSUE TITLE
Update indexer to support streaming flattened granules

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#1236]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>a system for metadata management and processing</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       index flattened granules and keep them up to date when their collection changes
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>provide an up to date search experience for users</td>
  </tr>
</table>

### Tasks
- [ ] Update the `indexer` to read from the new topic and index flattened granules
- [ ] Reprocess granules when a parent / collection changes
    - [ ] Implementation in ElasticSearch for 3.0 release (use existing painless script)

**Comment by dneufeldcu** [comment]
Working on associating a topic name with index name.
