### ISSUE TITLE
Provide NCEI dev access to OSIM in NESDIS Sandbox

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#1237]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>an NCEI developer</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
      access the latest features of OSIM
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>ensure my code is up to date</td>
  </tr>
</table>

### Scope
Initially limit to psi-registry api and Kibana. Need a data manager role r/w. Read access is public.
ngnix for 2 users CoMET and Metadata Content teams write access using basic auth an proxy to psi-registry and self-signed cert. Or as determined by implementor. 

### Considerations

How to expose the Registry API in terms of auth. Options:
- Basic auth via proxy, e.g. nginx
- Leverage Cognito + ALB integration
- Deploy CAS in the cloud k8s cluster
    - Avoid exposing CAS REST endpoint publicly to avoid DoS attacks, see: https://meet.google.com/linkredirect?authuser=0&dest=https%3A%2F%2Fapereo.github.io%2Fcas%2F4.2.x%2Fprotocol%2FREST-Protocol.html
- AWS API Gateway? OSIM API Gateway?

### Tasks
- [ ] Define endpoints to be exposed
- [ ] Determine access controls to be in place
- [ ] Implement public access using login.gov
    - Registry API
    - Kibana
- [ ] Review/add to documentation on Kubernetes cluster

**Comment by mcquinne** [comment]
Tasks thus far to update sandbox:
- [x] Touch base w/ AOI
- [x] Scale sandbox cluster back up
- [x] Turn kubectl node back up
- [x] Update kubectl and helm
- [ ] Update kubernetes control plane and workers 1.14 -> 1.17

**Comment by dneufeldcu** [comment]
Zeb and Erin remaining.

Dave needs to test kubectl

**Comment by dneufeldcu** [comment]
ssh keys in place
