### ISSUE TITLE
Create First-Pass Kibana Dashboards for Analysis & Error Information

### ISSUE THREAD

**Issue by ajakz** [cedardevs/onestop#1238]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>metadata manager</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       see analysis and error information in a dashboard
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>observe information about the metadata inventory to identify errors and potential improvements</td>
  </tr>
</table>

### Tasks
- [ ] Create kibana dashboard for viewing stats of all granules for defined collection(s)
- [ ] Save dashboard so that it is immediately available when OSIM is deployed
- Add fields to A&E indices:
  - [x] Add `stagedDate` to indices for time windows on ES dashboard
  - [x] Add `internalParentIdentifier` to granule index for better drill down capabilities
- Add content to Analysis in schemas, then update A&E mappings to include new content where applicable:
  - [x] Identifier block needs `isGranule`. Likely should replace `matchesIdentifiers`
    - [x] Update ValidationUtils in Indexer to use this field
  - [ ] ~Identifier block should note when a granule has more than one parentIdentifier or collection Relationship~ POSTPONED due to LOE vs value
    - Downstream granule flattening avoids these but the dashboard will help explain what's wrong
  - [ ] Utilize a descriptor enum for spatial bounding (i.e., `VALID`, `INVALID`, `NONE`)
    - [ ] Add `NONE` to temporal bounding descriptors & update downstream usage

### Future Kibana display of error information
- [ ] Improve Indexer error formatting/information to be more informative for display
  - [x] More granular titles
  - [x] Record-specific content in details to help solve problem (drill-down to details from titles)

### FUTURE separate story
  - [ ] Enhance spatial analysis to describe geoshape type (`LINE`, `POINT`, `BOX`, `SHAPE`, possibly?) There are different aggregate and analysis we can do on point-only data, for example.
  - [ ] Capture distinction between original bounding info vs the geojson we create. When we create multipolygons, if those fail to validate it may or may not be an error with the source data. (this is the case with the example in #1243 - the shape we generated is invalid)

**Comment by erinreeves** [comment]
branch strict-mappings-index-problems

**Comment by dneufeldcu** [comment]
Moving future tasks to new stories.

**Comment by erinreeves** [comment]
it looks like we can enable kibana's filebeat.yml to look in a directory, file, or url. "To load dashboards from a different location, you can configure one of the following options: setup.dashboards.directory, setup.dashboards.url, or setup.dashboards.file." (edited) 
12:58
https://www.elastic.co/guide/en/beats/filebeat/current/configuration-dashboards.html

"When dashboard loading is enabled, Filebeat uses the Kibana API to load the sample dashboards. Dashboard loading is only attempted when Filebeat starts up. If Kibana is not available at startup, Filebeat will stop with an error."

**Comment by dneufeldcu** [comment]
branch merged

**Comment by erinreeves** [comment]
Started story #1297

**Comment by zebdelk** [comment]
Added new stories under the epic #1281 to track tasks that haven't been addressed yet.
