### ISSUE TITLE
EPIC: Error Tracking For Devs and Metadata Owners

### ISSUE THREAD

**Issue by ajakz** [cedardevs/onestop#1240]
### Summary
For both metadata owners/managers/developers and the software developers/operators, it's vitally important to track errors throughout the OSIM environment so that the system can be used well at all times by all.

### Description
Users of the OSIM system need an intuitive and useful device to assess the quality of their metadata in the system. A dashboard that enables users to view the gathered analysis and error information on their metadata will empower them to resolve issues as well as keep tabs on what's in OSIM in general.

Likewise, we developers and the system operators of OSIM need to be able to assess the health of the data movement between OSIM components so that problems can be resolved quickly with minimal consequences. 

### Tasks
- [x] First pass Kibana A& E dashboard (#1238)
  - As devs, we will make our an attempt at something useful for users with (most) of what we currently have available with analysis and error content -- clearly missing fields or data structuring okay to address here but the point is to not spend too much time on our own before determining user needs
  - Meant to be available to help focus conversations in the next step
- [x] Iterate on Analysis & Errors Dashboard for the metadata content with metadata owners
  - Must include our users on designing the dashboards to be clear and useful
  - Put our test/iteration environment in the cloud for ease of access
  - Likely to involve changes to indexed information from Analysis
  - Likely to involve changes to how errors are described so as to be formatted well for aggregations
  - Support drilling down from collection --> granules (and possibly dataset --> collection) so users have aggregate view of collection status
- [x] System-wide error dashboard
  - Implement an error topic for system errors
  - Index system errors and pipe to an "operational awareness" type cluster
- [x] Spike on using Kafka Connect for writing to ES instead of homegrown bulk indexing in the Indexer (#1241)
  - If seems like better option, refactor Indexer to use KC
  - Should support writing to separate clusters (system errors not stored with metadata)
  - Should enable pre-fabricated mappings to be used when indices don't yet exist

#### Related Bugs
- [ ] Fix ES failing to index when cluster not supporting writes (could be handled by Kafka Connect above?) (#1242)
- [ ] Generating invalid multipolygon (#1243)
- [x] Wrong indexing error for invalid instant date (#1247)
- [x] DOS indexer (#1250)
- [x] Add missing fields to A&E mapping (#1251)
- [x] Ensure new A&E indices (#1248)

**Comment by erinreeves** [comment]
Merged 1360 pull request, branch 1268.
