### ISSUE TITLE
EPIC: Load Testing

### ISSUE THREAD

**Issue by mcquinne** [cedardevs/onestop#1258]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>NESDIS manager</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>test the catalog under heavy load</td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>rest assured that it will support all of NOAA's data</td>
  </tr>
</table>

### Description
The rest of the NCCF has undergone heavy load testing, but the Catalog has not. We need to verify that it will perform well enough to support cataloging all of NOAA's data. Specifically we need to test:
- Ingest/indexing throughput
- Search request throughput

### Assumptions
- Tests will be executed in the AWS stage environment
- All input metadata will be provided by the AOI team via SQS

### Goals
- Ingest throughput of 10k messages/minute

### Ingest Testing Tasks
- [ ] Upgrade the Python SQS consumer (#1252)
- [ ] Set up infrastructure to capture metrics (#1253)
- [ ] Define/tweak k8s resource claims (#1254)
- [ ] Plan specifics of test scaling (#1255)
- [ ]  Support multiple SQS queues (#1259)

### Search Testing Tasks
- [ ] Jmeter tests against search api
- [ ] Scdr-files test against search api

### Document Results
- [ ] Execute tests and capture data (#1256)
- [ ] Write up test results document (#1257)

### References
<table>
  <tr>
    <td><b>Testing plan</b></td>
    <td>https://docs.google.com/document/d/1-m8DSU9sQqNcFSosV5f5bJuvrng-LpLtGwjzgcnppXo/edit</td>
  </tr>
</table>
