### ISSUE TITLE
Lambda testing of search API

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#1262]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>devops engineer</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       test OneStop search responses under heavy load
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>be confident in it's scaleability and identify weak points in the current system</td>
  </tr>
</table>

### Tasks
- [ ] Develop 5 different query types ranging from simple to complex
- [ ] Deploy to aws and run queries in parallel at increasing exponential scale
- [ ] Record artifacts of results
