### ISSUE TITLE
Registry not supporting PATCH request operation type

### ISSUE THREAD

**Issue by ajakz** [cedardevs/onestop#1263]
## Summary
PATCH requests to the Registry should support adding and removing specific JSON content via the specified OperationType. Input sent directly via the Kafka topic can specify this but the setting of this field is not currently possible when input is received via an HTTP request.

## Tasks
- [x] Enable operation type specification via a query parameter on PATCH HTTP requests
- [x] Add setting operation type to Input records put on the Kafka topic
- [x] ~Replicate this on 2.x branch~ will deliver as part of 3.x
- [x] Update tests
