### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by bobalink** [cedardevs/onestop#127]
Microservices will use consistent logging implementation for use by Kibana (etc.)

- [x] Log search requests
- [x] Log collection hits
- [x] Log granule access clicks

**Comment by bobalink** [comment]
Didn't log collection hits because it really doesn't make sense because you should be able to recreate all the necessary info based on the search params. Same for Granule access clicks. you can tell when someone wanted the granules when the search params have the filter for collection of a specific ID.
