### ISSUE TITLE
Devops support fot OSIM 3.0

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#1279]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>development team</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       tag a release candidate
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>support security reviews and changes to ansible scripts, jenkins jobs</td>
  </tr>
</table>

### Tasks
- [ ] Security review
- [ ] Update build pipeline (new repo psi consolidated to onestop)
- [ ] Update ansible scripts
- [ ] Jar vs War (let's do it!)

**Comment by Ghebrechristos** [comment]
IT Contract transitions ... seems to slow down things

**Comment by dneufeldcu** [comment]
Met with Phil Cogbill on Thursday, Phil to update ansible script to match new artifact names.

**Comment by dneufeldcu** [comment]
Work with ITB to resolve JIRA #11463
