### ISSUE TITLE
Rename stream-manager to parsalyzer

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#1280]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>developer</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
      name things the way I want to align better with the function
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>feel good</td>
  </tr>
</table>

### Tasks
- [ ] Do it

**Comment by Ghebrechristos** [comment]
### changes and updates to
- [ ] root build, circleci config, gitlab and settlings files
- [ ] rename stream-manager module 
- [ ] packages to `org.cedar.onestop.parsalyzer `
- [ ] main and test classes names 
- [ ] skaffold file  
- [ ] helm and image definitions
- [ ] doc files
