### ISSUE TITLE
Add data format checker to CSB Crawler

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#1282]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>data distributor</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       distribute csv data in a consistent format
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>make life easier for our users</td>
  </tr>
</table>

### Tasks 
- [x] Add code that checks the header and first few lines of the CSV to verify which columns have LAT/LON values
  - [x] ISO 8601 time detection
  - [x] time parsing improvements
- [x] Ensure consistent CSV format is written out regardless of issues with incoming data
 
#### See also
CSV format notes in https://odp-noaa-nesdis-ncei-csb-docs.s3-us-west-2.amazonaws.com/readme.htm

**Comment by kenhtanaka** [comment]
Working on a branch "1282-Format-checker"

**Comment by kenhtanaka** [comment]
Pulling in changes from ingest-engines geometry-filter. xyz file parsing

**Comment by kenhtanaka** [comment]
Put in a change to pull uniqueID from the metadata and use that for the UUID column in the csv output

**Comment by kenhtanaka** [comment]
Working on code to parse the header of xyz files and verify the first data line matches the header format.

**Comment by kenhtanaka** [comment]
Adding a headerutils.py library to provide the header parsing and format checking.

**Comment by kenhtanaka** [comment]
Fixed two of the tests in CsbCrawlerTest.py by updating the test file locations to match data directory changes.

**Comment by kenhtanaka** [comment]
Added new work to parse ISO 8601 dates and test different inputs, on branch 1282-Format-checker.

**Comment by kenhtanaka** [comment]
Pushed some new code to handle datetime in various variations that are still considered ISO 8601

**Comment by kenhtanaka** [comment]
Added code to validate and parse ISO 8601 time formats. Added code in `headerutil.py` to index columns for 'lat', 'lon', 'depth' and 'time'. Added code to add Unique_id and file_uuid to output csv, which gets uploaded to AWS.

Made pull request to merge 1282-Format-checker branch to master.

**Comment by dneufeldcu** [comment]
Merged to master
