### ISSUE TITLE
Deploy initial version of CSB Crawler on-prem

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#1283]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>data distributor</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       upload new incoming files
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>be sure the object store in AWS ODP is up to date</td>
  </tr>
</table>

### Tasks
- [x] Deploy code to on-prem (acceptance)
  - [x] Package up code as a pip install
  - [x] Request Python 3.7+ install on acc-engines (fortuna.ngdc.noaa.gov)
- [x] Push data to new BDP bucket (instead of AWS ODP)

### AC
- [x] Python 3.7+ installed
- [x] Data from /nfs/csb_data/CSB

**Comment by kenhtanaka** [comment]
Requested python update to 3.7.7 or newer on fortuna.ngdc.noaa.gov. [ITSS-12622](https://jira.ncei.noaa.gov/servicedesk/customer/portal/1/ITSS-12622)

**Comment by dneufeldcu** [comment]
Can we install under a sudo account?

**Comment by kenhtanaka** [comment]
Installed python 3.8.3 in agiletc@acc-engines.ngdc.noaa.gov account. OPS didn't want to change the system wide python since that would break other things but said I could use miniconda/anaconda

**Comment by kenhtanaka** [comment]
Added setup.py and a MANIFEST.in to support packaging.

**Comment by kenhtanaka** [comment]
Added setup.py and a MANIFEST.in to support packaging.

**Comment by kenhtanaka** [comment]
Forked libgeospatialindex and updated the README.rst with current revision. Issued a pull reequest which was accepted.

**Comment by kenhtanaka** [comment]
Version 1.0.2 of csbCrawler2Cloud runs on acc-engines.

**Comment by dneufeldcu** [comment]
Determine whether to run one time to BDP until moved to production.

**Comment by kenhtanaka** [comment]
Added pull request #7 for on-prem changes

**Comment by dneufeldcu** [comment]
Merged pull request.

**Comment by kenhtanaka** [comment]
Tagged v1.0.2 and configured acc-engines (fortuna) on prem.
First pass of 900+ files running from /nfs/csb_data/CSB/ROSEP/2 running

**Comment by kenhtanaka** [comment]
Version 1.0.3, which handles MacGregor metadata, is now running on prem. Awaiting results...

**Comment by kenhtanaka** [comment]
222,915 files were uploaded to the noaa-bathymetry-pds bucket

**Comment by kenhtanaka** [comment]
Approximately 6100 files processed per hour, so 36 hours taken to upload 222,173 files (742 files uploaded in previous batch)
