### ISSUE TITLE
OneStop 3.0 Release Checklist (ORR)

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#1306]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>team</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       check off features and tasks associated with the 3.0 release
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>finalize the release with confidence</td>
  </tr>
</table>

### Tasks
- [x] Review registry support of indexer #1235 (Semere)
- [x] Indexer flattening #1236
- [x] Update on prem - build jobs
- [x] Upgrade ES to 7.x dependency for 3.0
- [x] Stepping through release checklist
-------------------------------------------

**Comment by Ghebrechristos** [comment]
beta release include
    - Stream flattening 
    - Error kibana dashboard 
Refactoring ES code twill go on next release

**Comment by dneufeldcu** [comment]
Internal reviews completed and beta 2 pushed to on-prem.
