### ISSUE TITLE
Migrate DataUtils to new data-common module

### ISSUE THREAD

**Issue by ajakz** [cedardevs/onestop#1307]
## Summary
In order to support #1268, some of the JSON/map/list utils (i.e., `DataUtils`) written in the `kafka-common` need to be accessible in non-Kafka contexts so that the ES mappings on the cluster and bundled with the application can be compared at startup by the Indexer.

## Tasks
- [x] Create new `data-common` module 
- [x] Migrate `DataUtils` content to new module
- [x] Code cleanup: migrate `FileUtils` from elastic-common to new module
- [x] Code cleanup: establish JSON API response objects for future use in APIs to enable us to move away from maps everywhere/struggle less using Java to build responses (#1308 future task for completing these and actually refactoring code to use them)
- [x] Code cleanup: break `DataUtils` into JSON, List, and Map classes
- [x] Code cleanup: make sure every method is fully tested

**Comment by ajakz** [comment]
This work is completed and on branch `array-iteration` but not ready for a PR as other issues are in progress on the same branch
