### ISSUE TITLE
Refactor ES read functionality to es-common module for use by Indexer

### ISSUE THREAD

**Issue by ajakz** [cedardevs/onestop#1309]
## Summary
In order to support #1268, read-only functionality for GETting mappings that is already defined in the Search API needs to be used by the Indexer app. To support maintainability and reduce duplicative code, the read-only functionality should be accessible from the `elastic-common` module.

## Tasks
- [x] Migrate direct read-only ES interactions from the Search API to `ElasticsearchReadService` in `elastic-common`
- [x] Refactor Search API's `ElasticsearchService` to rely on `ElasticsearchReadService` from `elastic-common`
- [x] Ensure ES client bean types match ES client dependencies
- [x] Convert groovy to java (`elastic-common` is a java package)
- [x] Remove support for ES v6
- [ ] Clean up the excess and dead code in `elastic-common`
- [x] Add old error handling back to response parsing (this was lost in the long-ago refactoring somehow and has meant we lost a large number of clean API responses for things like docs not found to the GlobalExceptionHandler)
- [x] Make sure DocumentationController isn't throwing NPE that result in no response returned (log nonexistent request)
- [x] "count" needs to be inside `attributes` in order to meet JSON API spec -- duplicate in correct location and add deprecation warning
