### ISSUE TITLE
SPIKE: Create a data loading pipeline that bypasses Kafka

### ISSUE THREAD

**Issue by Ghebrechristos** [cedardevs/onestop#1325]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>developer</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       load data with out using Kafka 
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>be happy by not running everything at once</td>
  </tr>
</table>

### Tasks
- [ ] gradle pass xml to schemas-parse, then pass results to indexer?

**Comment by Ghebrechristos** [comment]
Here is the doc: 
https://docs.google.com/document/d/1y37TDUOY8cIYZ4BrXKSIjAQ5QzyPI4u45DkPMkeUfhM/edit

**Comment by zebdelk** [comment]
Experimented a bit today and was able to create a standalone Java jar you can call from the command line that executes some of our transformation utility code. It's purely proof of concept at the moment.

Here's what's needed to turn it into something useful:

- [ ] identify each transformation step (parsing xml, analysis, convert for search index, convert for analysisAndError index)
- [ ] sort out exact use case (I am picturing something that has optional calls for each step, and maybe an additional one for xml through to json for ES. It will probably also need args for collection vs granule. Then calling it as a script such as `cat example.xml | java MainClass collection parse | java MainClass collection analyze | java MainClass collection search | curl post to ES search index`)
- [ ] update Main method to allow the params needed based on final decision for use case mentioned above
- [ ] refactor util methods to be easier to call without knowing more contextual details (in particular, the Indexer's TransformationUtils.reformatMessageFor* methods require being told about the expected ES fields, which makes it difficult to call from this context)

**Comment by zebdelk** [comment]
also need to solve:
- [ ] Jackson databind dependency - it's requiring a version from the schemas project to work, and the top level build is overwriting that and causing weird conflicts.

**Comment by zebdelk** [comment]
Currently refactoring transformation by generating POJOs from ES Mapping. Makes transformation util very easy to call, and seems to be working well.

**Comment by dneufeldcu** [comment]
Adding some error handling, code refactor wrap-up.
