### ISSUE TITLE
Leverage skaffold profiles

### ISSUE THREAD

**Issue by Ghebrechristos** [cedardevs/onestop#1326]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>developer</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       Leverage skaffold profiles more
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>ease my local development </td>
  </tr>
</table>

### Tasks
- [ ] Create more for more contexts
- [ ] Think about easier ways to trigger them
- [ ] Update quickstart docs with profile information

**Comment by zebdelk** [comment]
I had an idea of some profiles that might be helpful:

- psi (Kafka, and all the components centered on that - registry, stream manager, etc, but not ES or indexer)
- bridge (Kafka + ES + indexer, and anything else depending on both)
- os (ES, search, client, anything else related only on the ES side of the stack)

Not sure where the postgres DB and related stuff would go, os, or a separate profile.
