### ISSUE TITLE
EPIC: CSB Cloud Pilot Phase II

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#1349]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>pilot phase</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>demonstrate e2e CSB data landing in s3 and being discoverable in OneStop</td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>determine if OneStop supports non-satellite data sets</td>
  </tr>
</table>

### Description
Support CSB processing and discoverability in the OSIM cloud environment.

### Tasks
- [ ] CSB collection level metadata record available and loaded into OneStop
- [ ] Ensure all on-prem data is uploaded to s3 using consistent file format (#1282)
- [ ] Use the BDP s3 account (roll over from AWS ODP)
- [ ] Deploy CSBCrawler2Cloud on prem
- [ ] Add metadata capture from s3 events
- [ ] Add metadata capture from file (geospatial/temporal bounds)
