### ISSUE TITLE
Complete s3 metadata generation and capture by CSB/Data Lake

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#1358]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>NOAA data discovery system</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       generically capture file level metadata
    </td>
  </tr>
  <tr>
    <td><b>So that I can be</b></td>
    <td>ready for a capturing all data streams at NOAA</td>
  </tr>
</table>

### Tasks
- [ ] Add CSB metadata to loader script in onestop-test-data
- [ ] Finish lambda to post to registry-api
- [ ] Capture of URL based on public access point of s3 bucket

**Comment by dneufeldcu** [comment]
fileInformation block is done
relationships is done
fileLocations is in progress

**Comment by dneufeldcu** [comment]
first pass of granule content is complete

**Comment by dneufeldcu** [comment]
Just need to post the payload to registry.

**Comment by dneufeldcu** [comment]
Connecting the lambda to registry via VPC

**Comment by dneufeldcu** [comment]
Working! Next step documentations and check-in code to onestop clients repo.

**Comment by dneufeldcu** [comment]
Add s3 link
