### ISSUE TITLE
Capture uuid coming from psi-registry response

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#1361]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>a data catalog</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       refer my object by uuid in the object metadata
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>update my data catalog when an event happens to the object (like moving storage tier)</td>
  </tr>
</table>

### Tasks
- [ ] Check to see if object metadata contains an osim-uuid
- [ ] If so use the uuid in the post/publish to IM
- [ ] If not submit to registry and receive uuid and update object metadata

**Comment by dneufeldcu** [comment]
Add permissions to lambda execution role needed:
        {
            "Effect": "Allow",
            "Action": [
                "s3:GetObject",
                "s3:GetObjectTagging",
                "s3:PutObject",
                "s3:PutObjectTagging"
            ],
            "Resource": [
                "arn:aws:s3:::my-test-bucket/*"
            ]
        }

**Comment by dneufeldcu** [comment]
Note for CSB we will want to do this from the csbCrawler2Cloud code so that metadata uuid is assigned at object creation.

Next lambda should check for the metadata uuid coming out of the s3/sns/sqs event message

**Comment by dneufeldcu** [comment]
Mostly working task 2 on publishing from the kafka topic perspective, significant refactoring using configuration.

**Comment by dneufeldcu** [comment]
OBE - assume osim-uuid added when file lands in bucket see and pass osim-uuid to IM
