### ISSUE TITLE
Provide access to registry API from IM developer

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#1368]
### Summary

Allow an IM developer to post/patch to the registry API via a secure API call.

<table>
  <tr>
    <td><b>As an</b></td>
    <td>IM developer</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       post JSON to registry URL
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>test the latest features and see my results in OneStop</td>
  </tr>
</table>

### Tasks
- [ ] Firewall IPsec rule
- [x] BasicAuth in nginx admin user
- [x] Expose nginx via kubernetes ingress

**Comment by dneufeldcu** [comment]
mmm, might need to close this one. not good feedback from our partner.

**Comment by mcquinne** [comment]
Basic auth set up, credentials sent.
