### ISSUE TITLE
EPIC: Deployment and Access improvements for NESDIS Sandbox

### ISSUE THREAD

**Issue by mcquinne** [cedardevs/onestop#1376]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>OSIM Stakeholder</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>interact with an up-to-date OSIM deployment</td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>Develop software that interacts with OSIM with no impediments</td>
  </tr>
</table>

### Description
We have a number of stakeholders who are ready to interact with OSIM programmatically in various ways and who would benefit greatly by having access to an up-to-date version of OSIM to develop against.

### Assumptions
- Data in the sandbox account will continue to be treated as transient test data
- Users will need to access the system from on-prem networks
- Users will not be granted full AWS accounts

### Tasks
- [ ] Expose sandbox IM Registry API w/ basic security - #1368
- [ ] Improve flexibility of artifact publishing for osim itself and osim clients - #1375
- [ ] Automate artifact building and publishing
    - [ ] on prem (CI) - #1346
    - [ ] in the sandbox (CI)
- [ ] Automate artifact deployment in the sandbox (CD)
