### ISSUE TITLE
Prepare CIRES laptops for new hires

### ISSUE THREAD

**Issue by kenhtanaka** [cedardevs/onestop#1378]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>New Developer</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       Have a laptop ready to go
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>Work remotely and be productive right away</td>
  </tr>
</table>

## Tasks
- [x] Locate laptops
- [x] Verify all parts are present
- [x] Charge and check software installed
- [ ] Ready a short guidance document that provides
  - [ ] Contact info for CIRES IT assistance, 
  - [ ] Accounts and their purpose
  - [ ] Software available, IntelliJ Idea or PyCharm
- [ ] Arrange to transfer computer to new hires
  - [ ] Jeffrey
  - [ ] Vijay 
  - [ ] Brandon
