### ISSUE TITLE
EPIC: Archive to Glacier and Deep Glacier

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#1381]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>a data archive </td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>preserve data for the long-term at a reasonable cost</td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>feel confident in cloud based archival processes</td>
  </tr>
</table>

### Description
Move files landing in s3 to glacier based on temporal and parentId rules. Be able to restore the data to s3. Understand any AWS limits.

### Tasks
- [ ] Design session and documentation of discussion
- [ ] Know when a file goes into glacier
- [ ] Persist the identifier and location of the file
- [ ] Be able to retrieve the file from glacier

### References
Intelligent Storage - https://docs.google.com/document/d/1ga10PGamia4Y7-Hl4qWFNJbzr-QlGuPilBNv14y6SDg/edit#heading=h.bh4kpw8i4ph6

**Comment by StrayCat1** [comment]
relevant - https://docs.google.com/document/d/1nxYJD4tk6yfT3GdGNHCR8lH8lfYRO4C364ZrJ68NVVk/edit?usp=sharing

**Comment by dneufeldcu** [comment]
Currently we are using the 'glacier' resource type in boto3. This should be switched to s3 resource as glacier api will be deprecated.
