### ISSUE TITLE
Document steps for SME 

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#1387]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>subject matter expert</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
      publish my metadata to OSIM
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>make my data discoverable!</td>
  </tr>
</table>

### Tasks
  - [ ] Someone pushing data into registry (kafka in)
  - [ ] Someone pulling data from registry (kafka out)
  - [ ] Someone pushing data from registry (https)

### Assumptions
 - Focus on onestop-clients (python)
 - Docs are stored in onestop-clients repo
