### ISSUE TITLE
New developer spin up

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#1388]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>new OSIM developer</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       configure my development environment
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>be productive and contributing!</td>
  </tr>
</table>

### Tasks
- [x] Start with github documentation: https://github.com/cedardevs/onestop/blob/1093-doc_internal_dev/docs/developer/quickstart.md
- [x] Team ensure access to slack and calendar entries
- [x] Access to github
- [x] Help with archiving epic

### Confirm access with:
- [x] Jeff
- [x] Brandon
- [x] Vijay
