### ISSUE TITLE
Shared ramp up of OneStop project

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#1389]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>new developer</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       have a shared understanding of where the project is and where it is going
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>be productive and contributing</td>
  </tr>
</table>

### Tasks
- [x] Checkout the repo
- [x] Go through quickstart
- [x] Go over team norms - input
