### ISSUE TITLE
EPIC: One off archive

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#1392]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>a subject matter expert</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>upload a package for archive</td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>quickly ingest and archive data</td>
  </tr>
</table>

### Description
There are cases where we need to very rapidly upload data to support emergency events and then be able to archive those data for future reference. We want to create a very simple UI to upload that kind of data which can then integrate with the OSIM catalog and send data to Glacier for long term storage.

### Tasks
- [ ] create a simple web ui to upload a local file into s3
- [ ] enhance web ui to indicate which collection uploaded files should belong to
- [ ] support indicating whether the files of a collection should go to glacier or not (req. integration w/ onestop-clients python)

### References
<table>
  <tr>
    <td><b>SAB example data products site</b></td>
    <td>https://meet.google.com/linkredirect?authuser=0&dest=https%3A%2F%2Fwww.ospo.noaa.gov%2FProducts%2Focean%2Fmarinepollution%2F</td>
  </tr>
  <tr>
    <td><b>Catalog and Archive workflow document</b></td>
    <td>https://docs.google.com/document/d/1nxYJD4tk6yfT3GdGNHCR8lH8lfYRO4C364ZrJ68NVVk/edit</td>
  </tr>
</table>
