### ISSUE TITLE
Integrate single submission upload

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#1395]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>Catalog and Archive team member</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       to ensure that archive packages uploaded via single submission events are recorded in OSIM
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>be confident that I can discover and retrieve the files.</td>
  </tr>
</table>

### Tasks
- [ ] Set-up SNS
- [ ] Set-up SQS
- [ ] Deploy containerized sqs consumer / IM publisher keyed to bucket

**Comment by JeffreyHuynh1** [comment]
Made adjustments to SQSConsumer.receive messages to process the json payload
