### ISSUE TITLE
Project overviews and team norming

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#1398]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>team</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       share knowledge with new developers
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>ensure a productive experience</td>
  </tr>
</table>

### Tasks
Schedule a weekly meeting covering the technical stack as well as team norms

- [ ] Kafka and IM
- [ ] Elastic Search and OneStop
- [ ] Metadata
- [ ] UI and React/Redux
- [x] Team norms
