### ISSUE TITLE
Update upload UI to match wireframes

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#1405]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>file upload user</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       add a geographic location and begin date end date to associate with my file upload
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>enhance the discovery process.</td>
  </tr>
</table>

### Tasks
- [x] Drop down selector for collection association
- [x] Spatial coordinates entry
- [x] Date and time entry

### References
https://app.zenhub.com/files/62844166/b23602ae-b56a-4e0a-b7c2-a0b8ca0b82fd/download
