### ISSUE TITLE
Glacier redundancy

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#1407]
### Summary
<table>
  <tr>
    <td><b>As an</b></td>
    <td>archivist</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       ensure my data is sent to a long-term archive is a separate region (us-east-2)
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>that I have a backup copy in a different geography that supports COOP</td>
  </tr>
</table>

### Tasks
- [ ] Create vault
- [ ] Upgrade onestop-python-client to support sending data to glacier in a separate region
- [ ] Modify code to use s3 api over existing use of glacier
- [ ] Create utility class to restore from glacier for testing purposes

**Comment by JeffreyHuynh1** [comment]
Requires 3-5 hours for archival retrieval after initiating a job

**Comment by JeffreyHuynh1** [comment]
Created various scripts in archive_client_integration to test s3 to glacier upload, glacier restore to s3, etc. Might be good create different files for each script for better organization/management.
