### ISSUE TITLE
Create bucket for landing files with organizational structure

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#1409]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>integrated catalog system</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       organize datastreams by NOAA Line Office, collection and public private
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>leverage prefixes to add metadata to the granules</td>
  </tr>
</table>

### Tasks
- [x] Create noaa-nccf-dev bucket
- [x] Create top level directories
  - 
    - Public
      - NESDIS
        - CSB
        - GOES
        - H8
        - URMA
        - Review
        - SAB
      - NMFS
      - NOS
      - NWS
      - OMAO
      - OAR

    - Private
      - NESDIS
        - CSB
        - GOES
        - H8
        - URMA
        - Review
        - SAB
      - NMFS
      - NOS
      - NWS
      - OMAO
      - OAR

- [x] Automate ability to recreate bucket (amplify, boto3) IaC
- [x] Review s3 access policy (resource policy)
