### ISSUE TITLE
Project Open Data output

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#1412]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>catalog</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       to integrate with the full data.gov website
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>my data can be accessed by the public in the cross agency search portal</td>
  </tr>
</table>

### Tasks
- [ ] Design how to optimize generation along with sitemap
- [ ] Generation of data.json
- [ ] How to leverage exising JSON LD code and package for reuse
