### ISSUE TITLE
EPIC: Facet Filters TLC

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#142]
Goals:
- [x] Create a filter menu of which the facet filters is one section (#232)
- [x] Ensure the filter menu is accessible (#233)
- [x] Improve the layout of hierarchical facets (#17)
- [x] Ensure facet navigation and selection is accessible (#234)
- [x] Show selected facets across the top of the results (overlap with #36)
- [x] Improve facet storage and parsing (#369)
- [x] Facet / Filter selection changes should announce to screen reader (#370)
- [x] TreeView screen reader (entering mode) bug (#416)
- [x] missing expand/collapse attribute bug (#419)

See this working best practices document for what to expect in uploaded metadata: https://docs.google.com/document/d/1TFdn3e6eCuqkB49QX37gUJ_pSaGgKJLnB-oRkke9pK4/edit

**Comment by dneufeldcu** [comment]
- [ ] Improve hierarchy
- [ ] Display filter (overlap with #36)
- [ ] 508 compliance

**Comment by ajakz** [comment]
Wireframe:
![collection results view - keywords](https://user-images.githubusercontent.com/5514537/30941561-5089d764-a3a3-11e7-8887-792c7dcedd41.png)

**Comment by zebdelk** [comment]
"Filters"

**Comment by ajakz** [comment]
At last, it is done!
