### ISSUE TITLE
Create a resource policy for private buckets

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#1422]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>an archive client</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       control access to files in the bucket
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>ensure that my files are shared publicly</td>
  </tr>
</table>

### Tasks
- [ ] Investigate/learn the resource policy needed for a group policy tied to the cognito user pool
- [ ] Confirm the resource policy set-up statically
- [ ] Add the new resource policy to bucket set-up

**Comment by StrayCat1** [comment]
This Cognito user pool is associated with the cloud-archive-client- 
https://us-east-2.console.aws.amazon.com/cognito/users/?region=us-east

The policy - 
https://console.aws.amazon.com/iam/home?region=us-east-2#/policies/arn:aws:iam::798276211865:policy/noaa-nccf-dev-bucket-policy$serviceLevelSummary

The role that links the user pool to the policy - 
https://console.aws.amazon.com/iam/home?region=us-east-2#/roles/Cloud-archive-user-pool-role

The bucket I am developing against- 
https://s3.console.aws.amazon.com/s3/buckets/noaa-nccf-dev?region=us-east-2&tab=permissions

Example bucket policy that allows access to people with that role- 
```
{
    "Version": "2012-10-17",
    "Id": "Policy1605737714816",
    "Statement": [
        {
            "Sid": "Stmt1605737712384",
            "Effect": "Allow",
            "Principal": "*",
            "Action": "s3:GetObject",
            "Resource": "arn:aws:s3:::noaa-nccf-dev/public/*"
        },
        {
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::798276211865:role/Cloud-archive-user-pool-role"
            },
            "Action": "s3:GetObject",
            "Resource": "arn:aws:s3:::noaa-nccf-dev/private/*"
        }
    ]
}
```

**Comment by StrayCat1** [comment]
Controlling access with IAM policy...

**Comment by StrayCat1** [comment]
Useful tool for testing polices - 
https://policysim.aws.amazon.com/home/index.jsp

**Comment by StrayCat1** [comment]
There are a couple ways to do this- we can use s3 resource policies to Allow and Deny access, or we can Allow access with IAM policies associated with the Users themselves. 

In the example above, I have both. The s3 resource policy example above allows public access to /public/ and restricts /private/ to people with the cloud archive user role. 

Instead, we can user the s3 bucket policy to restrict access and then an IAM policy to approve access.

**Comment by StrayCat1** [comment]
For the reviewer, here is where I ended up- 
The bucket - https://s3.console.aws.amazon.com/s3/buckets/noaa-nccf-dev?region=us-east-2
The bucket policies - https://s3.console.aws.amazon.com/s3/buckets/noaa-nccf-dev?region=us-east-2&tab=permissions#

The cognito userpool that amplify created for our "devs" backend - https://us-east-2.console.aws.amazon.com/cognito/users/?region=us-east-2#/pool/us-east-2_vNVOBKF6K/details?_k=lz7mwt

The IAM Role that Amplify created for us (anyone who signs up/in to the cloud-archive-client will have this role applied)- https://console.aws.amazon.com/iam/home?region=us-east-2#/roles/amplify-cloudarchiveclient-devs-101344-authRole

And you can see that role has this policy (manually created and attached) that allows that role to PutObject to our bucket- 
https://console.aws.amazon.com/iam/home?region=us-east-2#/policies/arn:aws:iam::798276211865:policy/noaa-nccf-dev-bucket-policy$jsonEditor

**Comment by mcquinne** [comment]
This looks good for now, given the updates that'll take place with regard to programmatically defining these rules in #1429
