### ISSUE TITLE
EPIC: Trending Searches

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#143]
- [ ] Deploy OneStop to CU with logstash (Parent of #667)
- [ ] Logstash parses OneStop logs via a grok filter (Parent of #637)
- [ ] Search API queries logstash index (Parent of #668)
- [ ] Create and evaluate wireframes (Parent of #666)
- [ ]  Enhance logging on OneStop 2.0 (Parent of #618)
- [ ] Trending searches via Twitter (Parent of #672)

**Comment by dneufeldcu** [comment]
- [ ] Spatial tweaks

 - [ ] Evaluate google analytics data or OneStop  logging returned to us we explore index and use for trending results; consider use in search relevancy.

**Comment by ajakz** [comment]
Consider using decay functions in spatio-temporal requests to alter document scoring (see https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-function-score-query.html#function-decay for more info on implementation & scoring effects)

**Comment by dneufeldcu** [comment]
stale
