### ISSUE TITLE
Onestop search by object key

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#1430]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>developer</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       retrieve metadata by object key
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>reference other systems and their unique ids</td>
  </tr>
</table>

## Tasks
- [ ] Review whether existing fields like filename support this?
- [ ] If not, index s3 path (arn + object key)
- [ ] Allow search by object key 
- [ ] Return IM UUID in response payload
