### ISSUE TITLE
Reduce CIRES AWS deployment costs

### ISSUE THREAD

**Issue by mcquinne** [cedardevs/onestop#1434]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>CIRES supervisor</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       reduce AWS costs
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>pay for our AWS environment</td>
  </tr>
</table>

### Background
Our cloud environment costs spiked significantly in December and we want to prevent them from continuing to grow.

Our target budget is in the ballpark of **$500 per month**

It appears that the primary drivers of our cost thus far are the EC2 instances in our EKS cluster and potentially also our use of the NAT Gateway service.

### Tasks
- [ ] Migrate to the new graviton-based instance family, i.e. t4g instead of t3a
- [x] Assess pod resource requests and shrink them to fit into 3x .large instances instead of .xlarge
- [ ] Deploy a NAT Instance via EC2 instead of using the NAT Gateway service provided by Amazon
    - See data lake config for an example
    - Execute via the CF template instead of by hand
- [ ] (If necessary) Explore the cost breakdown further to identify other opportunities for savings

**Comment by mcquinne** [comment]
So far I've been able to shrink resource usage down to fit inside of 3 .large instances instead of .xlarge (which will essentially cut costs in half)

Relevant commits:
https://github.com/cedardevs/osim-deployment/commit/74d657b97a793e7cf8411d1f3dade36744220cbf
https://github.com/cedardevs/osim-deployment/commit/fcb5487cccccaf74eb1e99ab161e073fd17cee07
https://github.com/cedardevs/osim-deployment/commit/edf8fdd73bd80ba76429ac418fc4e01a53a41891
https://github.com/cedardevs/osim-deployment/commit/8a27506baefa9ba00c5907d7ea22389053566c5a
https://github.com/cedardevs/osim-deployment/commit/efa61095f5c6e30bc7d8da94e4c8fa0e924db705

**Comment by dneufeldcu** [comment]
Let's close and reassess after next months bill.

**Comment by dneufeldcu** [comment]
Confirmed costs are down and are estimated to fall below are monthly cost target.
