### ISSUE TITLE
Demo Data Wrangling

### ISSUE THREAD

**Issue by kenhtanaka** [cedardevs/onestop#1441]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>Developer</td>
  </tr>
  <tr>
    <td><b>I want</b></td>
    <td>
       A cloud based sample of 3 data sets, with 100 files each
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>have a ready to use sets of data to demonstrate data uploads to the cloud, which can then trigger metadata collection and storage into OneStop</td>
  </tr>
</table>

### Tasks
- [x] Create a staging bucket of test data for the `python-client`
  - [x] Create buckets in Cires first, then nesdis-sandbox
- [x] 100 GOES BDP files
- [x] 100 H8 BDP files
- [x] 100 CSB BDP files
- [x] Copy command to transfer files from staging to dev buckets

**Comment by kenhtanaka** [comment]
Created a bucket on cedar-devs called "bdp-demo-staging"

**Comment by kenhtanaka** [comment]
Need to create a cedar-devs bucket to match `noaa-nccf-dev` with the name of `noaa-nccf-staging` in the us-east-2 region.

Prefixes: 
- `public/NESDIS/CSB`
- `public/NESDIS/GOES`
- `public/NESDIS/H8`

Moved data from "bdp-demo-staging" to `noaa-nccf-staging` and then deleted "bdp-demo-staging".

**Comment by kenhtanaka** [comment]
100 goes16 ABI radiance CONUS files: 
https://s3.console.aws.amazon.com/s3/buckets/noaa-nccf-staging?prefix=public%2FNESDIS%2FGOES%2Fgoes16%2FABI-L1b-RadC%2F2020%2F001%2F00%2F&region=us-east-2&showversions=false#

100 CSB files:
https://s3.console.aws.amazon.com/s3/buckets/noaa-nccf-staging?region=us-east-2&prefix=public/NESDIS/CSB/csv/2019/12/&showversions=false

100 Himawari8 Full Disk files:
https://s3.console.aws.amazon.com/s3/buckets/noaa-nccf-staging?region=us-east-2&prefix=public/NESDIS/H8/AHI-L1b-FLDK/2020/01/01/0000/

**Comment by dneufeldcu** [comment]
Let's add an aws s3 cp from staging to nccf-dev to simulate the file loading.

**Comment by kenhtanaka** [comment]
Created `nesdis-nccf-staging` bucket in the nesdis-sandbox.

- private/
- public/
  - NWS/
    - URMA/
  - NESDIS/

**Comment by kenhtanaka** [comment]
nesdis-sandbox data files are now in place in bucket `nesdis-nccf-staging`

- CSB
  - https://s3.console.aws.amazon.com/s3/buckets/nesdis-nccf-staging?region=us-east-1&prefix=public/NESDIS/CSB/csv/2019/12/
- GOES-16
  - https://s3.console.aws.amazon.com/s3/buckets/nesdis-nccf-staging?region=us-east-1&prefix=public/NESDIS/GOES/goes16/ABI-L1b-RadC/2020/001/00/&showversions=false
- Himawari-8
  - https://s3.console.aws.amazon.com/s3/buckets/nesdis-nccf-staging?region=us-east-1&prefix=public/NESDIS/H8/AHI-L1b-FLDK/2020/01/01/0000/&showversions=false

**Comment by dneufeldcu** [comment]
Adding cp from staging to dev bucket

**Comment by kenhtanaka** [comment]
Staging scripts were checked in on
https://github.com/cedardevs/osim-deployment/tree/1441-demo-data-staging

**Comment by kenhtanaka** [comment]
URMA folder locations (public/NWS/URMA)
https://s3.console.aws.amazon.com/s3/buckets/nesdis-nccf-staging?region=us-east-1&prefix=public/NWS/URMA/&showversions=false

**Comment by kenhtanaka** [comment]
Pull request submitted for this story: https://github.com/cedardevs/osim-deployment/pull/3

**Comment by erinreeves** [comment]
noaa-nccf-staging for non-NCEI AWS

**Comment by erinreeves** [comment]
Looks great. Discussed with Ken, made a few suggestions, completed the pull request and deleted the branch.
