### ISSUE TITLE
Create a collection level metadata record for SAB

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#1444]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>Catalog and Archive IPT</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       demonstrate landing an SAB file associated with a collection
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>show support for single file upload.</td>
  </tr>
</table>

### Tasks
- [x] Create a ISO Collection level metadata record
- [x] Add it to the test metadata repo
- [x] Upload it to cedardevs
- [x] _Added manifest for SAB_

Edit xml:
- [x] on the data access tab remove anything with the curly braces {{ }}
- [x] for distribution formats list text/jpg/zip (technically shapefile(shp) inside these files)

### Reference
https://www.ospo.noaa.gov/Products/ocean/marinepollution/

**Comment by erinreeves** [comment]
A simpler version of this
https://data.noaa.gov/waf/templates/iso_u/xml/ncei_template-clean.xml
Where the data comes from 
https://www.ospo.noaa.gov/Products/ocean/marinepollution/

**Comment by erinreeves** [comment]
What fields are  required? Is it just OneStop required fields or is there metadata team required fields?

**Comment by erinreeves** [comment]
dataset description-https://www.ospo.noaa.gov/Products/ocean/marinepollution/

**Comment by erinreeves** [comment]
Look up on fed laptop:
ISO Explorer - https://geo-ide.noaa.gov/wiki/index.php?title=MI_Metadata
* dateStamp
