### ISSUE TITLE
EPIC: Load Metadata via Secured UI Endpoint

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#145]
## Context
Today metadata loading occurs from a script where a single user is able to run that script, and authentication is handled via basicAuth configured in Apache.

*Notes from sprint review discussion on 5/23/2018*
https://docs.google.com/document/d/1mwicO6JJXTvEFArDnbqaesHqHFOpHY9uxm97sshYhag/edit?usp=sharing

## User Stories

- [x] As a user, I will authenticate as a valid NOAA user against the ICAM identity provider. My user principle will be my email assertion returned from ICAM and will be tied to my appropriate roles for authorization.

- [x] As a user who has the proper authorization to load metadata, my granting role should be bootstrapped into api-metadata as an in-memory database.

- [x] As an authenticated and authorized user (e.g. - METADATA_CURATOR role), I want to be allowed access to specific metadata API endpoints (loading new metadata) from any location.

- [x] As a developer, I want to have access to documenation on HOW-TO integrate our custom SAML filter into a Spring Security context.

- [x] As a 'logged-in' user (via ICAM with the role of METADATA_CURATOR), I want to easily navigate to a metadata loading interface.

- [x] As an unauthorized user, I should NOT be able to access metadata loading actions, endpoints, and information.

## Reference
https://docs.google.com/document/d/10Bh1VVIZzzebhG5njhRvP5vhNkTMG0kQnT0AcNW3oLM/edit

## MVP
A single user is able to authenticate with ICAM and be authorized to update the metadata using email/pwd. In general, assume email is the main source of identification of the user.

## Acceptance Criteria

- [x] SAML or OpenId authentication works (Parent of #612)
- [x] login.gov authentication
- [x] ICAM authentication ( Parent of #597)
- [x] EA Roundtable discussion (parent of #578 )
- [x] Authorization should be provided by OneStop (Parent of #600 )
- [x] ~~SSO deployment ( Parent of #606 )~~
- [x] basic webform to secure (Parent of #631)
- [x] #540 learning spike

**Comment by dneufeldcu** [comment]
- [ ] Prototype a login capability using external OAuth2 provider like google
