### ISSUE TITLE
Clean-up onestop-test-data repo

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#1454]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>devops engineer</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       to have an up to date shell script that loads metadata into IM
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>not be confused by older deprecated references.</td>
  </tr>
</table>

### Tasks
- [x] Remove references to onestop API (Inventory Manager API or PSI really) in readme
- [x] Remove references to onestop API (Inventory Manager API or PSI really) in shell scripts
- [x] If a collection uuid is present make sure we use it during post to IM (manifest.sh)
- [x] Ensure shell script uses new api endpoint 
 -- https://cedardevs.org/onestop/api/registry/metadata/collection

**Comment by StrayCat1** [comment]
To clarify, we need to deprecate the feature that allows us to POST to api-metadata, which doesnt exist anymore. 
Example- 
```
./upload.sh IM GOES/ localhost/onestop/api/registry
```
becomes 
```
./upload.sh IM localhost/onestop/api/registry
```

Also, the UUID's in the manifest are respected. If you need to add a new dataset, run the ./manifest.sh on the new directory. 

Also, the script will use whatever base url you give it, so to post to cedardevs, use- 
```
./upload.sh IM GOES/ https://cedardevs.org/onestop/api/registry
```

**Comment by erinreeves** [comment]
For testing the EdgeCases was a good one that has collections and granules:
./upload.sh IM EdgeCases localhost/onestop/api/registry ju:ju

If you cannot get OS running locally up on bastion you can test it:
./upload.sh IM EdgeCases http://internal-abcd2708f254f4905a30bf735e5b5d27-1737336414.us-east-1.elb.amazonaws.com

**Comment by erinreeves** [comment]
https://github.com/cedardevs/onestop-test-data/pull/10

**Comment by dneufeldcu** [comment]
Looks good, minor updates to upload.sh and delete.sh
