### ISSUE TITLE
EPIC Data Visualization

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#146]

**Comment by dneufeldcu** [comment]
- [ ] Develop prototype of search by data values
- [ ] Harvest elevation values from OneStop DEM datasets
- [ ] UI slider for elevation range

**Comment by dneufeldcu** [comment]
wontfix
