### ISSUE TITLE
Implement produce/consume methods on onestop-python-clients

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#1460]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>an SME developer</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       consume and produce metadata off of Kafka topics
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>better integrate my domain specific code into metadata publishing workflows</td>
  </tr>
</table>

### Tasks
- [ ] Initial avro python classes to simplify message deser
- [ ] Deserialize an incoming granule metadata message for CSB
- [ ] Use the deserialized message to load spatial database
