### ISSUE TITLE
Create GEFS xml collection

### ISSUE THREAD

**Issue by erinreeves** [cedardevs/onestop#1462]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>new onetop stakeholder from National Weather Service</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       demonstrate landing a GEFS file associated with a collection
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>show support for single file upload.</td>
  </tr>
</table>

### Tasks
- [x] Copy all ISO Collection level metadata record for GEFS from data.noaa.gov, from Paul via email
- [x] Add it to the test metadata repo
- [x] Review and verify correct
- [x] Upload it to cedardevs

Notes:
Add browse graphic https://www.ncdc.noaa.gov/sites/default/files/GEFS%20-%20gens-a_2_20120712_0000_024_1013hPa-small.gif

### Reference
https://registry.opendata.aws/noaa-gefs/
https://data.noaa.gov/onestop/collections?q=gefs

https://www.uuidgenerator.net/version4

**Comment by erinreeves** [comment]
Remove reference to grid resolution duetouncertainty.

**Comment by erinreeves** [comment]
let's go ahead and delete [1 deg.] and update the manifest

**Comment by erinreeves** [comment]
dave:
it's fine
I have reviewed it multiple times
