### ISSUE TITLE
Sitemap Integration

### ISSUE THREAD

**Issue by uniyalVJ** [cedardevs/onestop#1464]
Integrating story "Generate sitemap as a file#726" into OneStop.
https://app.zenhub.com/workspaces/onestop-5caf5b03e94905314d5883a8/issues/cedardevs/onestop/726

### Description
Integrating the sitemap generator into OneStop to increase discovery of our data on search engines.
Acceptance Criteria: Sitemap generator runs in a container in AWS cedardevs environment

Node script run daily
Host at cedardevs.org/onestop/sitemapIndex.xml
JSON in same area as XML

Hosting:
Javascript Node web server Express
One pod to generate/serve files

### Tasks
- [x] Design discussion
- [x] Build.gradle file configure JIB (Gradle Extension/Library) to build docker image to run node js app
       -Client build gradle good example
- [x] Add JIB (Should build image)
- [x] Write sitemap XML files to root directory where Nginx is hosting
     - Curling at this point should generate sitemap files
- [x] Create a chart
- [x] Containerize code so that it runs in the cluster
- [x] CRON Job/Dockerfile
- [x] Host XML/JSON files at top level for GoogleBot to retrieve 
- [x] Sitemap Microservice
