### ISSUE TITLE
EPIC: Hardening

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#1465]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>team</td>
  </tr>
  <tr>
    <td><b>We want to be able to</b></td>
    <td>ensure high-quality code, test coverage, documenation</td>
  </tr>
  <tr>
    <td><b>So that We can</b></td>
    <td>be confident in our solutions</td>
  </tr>
</table>

### Description
{description}

### Assumptions
- {assumption 1}

### Tasks
- [ ] Improve demo/integration test script with clean-up
- [ ] Resolve glacier storage when running from VPC
- [ ] Granule metadata follow-up with John R.
- [ ] onestop-python-client comments for API docs pyDoc?
