### ISSUE TITLE
Create URMA XML collection

### ISSUE THREAD

**Issue by erinreeves** [cedardevs/onestop#1466]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>new onetop stakeholder from National Weather Service</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       demonstrate landing a GEFS file associated with a collection
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>show support for single file upload.</td>
  </tr>
</table>

### Tasks
- [x] Create an URMA collection XML
- [x] Add it to the test metadata repo
- [x] Review and verify correct
- [x] Upload it to cedardevs

Notes:
Add browse graphic 

### Reference
https://www.nco.ncep.noaa.gov/pmb/products/rtma/#URMA

https://www.uuidgenerator.net/version4

**Comment by erinreeves** [comment]
![Screen Shot 2021-02-15 at 7.27.11 AM.png](https://images.zenhubusercontent.com/5caf6655760a2951f5e7aa02/38459b7a-ff82-4d55-881f-449de5be76e6)

![Screen Shot 2021-02-15 at 7.27.25 AM.png](https://images.zenhubusercontent.com/5caf6655760a2951f5e7aa02/4e275ae6-ae82-4f9f-9655-366be1d42675)

![Screen Shot 2021-02-15 at 7.27.34 AM.png](https://images.zenhubusercontent.com/5caf6655760a2951f5e7aa02/1926c86b-f3ce-4711-870e-c1e3abd09000)

**Comment by erinreeves** [comment]
Dave:
 let's push to master for GEFS and URMA

**Comment by erinreeves** [comment]
Dave:
 let's push to master for GEFS and URMA
