### ISSUE TITLE
Cross Region Replication

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#1468]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>an archive manager</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
        ensure my data is backed up to glacier in a second region
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>be confident in the archive</td>
  </tr>
</table>

### Tasks
- [x] Set-up cross region replication to from s3 region 1 to glacier region 2
- [x] Capture events on second 'bucket' on second region 2 location with storage class glacier
- [x] Add URMA prefix

### Notes
Glacier data does not need to extractable

**Comment by kenhtanaka** [comment]
Demo'd to stakeholders
