### ISSUE TITLE
Build basic auth into registry

### ISSUE THREAD

**Issue by mcquinne** [cedardevs/onestop#1471]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>data manager</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       access create/update/delete endpoints in the registry using basic auth
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>use the same API endpoints consistently to manage data</td>
  </tr>
</table>

### Description
We need to expose some registry endpoints to the public, e.g. for retrieving raw xml metadata, but we can't fully expose the registry api through the gateway unless the potentially destructive endpoints are configured to require authentication. We can get started by simply installing Spring security using embedded basic auth and evolving into more advanced authN/Z approaches down the road.

### Tasks
- [ ] Install Spring Security into the registry
    - Configured to use basic authentication for now
- [ ] Add `@Secured` annotations to potentially destructive endpoints
- [ ] Use authentication hooks to restrict access to records marked as private
- [ ] **Decision**: Remove previous CAS integration via pac4j implementation?

**Comment by mcquinne** [comment]
After research and discussion we've decided our path is to retain and leverage the integration with CAS in our cloud deployment. We have a basic helm chart to deploy it locally already, which we will leverage in order to deploy it to the CIRES cloud.
