### ISSUE TITLE
Ensure API definitions are published on SwaggerHub

### ISSUE THREAD

**Issue by mcquinne** [cedardevs/onestop#1487]
### Summary
<table>
  <tr>
    <td><b>As an</b></td>
    <td>API consumer</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       discover the OneStop API documentation
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>know how to use the APIs</td>
  </tr>
</table>

### Tasks
- [x] Search API's `openapi.yaml` is published to swaggerhub, automatically if possible.
- [x] Registry API's `openapi.yaml` is published to swaggerhub, automatically if possible.
- [x] Add to the [OneStop Release Checklist doc](https://cedardevs.github.io/onestop/developer/testing/onestop-release-checklist) about adjusting the openapi version number (unsure what we've decided for incrementing) as well as what steps need to be done, if any, manually by the deployer to generate the docs.
- [x] Adjust docs to point to new swaggerhub urls for search and registry docs

**Comment by erinreeves** [comment]
https://support.smartbear.com/swaggerhub/docs/apis/importing-api.html

**Comment by erinreeves** [comment]
Per Evan:
IIRC the registry build uses this base openapi definition and then supplements it with json schemas that are derived from our avro schemas: https://github.com/cedardevs/onestop/blob/master/registry/src/main/resources/openapi_base.yaml
registry/src/main/resources/openapi_base.yaml

if we use gradle to do this then hopefully we can also leverage Elliott’s versioning/publishing code, so we can publish with the 3.0.0-SNAPSHOT version for every master build, then with a concrete version when it’s building a tag (edited)

**Comment by erinreeves** [comment]
Swagger naming convention:
OneStop-Registry
OneStop-Search

**Comment by erinreeves** [comment]
https://app.swaggerhub.com/apis/cedarbot/OneStop/search/3.0.0-RC1

**Comment by erinreeves** [comment]
*sigh* well "API name must start and end with a alphanumerical and can only contain alphanumerical, period, hyphen and underscore"
https://app.swaggerhub.com/apis/cedarbot/OneStop-Registry/3.0.0-RC1

**Comment by erinreeves** [comment]
Should the schemas that Registry openapi is referencing/using be 0.7.1? It's currently 0.7.0
https://jitpack.io/p/cedardevs/schemas

Looks like the variable ONESTOP_SCHEMAS is used by Indexer, Registry, parsalyzer, and test-common.

https://github.com/cedardevs/onestop/blob/master/buildSrc/src/main/kotlin/utils.kt#L44

https://github.com/cedardevs/onestop/blob/master/registry/build.gradle#L40

**Comment by erinreeves** [comment]
Exported and re-imported old search api docs as new url format of:
https://app.swaggerhub.com/apis/cedarbot/OneStop-Search/2.4.0
