### ISSUE TITLE
Docker implementation support for ES 5.x (coordinated with CCOG)

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#161]

**Comment by zebdelk** [comment]
- [ ] publish docker images when creating artifacts
 - [ ] running docker-compose up locally uses ES 5.x
 - [ ] deployment project has docker-compose file appropriate to the cu-server system
