### ISSUE TITLE
Search API To ES 5.x

### ISSUE THREAD

**Issue by ajakz** [cedardevs/onestop#169]
Given the substantial changes in the ES Java client from 2.x to 5.x, we've decided to rewrite our code to use the new REST client. May as well get the ball rolling and write the rewrite as a microservice. 

AC:
- [x] Search functionality is kept the same (same request, same response formats)
- [x] Tests verify same capabilities as old tests
- [x] Update gradle build script (implemented by #191)

**Comment by ajakz** [comment]
Noting here -- I've intentionally left the UI Config out of the Search Controller, as it's a prime example of a responsibility that should be owned by a configuration manager of sorts.

**Comment by ajakz** [comment]
Just kidding, Zeb's going to put the UI Config back in place

**Comment by zebdelk** [comment]
- [ ] UI config as part of api
