### ISSUE TITLE
Metadata API & ETL to ES 5.x

### ISSUE THREAD

**Issue by ajakz** [cedardevs/onestop#172]
Given the substantial changes in the ES Java client from 2.x to 5.x, we've decided to rewrite our code to use the new REST client. May as well get the ball rolling and write the rewrite as a microservice. 

AC:
Metadata Management:
- [x] Metadata ingest functionality is kept the same (same request format, except for changes due to #194)
- [x] Add recursive flag to DELETE operations (defaults to true; removes a collection's granules from Staging)
- [x] Remove XML from staging collections
- [x] Tests same or better

ETL:
- [x] Make sure synthesized granules are deleted when true granules ingested
- [x] Use Reindex API & Painless scripting to implement ETL instead of bulk operations
- [x] ~Disable index refresh at start of ETL operations, enable it at end to optimize for heavy indexing operations (method already defined in ElasticsearchService)~
- [x] After load testing we've decided to simply use the default `refresh_interval` instead
- [x] Tests same or better

**Comment by mcquinne** [comment]
Additional follow-up tasks:

- [ ] Address "inline --> source" deprecation message from elasticsearch
- [ ] Delete obsolete `api` module
- [ ] Add a full output assertion to the e2e tests
- [ ] Simplify `index-configuration` project's resource sharing
- [ ] Check gradle deprecation warnings (e.g. `api-metadata:integrationTest` task)

**Comment by mcquinne** [comment]
Gradle deprecation warnings seem to be cause by Intillij being confused. It says we should be using `setDestination(File)` instead of `setDestination(Object)`, but we are in fact calling it with a file object like `reports.html.destination = file("${buildDir}/reports/integrationTests")`

Gonna check that one off.

**Comment by zebdelk** [comment]
For deleting api module: confirmed that all endpoints in that module have been implemented in the new modules. The only change is the endpoints which use doi as an identifier, which was a deliberate change to the api to support our new way of dealing with internal ids vs fileIdentifier and/or doi.

**Comment by mcquinne** [comment]
The change from `inline` to `script` in the elasticsearch API was only [introduced in 5.6](https://www.elastic.co/guide/en/elasticsearch/reference/current/release-notes-5.6.0.html). Since we don't know exactly which version of 5.x they're going to install, and it's only a warning about a future deprecation in 6.x, it's safer to leave our API calls as they are, i.e. using `inline`.

**Comment by zebdelk** [comment]
e2e test changes can be seen at https://github.com/cedardevs/onestop/pull/249

**Comment by mcquinne** [comment]
Everything's been followed up on!
