### ISSUE TITLE
Remove ability to change how DSMM affects search rankings

### ISSUE THREAD

**Issue by ajakz** [cedardevs/onestop#176]
For the function score config ability, we allow customization of the 'modifier' and 'factor' fields -- essentially how the dsmmAverage should affect the scores of the results. However, if we allow config to change the function, we should also allow changing the 'missing' value since assigning it to 0 may be wrong if not configured with log1p. Another concern is that scoring could be set in a completely erroneous way if not all fields are provided. Should we check for this since we are setting a default config so that the default can't be "broken"? 

See SearchConfig class, assembleScoringContext() in SearchRequestParserService, and [this ES guide](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-function-score-query.html#function-field-value-factor).

AC:
- [ ] DSMM search config allows for changing 'missing' field
- [ ] Foolproof the default setup
- [ ] SearchRequestParserServiceTest "Test only queryText with dsmm boosting configured"() is updated
- [ ] SearchConfigSpec tests updated

**Comment by ajakz** [comment]
Maybe we just leave the defaults as is and remove the option to change it?
