### ISSUE TITLE
Cleanup gradle builds

### ISSUE THREAD

**Issue by zebdelk** [cedardevs/onestop#191]
Modules: api-search, api-metadata

- [x] docker-compose up actually uses latest code changes for development
- [x] cleanup start task (remove?)
- [x] common dependency for index settings

AC: If needed document what is working / not working in docker-compose up.  Then stop.

**Comment by zebdelk** [comment]
The dockerComposeUp gradle task does include code changes in a developer's working directory. The biggest downside is that it is slow since it forces a rebuild of all components every time.

**Comment by mcquinne** [comment]
Tweaks:

- Switch to `dockerComposeStart` and `dockerComposeStop` so the containers stay around by default
- Maintain `dockerComposeDown` and call it on a `gradle clean`
- Add tasks to start and stop compose "infrastructure" (elasticsearch) and use call start before `bootRun` tasks
- Install the [spring boot devtools](https://docs.spring.io/spring-boot/docs/current/reference/html/using-boot-devtools.html) in our boot apps

That ought to do it!
