### ISSUE TITLE
Use elasticsearch auto-generated ids

### ISSUE THREAD

**Issue by ajakz** [cedardevs/onestop#194]
Time to stop relying on fileIdentifiers and parentIdentifiers for making metadata searchable & plan for a better future...

Metadata CRUD:
- [x] GET metadata requests now have request params `fileIdentifier` and/or `doi`, or path variable with ES `_id` value
- [x] DELETE metadata request options same as GET. 
- [x] POST requests need to search for existing records first; perform a PUT to ES for update, POST to ES for create
- [x] POST requests return `_id` in addition to currently returned info.
- [x] No longer any "bad" identifier values

ETL:
- [x] Granule mapping has new field: `internalParentId`. This maps to the `_id` of the corresponding collection.

Search:
- [x] Searches and aggregations using `parentIdentifier` now reference `internalParentId` instead

Client:
- [x] References to `parentIdentifier` need to be changed to `internalParentId`

**Comment by mcquinne** [comment]
This has been well tested and is working correctly.

**Comment by zebdelk** [comment]
Review:  we've all seen that code, we know it's working on CU, we've got integration tests around it. [x]
