### ISSUE TITLE
Geoportal OneStop Integration

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#196]
- [x] Install geoportal catalog 
- [x] Configure geoportal JavaScript configuration file to point to OneStop index
- [x] Test CSW query
AC: TimeBox 2-3 days 1 dev

**Comment by dneufeldcu** [comment]
Version 2.5.1.5 is available here:
https://esri.box.com/s/by039ukp9jkgrdaqb6tf6foeh8osyopr

**Comment by ajakz** [comment]
Installation and configuration information is [here](https://github.com/Esri/geoportal-server-catalog/wiki/Installing-Geoportal-Server-2.5.0) and [here](https://github.com/Esri/geoportal-server-catalog/wiki/Elasticsearch-configuration), respectively. I can't figure out what modifying the linked to Config.js and building from source is supposed to accomplish -- on modifying the [Tomcat8]/webapps/geoportal/WEB-INF/classes/config/app-context.xml file to point to our index, the URL used by the Geoportal UI correctly resolved to ` http://localhost:8080/geoportal/elastic/search/item/_search` without needing to touch that Javascript file. 

However, the problem with this config is that while we are capable of changing the index that Geoportal talks with, there's nowhere to modify the type, i.e, "item" which is "collection" and "granule" for our index. Anyway, I went ahead and called it "item" instead of "collection" just for testing and Geoportal still cannot communicate with our index. The error in the initial search request is:

``` {"error":{"root_cause":[{"type":"query_shard_exception","reason":"No mapping found for [title.sort] in order to sort on","index_uuid":"oyeKSjzLTGKbxS9sXDtoXA","index":"search_v2"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"search_v2","node":"Pni47bLrRU2Pum51MqyC6g","reason":{"type":"query_shard_exception","reason":"No mapping found for [title.sort] in order to sort on","index_uuid":"oyeKSjzLTGKbxS9sXDtoXA","index":"search_v2"}}]},"status":400}```

If we want to connect our index to the ones Geoportal expects, we will need from ESRI a config file that allows us to specify the fields in our index to correlate to the fields they expect in their querying. This is not a simple plug-and-play right now; it turns out we have diverged quite a bit (and will continue to do so) in our index mapping. 

Can they create some sort of configuration that allows us to map the index field to field?

**Comment by dneufeldcu** [comment]
Write email describing how the configuration needs to change for ESRI.

**Comment by umacgillivray** [comment]
@dneufeldcu @ajakz 
You won't need to deploy and configure the full Geoportal catalog. There is a separate war file that can support CSW3 and Opensearch for OneStop.

https://github.com/Esri/geoportal-server-catalog/releases/download/v2.5.0/geoportal-search-1.0.0.zip

The zip contains geoportal-search.war, that's the one that will need to be deployed.

Once deployed, edit:

[tomcat]/webapps/geoportal-search/WEB-INF/classes/gs/config/Config.js

Change the defaultTarget to:

	defaultTarget: {writable: true, value: "onestop"},

In the targets section, add one for OneStop:

        "onestop": gs.Object.create(gs.target.elastic.CustomElasticTarget).mixin({
          "searchUrl": "http://yourhost:9200/yourindex/youritemtype/_search"
        }),

You can remove or comment out the other targets if you'd like.

There are some usage examples within the zip, see readme.txt.

Once you have it running we will need to map some of your fields to support CSW queryables and responses. I can help with that.

**Comment by mcquinne** [comment]
@umacgillivray 
I think what you and @ajakz are describing are just alternate ways to configure the connection to elasticsearch, right?

She used the
`[tomcat]/webapps/geoportal/WEB-INF/classes/config/app-context.xml`
file as described [in your wiki](https://github.com/Esri/geoportal-server-catalog/wiki/Elasticsearch-configuration), and you're suggesting using the
`[tomcat]/webapps/geoportal-search/WEB-INF/classes/gs/config/Config.js`
file instead, but it looks like they both have the effect of being able to customize the elasticsearch location.

I think what we need help with at this point is exactly what you alluded to in your last sentence: How do we map the CSW queryable fields to search against our fields in our index.

**Comment by umacgillivray** [comment]
@mcquinne @ajakz 
There are two web applications. 

geoportal.war is a full catalog with it's own index, it can use the same Elasticsearch as OneStop but it will not integrate content.

geoportal-search.war is a separate web app, it does not have it's own catalog or index. It can provide CSW3 and OpenSearch entry-points to your OneStop index. This is the one to deploy and configure using:
[tomcat]/webapps/geoportal-search/WEB-INF/classes/gs/config/Config.js

**Comment by ajakz** [comment]
@umacgillivray
Okay, seems there was a misunderstanding on our end about there being two different apps. We were thinking this would be addressing two issues for us at once: being able to use the Geoportal UI with our index AND have CSW3 and OpenSearch entry-points into our index. Sounds like the former won't happen?

Anyway, the configuration of geoportal-search seems to have connected to our index and returned some results. 

What can we do now to map our fields to support CSW queryables and responses?

**Comment by umacgillivray** [comment]
@ajakz 
Do you have an example JSON document from your index?

[tomcat]/webapps/geoportal-search/WEB-INF/classes/gs/target/elastic/

GeoportalSchema.js is an example of how the Elasticsearch JSON gets mapped. We'll need to do something similar for OneStop by modifying CustomElasticSchema.js.

**Comment by umacgillivray** [comment]
@ajakz 
Also, what were you looking for from the Geoportal UI, search related, publication related or both?

**Comment by ajakz** [comment]
@umacgillivray 
Our latest ES mappings can be found here: https://github.com/cedardevs/onestop/blob/feature/elasticsearch/index-configuration/src/main/resources/searchIndex.json  

For the Geoportal UI, I was trying to enable searching of our index through it. We don't want to allow writing to the index from the Geoportal UI. (Assuming this is what you're asking)

**Comment by umacgillivray** [comment]
@ajakz 
I attached a modified copy of CustomElasticSchema.js that has some of the OnStop fields configured, I couldn't test it but hopefully it won't fail. You'll need replace:
[tomcat]/webapps/geoportal-search/WEB-INF/classes/gs/target/elastic/CustomElasticSchema.js
with the attached version (Tomcat will need a restart, the JavaScript gets cached). We'll probably need a couple more iterations (and maybe a call) to complete this.

[CustomElasticSchema.zip](https://github.com/cedardevs/onestop/files/1322232/CustomElasticSchema.zip)

**Comment by mcquinne** [comment]
FYI - Added a [wiki page](https://github.com/cedardevs/onestop/wiki/CSW-&-OpenSearch-APIs) about how to set up `geoportal-search` to point to the onestop elasticsearch.
