### ISSUE TITLE
EPIC: ES Mapping Improvements

### ISSUE THREAD

**Issue by ajakz** [cedardevs/onestop#216]
The current mappings for metadata need to be revised and reevaluated. The goal of this epic is to incorporate parsing of additional fields, optimize Search Index mapping for... you know, search, and ingest "keywords" with more granularity (1 -> many fields). Some changes to the API request body will likely occur. 

-------------------------

Associated user stories:
- [x] #151 use ISO hierarchy element to designate collection/granule/etc
- [x] #176 remove ability to modify dsmm impact on rankings 
- [x] #182 index accession values separate from keywords
- [x] #188 fix keyword parsing in Metadata Parser
- [x] #202 document indexed fields
- [x] #414  extra fields to be included -- this work will spin off from input from metadata team after reviewing #202
