### ISSUE TITLE
EPIC: Service Discovery

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#218]
- [ ] Identify serviceMetadata records
- [x] Add modify ES index mappings (Parent of #860)
- [ ] UI implications in search results
- [ ] Aggregate and search on service metadata / show in search results

## service xpaths
These were provided by Anna in an email thread, captured here for when we dig into this enhancement.
`/gmi:MI_Metadata/gmd:identificationInfo/srv:SV_ServiceIdentification/srv:containsOperations/srv:SV_OperationMetadata/srv:connectPoint/gmd:CI_OnlineResource/.... `
SV_ServiceIdentification, containsOperations and connectPoint elements are repeatable.
