### ISSUE TITLE
Create Filter Menu

### ISSUE THREAD

**Issue by mcquinne** [cedardevs/onestop#232]
The menu on the left should be be turned into a higher-level component which can then contain our different sub-sets of filters in collapsible panels.

To start with, this will only have a "Keywords" section in it, but eventually we'll drop space and time in here too.

Belongs to epic #142

**Comment by ajakz** [comment]
- [ ] Swap out rc-collapse with [react-tabbordion](https://github.com/Merri/react-tabbordion)
- [ ] Filter menu exhibits accordion behavior -- only one filter type can be open at a time

**Comment by forgo** [comment]
- [ ] created conversion function `metaFacetsConverter = (facets) => { ... }` to take search meta.facets object and convert to something a React component can understand to generate a hierarchical <FacetFilter />
- [ ] write FilterMenu component
- [ ] write FilterSection component
- [ ] write FacetFilter component where `<FacetFilter facets={metaFacetsConverter(facets)} />` traverses the converted facets and generates nested FilterMenu components with "count" in parenthesis. The original "hierarchyCategory" string should be preserved for onChange/Click behavior"
- [ ] write SpaceFilter component
- [ ] write TimeFilter component

**Comment by forgo** [comment]
the checkboxes in the hierarchy menu are now also in sync with the search result "tags" when you "x" out of them, the corresponding checkbox in the facet menu will be unchecked

**Comment by zebdelk** [comment]
Closed by #271
