### ISSUE TITLE
Filter Menu Accessibility

### ISSUE THREAD

**Issue by mcquinne** [cedardevs/onestop#233]
The filter menu from #232 needs to be navigable via screen reader and/or keyboard.

Specifically, you need to be able to cycle through the filter sections and then dive into one if you'd like, e.g. open the facets filters.

Part of epic #142

**Comment by zebdelk** [comment]
Note that exact requirements for screenreaders are still in flux, and awaiting feedback. These assumptions are based around https://cedardevs.github.io/508Demo/alternate.html for structure.

The general structure of the filter widget should be:
```
<h2>Filters</h2>
<a>Show/Hide Search Filters</a>
<Filter Section/>
<Filter Section/>
<Filter Section/>
```

And each filter section should be:
```
<h3>NAME</h3>
<a>Show/Hide NAME Filters</a>
<!-- Elements or sections that are invisible -->
```

- [ ] Sections have appropriate headers
- [ ] Use links styled to look like buttons
- [ ] (TBD) Show/Hide links notify screen readers
- [ ] Link behavior is clear to screen reader users (links may be navigated out of context)
- [ ] (TBD) Filter Section behavior is consistent (apply filter on change vs apply button)
   - TODO: Review if apply-on-change behavior will be clear to screen reader users or confusing.

**Comment by ajakz** [comment]
Right now we're using a 3rd-party component, rc-collapse, for the facet menu. I'm thinking it's not going to be accessible no matter what we do and we'll need to use a different component. I found [this one](https://github.com/Merri/react-tabbordion) though and it looks promising (plus could be useful for other components, like the collection-view tabs). Any thoughts on that with a quick glance?

**Comment by zebdelk** [comment]
A quick look at react-tabbordion:



1. It's definitely not visually keyboard navigable.
    - It doesn't show you what's selected at all
    - The ability to expand / collapse tabs either isn't selected in the tab order at all, or doesn't react when you tab to it and hit enter (or both)
    - There are 5 elements you tab through invisibly before you hit the regular links at the bottom of the demo. I *think* they are the 3 mode options then the 2 tab expand/collapses.
1. I tried their demo page with VoiceOver, it seemed to do an ok job of telling me the status of things, allowing me to interact with changeable elements, etc.
    - I had some issues getting inside the content of each tab (and knowing for sure where I was in the doc) - I'm not sure if this is just inexperience with screen readers or an actual problem?
    - I wonder if Imke would also review their demo, or could suggest a site with the same type of 
functionality that she can easily navigate so we can compare ourselves. (I don't want to overburden her, but it would give me a lot of confidence in dynamic sections to have her input).
1. Either way, that seems to make good use of `aria-expanded="true" aria-selected="true"`, so that's a nice reference for that kind of behavior.

**Comment by zebdelk** [comment]
I also found this: https://medium.com/@andreasmcd/creating-an-accessible-tab-component-with-react-24ed30fde86a

(I mostly played with the final demo in VoiceOver. It's particularly effective because it .kept changing the view to show other random parts of the page.)

My current takeaway is to reiterate that I'm not familiar enough with screen readers yet to know which controls are expected to take me between navigating tabs and content sections, since this was a problem with that component demo above too.

**Comment by zebdelk** [comment]
Re the unchecked items above: I think this is the sort of feedback we're looking for when we ask AUL or other groups to do a review of our site's accessibility. We've made a solid effort to cover this.
- [ ] Make a follow up story to verify those items in a screen reader review?
