### ISSUE TITLE
EPIC: Collections Details UI TLC

### ISSUE THREAD

**Issue by mcquinne** [cedardevs/onestop#235]
Goals:

- [x] Make the main collection results view more accessible (#119) (some support in #276)
- [ ] Hover over results tile reveals full title (#285)
- [ ] Ensure accessibility of collection detail views (#120) 
- [x] Restructure layout to support non-modal collection view (#276)
- [ ] Show collection summaries within the results view (i.e., not a popup) (#312)
- [x] Create tabs for collection detail view (#256)
- [x] Add Summary tab (#255)
- [x] Add Description tab (#257)
- [x] Add Matching Files tab (#259)
- [x] Add Access tab (#258)
- [x] Add Citations tab (#314)
- [x] Enable the ability to link to a particular collection within the results view (#315?)
- [x] Enable standalone collection view outside of the results view? (#315?)
- [ ] Update [Release Checklist](https://github.com/cedardevs/onestop/wiki/Release-Checklist) to cover new functionality

**Comment by mcquinne** [comment]
Potential idea: Use the same approach as with the map in the spatial filters to show a collection summary, i.e. push the results off to the side and use most of the real estate for the summary.

**Comment by ajakz** [comment]
Wireframes:
![collection summary view](https://user-images.githubusercontent.com/5514537/30941597-7fcb9c6a-a3a3-11e7-956c-544d6986ee4c.png)
![collection description view](https://user-images.githubusercontent.com/5514537/30941605-89d149b2-a3a3-11e7-8d92-1197f2097cd9.png)
![collection matching files view](https://user-images.githubusercontent.com/5514537/30941611-91ddc112-a3a3-11e7-9ee9-a7328c95d2bf.png)
![collection access view](https://user-images.githubusercontent.com/5514537/30941619-9ad1f824-a3a3-11e7-9b1d-3433c0f2f276.png)
![collection citations view](https://user-images.githubusercontent.com/5514537/30941632-a5508900-a3a3-11e7-9d8c-4863dc13a2bb.png)

**Comment by zebdelk** [comment]
Closing in favor of #440.
