### ISSUE TITLE
EPIC: Temporal Filters TLC

### ISSUE THREAD

**Issue by mcquinne** [cedardevs/onestop#236]
This epic covers the work necessary to move the time filtering functionality to the filter menu from the search bar, and apply said filtering to existing search results (i.e., not part of initial search but a refining of a query-only search results).

We'd like to:

- [x] Move the temporal filters into the filter menu on the left (#238)
- [x] Remove the filters from the top menu and the front page (#238)
- [x] Change the behavior of date filters so it filters existing results rather than starting a new search (#239)
- [x] Ensure that applying temporal filters is accessible (#118)
- [x] Update [Release Checklist](https://github.com/cedardevs/onestop/wiki/Release-Checklist) to cover new functionality

**Comment by ajakz** [comment]
Wireframe:
![collection results view - temporal](https://user-images.githubusercontent.com/5514537/30941652-c53675a4-a3a3-11e7-8117-a19f75f676af.png)

**Comment by mcquinne** [comment]
All stories are complete and release checklist verbiage updated. Good to go!
