### ISSUE TITLE
EPIC: Space, the Final TLC

### ISSUE THREAD

**Issue by mcquinne** [cedardevs/onestop#237]
Goals:

- [x] Move spatial filter into filter menu on left #374
- [x] Remove spatial filter buttons from top menu and front page #374
- [x] Add the exclude global option back #386
- [x] Improve accessibility by providing text-based geometry entry #374
- [x] Expand map into results area to enable visual box generation (collapse/slide results to show map) #375
- [x] Update behavior so spatial filtering does not trigger a new search #376
- [x] Update [Release Checklist](https://github.com/cedardevs/onestop/wiki/Release-Checklist) to cover new functionality

**Comment by ajakz** [comment]
Wireframes:
![collection results view - spatial](https://user-images.githubusercontent.com/5514537/30941679-e54fd146-a3a3-11e7-93a7-5fd431647a75.png)
![show map](https://user-images.githubusercontent.com/5514537/30941685-ed165710-a3a3-11e7-901a-507c2e3771ab.png)

**Comment by ajakz** [comment]
We should update Leaflet and Leaflet-Draw as part of this epic since Leaflet especially is very out of date

**Comment by ajakz** [comment]
Noticed while poking around that NASA's map has Arctic & Antarctic maps -- we should add something similar to ours if possible

**Comment by ajakz** [comment]
Filters across dateline, when applied to a new search, are disappearing. More motive to look for alternatives to Leaflet...?
