### ISSUE TITLE
Move temporal filters to filter menu

### ISSUE THREAD

**Issue by mcquinne** [cedardevs/onestop#238]
- [x] Move the controls in the current temporal filters popup into a new temporal filters section in the filters menu
- [x] Remove the temporal filter button from the front page
- [x] Remove the temporal filter button from the top menu bar

**Comment by mcquinne** [comment]
See #236 for wireframes
