### ISSUE TITLE
Make spatial search component 508 compliant

### ISSUE THREAD

**Issue by zebdelk** [cedardevs/onestop#241]

**Comment by zebdelk** [comment]
See #233 for more context.

Relative structure:
```
<h3>Spatial</h3>
<a>Show/Hide Spatial Filters</a>
<!-- The following elements are invisible when hidden -->
<form>
<input>BoundingBox</input> 
<a>Show Map</a>
<button>Apply</button>
<button>Clear</button>
```

- [ ] Sections have appropriate headers
- [ ] Use links styled to look like buttons
- [ ] Link behavior is clear to screen reader users (links may be navigated out of context)
- [ ] Links names are not too long / over-descriptive
- [ ] Button behavior (Apply/Clear) makes sense to screen readers (which field is cleared, and if apply needs to be hit to take effect)
- [ ] Input / form labels are used correctly identify fields to screen readers
- [ ] format of input is clear to screen readers
- [ ] Validation errors are understood by screen readers
- [ ] The show map button is skipped by screen readers
- [ ] (TBD) Filter Section behavior is consistent (apply filter on change vs apply button)

**Comment by mcquinne** [comment]
This issue is outdated. We will assess the current accessibility of the space filter and generate new issues if needed.
