### ISSUE TITLE
EPIC Accessibility Improvements From MediaCurrent

### ISSUE THREAD

**Issue by ajakz** [cedardevs/onestop#250]
See site audit slide deck

AC:
- [x] Improve color contrast as suggested
- [x] Add language tag in HTML header
- [x] Add required labels to all form fields (on main site these can be hidden)
- [x] Add alt text to icons *
- [x] Add accessibility statement to accessible site

* We would do images but we've covered this before: the alt text has to be supplied in the metadata because we have no idea what the images are from the app. Also we were told the image alt text of 'Collection Image' is not actually useful and a bit annoying.

**Comment by ajakz** [comment]
We addressed all issues from the initial Mediacurrent evaluation of our site. Will likely have a new epic when we receive additional feedback.
