### ISSUE TITLE
EPIC: Search Optimization

### ISSUE THREAD

**Issue by mcquinne** [cedardevs/onestop#266]
### Goal

Improve search performance.

### General Approach

We want to split our main search API endpoint out into multiple endpoints with more focused, simple behaviors. We'd like to create separate endpoints to:
- [x] Redefine search index #489
- [x] Update ETL to write to new search index #490
- [x] Search against collections and return collections #394
- [x] Search against granules and return granules #395
- [x] Search against granules and return collections (current behavior) #396
- [x] Add 'summary' flag to endpoint w/ subset of fields #491
- [x] Retrieve collections (or granules?) directly by ID #397
- [x] Retrieve totalCounts, including count of granules for a specific collection #398

- [x] remove summary flag from queries #508
#### Notes:

- Search endpoints should all accept request objects of the same shape
- Search requests should no longer support collection filters
- Search requests should support a "summary" flag which only returns a small subset of attributes

**Comment by dneufeldcu** [comment]
- [ ] Test edge cases #460 Moved to 2.1 release

**Comment by dneufeldcu** [comment]
Confirmed all stories closed or moved.
