### ISSUE TITLE
Remove collection view popup

### ISSUE THREAD

**Issue by zebdelk** [cedardevs/onestop#312]
AC:
- [x] Push result tiles out of the way and show a div with the collection detail view

**Comment by mcquinne** [comment]
Initial logic in place. More specific to do items:

- [ ] Animate height on open
- [ ] Clean up details heading (show more, close button...)
- [ ] Auto scroll the screen to the selected collection card
- [ ] Keep selected collection card highlighted
- [ ] Consider options for details height... e.g. should it stay constant?
- [ ] Consider setting details width to match current card columns width

**Comment by mcquinne** [comment]
After trying a couple approaches and running into a number of roadblocks, we've decided to table this change for the time being. We'll proceed with collapsing the space and time filters into the filter menu in #236 and #237 as well as improve/expand the endpoints available from the backend in #266. Then we'll work on some wireframes in #366 to facilitate a broader discussion about what we should do to display collection details and their granules.

For now, I'm leaving two branches pointing to the beginnings to two potential implementations: 312-inline-details places the details view inline with the collection results, while 312-standalone-details replaces the collection results with a details view.

**Comment by zebdelk** [comment]
Proposed path forward for #440:

- [ ] merge 312-standalone-details
- [ ] move title of collection above tabs and make it an H1 element
- [ ] make sure height is not restricted if tab content grows too large

**Comment by zebdelk** [comment]
Depends on #397 to get a collection by id to work correctly.
