### ISSUE TITLE
Add Functionality To Link To Collection Detail

### ISSUE THREAD

**Issue by ajakz** [cedardevs/onestop#315]
AC:
- [ ] Button in collection detail to "Copy Link To Collection"
- [ ] URL resolves to view of just the collection? 
- [ ] URL support to resolve to an open collection w/search results?

**Comment by zebdelk** [comment]
No longer needed, since design doesn't include collection in-line with search results.
