### ISSUE TITLE
Release Checklist 1.3.2

### ISSUE THREAD

**Issue by forgo** [cedardevs/onestop#336]
- [x] add 100vh to middle content for collections, similar to help/about so footer is not floating above bottom when content doesn't fill screen

- [x] ~hamburger menu not showing in IE when collapsed window size~ (will be covered by #339)

- [x] ~IE can't collapse left menu (not a deal breaker)~ (will be covered by #340)

- [x] ~IE shows "Featured Data Sets:" heading  even when they are not visible on landing.~ (will be covered by #341)

**Comment by zebdelk** [comment]
- [ ] in IE 11, there's some strange padding on IE collection results

![Screen Shot 2017-11-15 at 3.37.21 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/591b3ded1d376e001ad78dc3/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76226455f66b7191a37bf1112c4f5d5e5ecc3c4a4356bcbbd671f3e57862804e0ee4d03e0c26973a16aeb0804cb601b822d84b87b0ee894fd2f42f67b6d5db1063474f4dcbed5727a19141c95df74be64550a0153763ef742431.png)

**Comment by zebdelk** [comment]
- [ ] Elasticsearch 2 does not appear to be clustered correctly. on VM 2 it has no indices at all

**Comment by zebdelk** [comment]
- [ ] add to release checklist: verify site css with different screen sizes, since some stuff only misbehaves if the window is small

**Comment by zebdelk** [comment]
- [ ] https://sciapps.colorado.edu/onestop/#/508/help/ shows the filter menu in the left side, which makes no sense (about also has this problem) - this was specifically entering the /508/help/ url directly, it works if the link is clicked from the menu

**Comment by zebdelk** [comment]
- [ ] weird open/close css on iPhone/safari

![IMG_5527.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/591b3ded1d376e001ad78dc3/125516c66e82c728ace21e0d46c1b9bd1cd7d6fbd8abf301b44fff9e2c4533317346f6722186e02abe152c53575d1da5415a5d17f8fb8f79a5b52e6c981e5ab38532022d8c6853beb2901eb80bbb258a4f82bebb824ac2ed3e26f5c6.PNG)

**Comment by mcquinne** [comment]
Everything in this story has either been already fixed or generated new stories to fix them in 2.0
