### ISSUE TITLE
Move spatial filter into filter menu on left

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#374]
- [x] The map filter capability needs to move from the top level buttons down into the left panel filter options.
- [x] Remove map  buttons from SearchFieldsContainer
- [x] Improve accessibility by providing text-based geometry entry
- [x] Remove Reset Search button from SearchFieldsContainer (after this, only the search/magnifying glass button and the X in the text box will be in this component)
