### ISSUE TITLE
Add exclude global to spatial filter

### ISSUE THREAD

**Issue by ajakz** [cedardevs/onestop#386]
- [x] Add exclude global results checkbox back to the filters, under the spatial filter menu section
- [x] Link with exclude global flag should load with Exclude Global checkbox checked
- [x] New search should clear all filters, including Exclude Global flag
