### ISSUE TITLE
Update metadata parsing/mapping

### ISSUE THREAD

**Issue by ajakz** [cedardevs/onestop#389]
The metadata team has gotten back to us with refined paths to parse metadata and new fields to parse. (shared spreadsheet in drive -- "OneStop Metadata Indexing Fields -  Review") 
- [ ] Update MetadataParser
- [ ] Update Elasticsearch index mappings
- [ ] Update tests (include all alternate routes for fields in unit tests)
- [ ] Update wiki to show new paths & new fields

**Comment by mcquinne** [comment]
Closing in favor of #414
