### ISSUE TITLE
EPIC: Extract Integration

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#391]
## Context

A client application should be able to post a list of URLs of publicly accessible datasets to an external common access service to package and stage a collection of files for download by a user.

## User Statement

- [ ] As a Extract API user, I want to be able to POST a JSON request with a list of granule access links and an email, and get a tar emailed to me with the data.

Proposed JSON payload to submit from OneStop to Extract API:
[Drive: JSON payload doc](https://docs.google.com/document/d/1UUfZdqrWR8hot81KbCfyz8rw2F5Bku2QClgVhGSH9gc/edit?usp=sharing) 

## Acceptance Criteria

- [ ] Post to Extract API (Parent of #640)
- [ ] Wireframe Extract UI (Parent of #653)

## Future Features - Discuss:
- [ ] Mock data delivery service (Parent of #760)
- [ ] Download component (Parent of #756)
- [ ] Wireframe data delivery alternative options (Parent of #678)
- [ ] Supporting UI changes when no links available
- [ ] Cancel dialog
- [ ] Visualize download progress; report # successfully downloaded
- [x] Shopping cart cleanup (Parent of #734)

**Comment by dneufeldcu** [comment]
Switched to using a label for AOP items based on a suggestion from Zeb.
