### ISSUE TITLE
EPIC: Time Filter Enhancements

### ISSUE THREAD

**Issue by ajakz** [cedardevs/onestop#392]
This epic covers the addition of some extended functionality to our time filtering. Specifically, allowing 'relation' to be declared in time filtering (similar to the 'relation' used in spatial filtering; see the [request schema](https://github.com/cedardevs/onestop/blob/master/api-search/src/main/resources/onestop-request-schema.json)) and supporting paleo dates.
- [x] Support paleo dates (parent of #223)
- [ ] Enable users to search records that intersect given dates OR are confined by given dates (parent of #327)
- [ ] Add paleo search functionality to UI (parent of #501)

Note: The paleo search page has time filtering functionality that we should mimic elements of -- [search page](https://www.ncdc.noaa.gov/paleo-search/)
