### ISSUE TITLE
EPIC: MediaCurrent UI 2.0 priorities

### ISSUE THREAD

**Issue by zebdelk** [cedardevs/onestop#401]
- [x] Landing page
- [x] Landing page: add about section below featured data sets, instead of only in menu - intent achieved via the data.noaa.gov page 
- [x] Search results page: default to white background
- [x] Search results: put new search bar at the top of the page, but not in the header (I recommend above Search Results header, since it should start a new search)
- [x] Search result tile - update style
- [x] Filter menu - revise check boxes to either unchecked or checked #536

## recommendations that we should probably not pursue:

- [x] Sort By element on the search result page
- [x] Tiny hidden filters button on search result page / popup
- [x] Popup topic / map / date filters on main search bar (since we are removing these)

https://drive.google.com/open?id=1TmYi1MHl-pn3c1khWphm3VuWGKNCvo1Q
