### ISSUE TITLE
Toggle map behavior

### ISSUE THREAD

**Issue by ajakz** [cedardevs/onestop#406]
The map toggling should be more responsive to what is displayed in the UI. Namely:

- [x] Map should be hidden when leaving the results page
- [x] Map should be hidden when the Spatial panel is collapsed (the 'Hide Map' button is no longer accessible, making its staying open awkward)
- [ ] ~~Map should be hidden when a collection is opened (preparing for when the collection takes up results area)~~ Reconsider this when we return to Collection Detail UI work

**Comment by zebdelk** [comment]
Reviewed! This looks good.
