### ISSUE TITLE
Update parsing based on metadata team feedback

### ISSUE THREAD

**Issue by mcquinne** [cedardevs/onestop#414]
Using the spreadsheet created by the metadata team:
- Add new fields to the staging index
- Update existing fields as indicated

Note:
Do not include geometry parsing logic updates.

**Comment by mcquinne** [comment]
TODO:
- [ ] Update MetadataParser
- [ ] Update Elasticsearch index mappings
- [ ] Update tests (include all alternate routes for fields in unit tests)
- [ ] Update wiki to show new paths & new fields

**Comment by ajakz** [comment]
Closing this in favor of more specific stories

**Comment by ajakz** [comment]
Reopened this to reflect branch of consolidating specific stories before merging to master
