### ISSUE TITLE
EPIC: 508 Improvements

### ISSUE THREAD

**Issue by ajakz** [cedardevs/onestop#426]
- [x] #357 
- [x] #424 Aria labels
- [ ] #418 Collection results list: more heading levels than needed
- [ ] #423 Spike map accessibility
- [ ] #422 Tree view improvement

# AAA findings 
- [ ] link contrast (parent of #801)
- [ ] Maximum Line Length and Line Spacing (parent of #802)

**Comment by zebdelk** [comment]
Accessibility Info currently lives on the About Us page.

**Comment by dneufeldcu** [comment]
Achieved AA standards
