### ISSUE TITLE
filter apply/clear buttons do not trigger unneeded searches

### ISSUE THREAD

**Issue by zebdelk** [cedardevs/onestop#428]
For both space and time filters.

Filter buttons:
- [ ] disable apply/clear if all the fields are empty
- [ ] clear button should not submit a search if there are no applied time filters (though it should still clear the fields)
- [ ] apply button should not submit a search if the time filter that would be applied is already applied to the search

**Comment by zebdelk** [comment]
Resubmitting a search with no changes is valid (looking for new results, time filters imply 'now', etc)
