### ISSUE TITLE
EPIC: Collection UI TLC

### ISSUE THREAD

**Issue by zebdelk** [cedardevs/onestop#440]
General:
- [x] Archive older version of this epic (#235)
- [x] Hover over results card shows full title (#285)
- [x] wrap up: overall 508 (#463)

Details View:
- [x] Show collection details in main body of page (i.e., remove popup) (#312)
- [x] 508 collection detail (#441)
- [x] show filter on page (redux state) (#442)

Specific Changes:
- [x] Description (#451)
- [x] Overview (#450)
- [x] Access (#452)
- [x] Citation (TODO design where citation is shown)

- [x] collection detail view: summary
![Screen Shot 2018-01-09 at 10.52.16 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/591b3ded1d376e001ad78dc3/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77226454fa6b7191a379ef0c2e53415e48bc30254d58eeb9cb74fce36f34985619e8d86c0c27946c16abba8a1dec08ba22891c81b4bad84fc3fa2137a5dad11b61435c52dcbd4f3fb29843c259f34ae44857a4103067ee74376e0a.png)

- [x] collection detail view: summary + DSMM popup
![Screen Shot 2018-01-09 at 10.53.30 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/591b3ded1d376e001ad78dc3/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77226454fa6b7191a379ef0c2e52415c4ebc30254d58eeb9cb74fce36f34985619e8d86c0c27946c16abba8a1dec08ba22891c81b4bad84fc3fa2137a5dad11b61435c52dcbd4f3fb2984cc259f34ae44857a4173563e575376e0a.png)

- [x] collection detail view: data access

![Screen Shot 2018-01-09 at 10.54.30 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/591b3ded1d376e001ad78dc3/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77226454fa6b7191a379ef0c2e55415c4ebc30254d58eeb9cb74fce36f34985619e8d86c0c27946c16abba8a1dec08ba22891c81b4bad84fc3fa2137a5dad11b61435c52dcbd4f3fb29843c259f34ae44857a4173164e47f3f6e0a.png)

- [x] collection detail view: matching files
![Screen Shot 2018-01-09 at 10.54.47 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/591b3ded1d376e001ad78dc3/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77226454fa6b7191a379ef0c2e55415b49bc30254d58eeb9cb74fce36f34985619e8d86c0c27946c16abba8a1dec08ba22891c81b4bad84fc3fa2137a5dad11b61435c52dcbd4f3fb29843c259f34ae44857a4163660e6703e6e0a.png)

- [x] collection detail view: related
![Screen Shot 2018-01-09 at 10.55.16 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/591b3ded1d376e001ad78dc3/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77226454fa6b7191a379ef0c2e54415e48bc30254d58eeb9cb74fce36f34985619e8d86c0c27946c16abba8a1dec08ba22891c81b4bad84fc3fa2137a5dad11b61435c52dcbd4f3fb2984cc259f34ae44857a4163460e074316e0a.png)

**Comment by zebdelk** [comment]
![IMG_6238.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/591b3ded1d376e001ad78dc3/125516c66e82c728ace21e0d46c1b9bd1cd4d1fad7abf301b44fff9e2c4533317346f6722186e02abe152c53575d1da5415a5d17f8fb8f79a5b52e6c981e5ab38532022d8c6853beb2901eb80bbb258a4886b2bd8348c1e03b26f5c6.JPG)
![IMG_6241.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/591b3ded1d376e001ad78dc3/125516c66e82c728ace21e0d46c1b9bd1cd4d1fddeabf301b44fff9e2c4533317346f6722186e02abe152c53575d1da5415a5d17f8fb8f79a5b52e6c981e5ab38532022d8c6853beb2901eb60bbb258a4886b2bd8348c8ed3422f5c6.JPG)

**Comment by zebdelk** [comment]
Question: Is it worth reiterating the citation info on the granule file list?

**Comment by dneufeldcu** [comment]
Confirmed all stories closed.
