### ISSUE TITLE
508: collection details

### ISSUE THREAD

**Issue by zebdelk** [cedardevs/onestop#441]
- [x] alert user pages has changed (including 'loading' and 'ready' type messages)
- [x] change focus to top of main content
- [x] aria roles for tabs: identify what tabs are available, with additional information such as "1 of 3", what the tab status is "open/close" and marking the tab content.
- [x] tab headings are H2 (TODO: check that this is the best choice for heading structure - it may make more sense to have H2 be the first heading level inside the tab content instead)
- [x] along with fixing tab and general heading levels - get the relative font sizes to make more sense

**Comment by zebdelk** [comment]
Note for testing: changing the focus is also critical for sighted users, as when you scroll down to the bottom of the results and click on a collection, it leaves you looking at the footer and not seeing the title / top part of the view if the window is too small.
