### ISSUE TITLE
show filter on page (redux state)

### ISSUE THREAD

**Issue by zebdelk** [cedardevs/onestop#442]
Move logic to show Filter into redux store, and hide it completely on the detail page

- [ ] move the logic for including the left side filter element into the redux store
- [ ] the collection detail should update it to not display at all
- [ ] include if applied filter bubbles should be shown, or refactor the detail view so that they don't appear above the selected collection (possibly just change the nesting of routes in index.jsx)
