### ISSUE TITLE
Granule files view

### ISSUE THREAD

**Issue by zebdelk** [cedardevs/onestop#445]
- [x] add link ("show matching files" or "show files matching my search") to collection summary tab to do granule search
- [x] use new endpoint to get granule results. (search by passing array of collection ids, ignore keywords).
- [x] update URL
- display list view:
  - [x] shows filter options on left (moved to #447)
  - [x] basic result: title + list of links
  - [x] updates 508 user on load (What information is announced to user)
- [x] remove Matching Files tab

**Comment by zebdelk** [comment]
Note: This view isn't going to show filter options for now, since this story doesn't include the work to apply the filters to the correct search (they currently try to modify the collection search instead)
