### ISSUE TITLE
Summary (List result view detail element)

### ISSUE THREAD

**Issue by zebdelk** [cedardevs/onestop#448]
- [x] reuse component to show map or thumbnail (make sure default if there is no thumbnail or geometry makes sense)
- [x] show title as H2 element
- [x] show links as H3 element with unordered lists (display as table as in Access Tab)

**Comment by zebdelk** [comment]
Note: after switching to a result list view for granules and completing this, we can get ride of the map component specific to the matching files tab.
