### ISSUE TITLE
Overview Tab

### ISSUE THREAD

**Issue by zebdelk** [cedardevs/onestop#450]
- [x] Add "total files" and count (requires updated collection GET endpoint)

508:
- [x] each info block label ("Time Period", "Themes", etc) should be an H3 element (see note in #441 about correct relative heading levels)
- [x] list content (Themes, Instruments, Platforms) should be ul and li elements
- [x] any "show more" links should use aria to label them "show more [Themes]" for disambiguation
- [x] map is marked appropriately by aria as much as we can easily control or hidden

**Comment by forgo** [comment]
see #445 for changes
