### ISSUE TITLE
Overall collection detail accessibility

### ISSUE THREAD

**Issue by zebdelk** [cedardevs/onestop#463]
This is a final review of the overall 508 compliance of the collection views. Most of these are expected to have no changes, since other work should hopefully address them, but most other stories are more focused on specific views and sections, rather than how everything comes together.

- [x] relative order of collection detail DOC makes sense (for all tabs)
- [x] relative order of the granule list DOC makes sense
- [x] any links/buttons/etc have enough detail to be distinguished out of order (eg. show more)
- [x] links are implemented as links and not buttons
- [x] verify tab order makes sense, and all interactive elements are keyboard accessible
- [x] verify element navigation with screenreader using up/down keys correctly hits all elements
- [x] verify popup warning for links that leave the domain works for screen reader users

**Comment by zebdelk** [comment]
links and buttons look good overall, created issue #562 to cover the one place they still need some improvement

**Comment by zebdelk** [comment]
All the work that went into 2.0.0-RC6 covered this, except the one new backlog issue mentioned above.
