### ISSUE TITLE
Run through release checklist for 2.0.0-RC2

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#497]
Start on Monday March 5th

**Comment by zebdelk** [comment]
## Manual UI checks

### Set up the test environment

- [ ] Deploy the latest candidate to the SciApps demo site
- [ ] Reset the indices and reload the data.

### General checks
- [ ] Landing page functionality
  - [ ] Correct Version # (visible in the footer of the page)
  - [ ] "About Us" page lists expected number of collections (413) and granules (51). These numbers are reflective of the test data from Ansible (clean CU deployment with empty ElasticSearch); otherwise, they will likely be different values.
  - [ ] Links in the header menu and footer work
- [ ] Verify CSS changes work across browsers
  - [ ] IE 11
    - [ ] on AdminLan
    - [ ] on Windows
    - note for css on IE (VirtualBox): You may have to manually clear the IE cache.
  - [ ] Firefox latest
    - [ ] on Mac
    - [ ] on AdminLan
  - [ ] Chrome Latest
    - [ ] on Mac
    - [ ] on AdminLan
  - [ ] Safari
  - [ ] Opera
  - [ ] Confirm supported browser docs: [Supported Browsers](https://github.com/cedardevs/onestop/wiki/OneStop-Client-Supported-Browsers)
- [ ] Use chrome devtools mobile view to check how it looks on mobile devices and custom dimensions.
  - rotate to landscape views
- [ ] General page responsiveness (adjust window size between large and small)
  - [ ] Does landing page adjust gracefully?
  - [ ] Do header and footer elements maintain a reasonable placement in the page layout? 
  - [ ] If all keyword categories are expanded on search page, do they stay visible (push footer down without clipping)? 
  - [ ] Do result cards respond to page adjustments (proper flex behaviors)? 
  - [ ] Does an open collection detail view realign elements cleanly on each tab?

### Search Verification

#### Keywords

  - [ ] From landing page, click 'Weather' in Search By Topic. Results count is 53. Confirm clicking `Show More Results` button loads 20 additional results, after 2 clicks button disappears and section header states 'Search Results (showing 53 of 53)'
  - [ ] All cards show thumbnail images or black overlay in event image is slow to load/not available (external service; either of these are okay)
  - [ ] Keywords Data Theme shows:
    - Agriculture (1)
    - Atmosphere (15)
    - Biological Classification (1)
    - Biosphere (1)
    - Climate Indicators (1)
    - Cryosphere (1)
    - Oceans (51)
    - Spectral/Engineering (1)
  - [ ] Confirm keyword labels are rendered and functioning accurately:
    - Drill down through Data Theme, verifying labels match 'Atmosphere' > 'Atmospheric Winds' > 'Surface Winds' > 'U/V Wind Components'.
    - Select keyword above. Tag above collection cards reads 'U/V Wind Components'.
    - Open collection card. Verify tag appears as 'U/V Wind Components' in 'Themes' section.
    - Back to Keywords, confirm 'Anemometers' and 'MOCNESS Plankton Net' under 'Instruments' category have correct capitalization.
    - Select both in facet menu. Confirm string format is consistent in tags.
    - Open collection card and confirm format again under 'Instruments' category.
    - Look for last `search` request in browser dev tools. Confirm request payload is: 
{"queries":[{"type":"queryText","value":"weather"}],"filters":[{"type":"facet","name":"science","values":["Atmosphere > Atmospheric Winds > Surface Winds > U/V Wind Components"]},{"type":"facet","name":"instruments","values":["ANEMOMETERS","MOCNESS > MOCNESS Plankton Net"]}],"facets":true,"page":{"max":20,"offset":0}}

#### Time Filter (Temporal)

- [ ] Overlapping Allowed
    - Start with a fresh search by selecting 'Fisheries' topic on Landing Page -- 2 results returned
    - In time filter, set start to any day in 2010 and apply -- now 1 result, 'Tutuila, American Samoa [...]' (AKA Return data covering anytime after {day}, 2010)
    - Clear time filter (X button) and initiate new search again -- back to 2 results
    - Apply new time filter by selecting end to any day in 1990 and apply -- 1 result, 'Tutuila, American Samoa [...]' (AKA Return data covering anytime before {day}, 1990)
- [ ] Overlapping Restricted
    - TBD
- [ ] Paleo Dates
    - TBD

#### Location Filter (Spatial)

- [ ] Rendering across dateline
    - Search `"southern alaska coastal relief"` -- 1 result returned. 
    - Inside collection summary tab, bounding coordinates read: 'Bounding box covering 170°, 48.5°, -130°, 66.5° (W, N, E, S).' 
    - Map image shows enclosed area of Alaska.
- [ ] Rendering across prime meridian
    - Search `mediterranean` -- 17 results returned.
    - Open GHRSST ODYSSEA collection (should be second result). Bounding coordinates read: 'Bounding box covering -18.5°, 30°, 36.5°, 46.5° (W, N, E, S).'
    - Map image shows enclosed area of Mediterranean region in Europe.
- [ ] Searching by geometry
    - Search `water` -- 393 results returned.
    - Using map filter, draw a bounding box over the Mediterranean region and initiate new search -- 64 results returned.
    - Apply 'Exclude Global' filter -- TBD results returned (need to reinstate this filter in the coming Spatial filter section)

#### Collection View

- [ ] Confirm title expands/collapses

Summary Tab
- [ ] Time range
- [ ] No end date 
- [ ] No time range
- [ ] Spatial -- bounding box
- [ ] Spatial -- point (search `glacier`)
- [ ] Spatial -- no geometry
- [ ] DSMM present
- [ ] DSMM not available
- [ ] Keywords

Description Tab
- [ ] Thumbnail image
- [ ] No thumbnail image but spatial bounding available
- [ ] No thumbnail or spatial bounding
- [ ] Description 

Matching Files Tab
- [ ] Map rendering & data types
    - Search `ghrsst viirs`. First result should be "GHRSST GDS2 Level 2P Global Skin Sea Surface Temperature from the Visible Infrared Imaging Radiometer Suite (VIIRS) on the Suomi NPP satellite created by the NOAA Advanced Clear-Sky Processor for Ocean (ACSPO) (GDS version 2)"
    - Under Matching Files tab, multiple granules with a variety of bounding boxes appear. Confirm in search request total count in 29.
    - Access Protocols show Download, FTP, OPeNDAP, THREDDS.
    - Click 'Show More Results' button. Access Protocols now includes Web.
- [ ] Filtering granules -- time
    - Search `coops`
    - Open collection and go to 'Matching Files' tab. Search request shows 22 total granules matching.
    - Apply time filter to search, filtering between 2016-12-01 and 2016-12-31. 
    - Open collection and go to 'Matching Files' tab again. Search request now shows 10 total granules matching.
- [ ] Filtering granules -- space
    - Follow first two steps from above.
    - Apply spatial filter to search with a bounding box enclosed around Hawaii.
    - Open collection and go to 'Matching Files' tab again. Search request now shows `TBD` total granules matching.

Access Tab
- [ ] Confirm 3 rows in table of this tab -- Information, Download Data, and Distribution Formats


#### Miscellaneous Edge Cases

- [ ] Results cards with no thumbnail image show a map
    - Search `Nikolski`. Returns 4 results, 2 of which have no thumbnail image and should instead render a map.
- [ ] Results with no spatial bounding & no thumbnail show world map
    - Search `TBD`. Confirm result card shows a world map.

### Error conditions

#### Text Search Errors

- [ ] entering with a blank text search field will result in an error message
- [ ] starting a search with an asterisk '*' or question mark '?' will result in a corresponding error message
- [ ] using an escape character '\' in the search field will result in a parsing error

#### Spatial Search Errors

- [ ] entering invalid bounding box coordinates, for example, West: -191, South: 90, East: 90, North: 90, will result in a relevant error message upon hitting the "Apply" button
- [ ] leaving coordinates blank, for example, West: -180, South: *empty*, East: *empty*, North: *empty*, will result in a relevant error message upon hitting the "Apply" button

### Accessibility and 508 compliance

- [ ] Run Chrome plugin WAVE (Web Accessibility Evaluation Tool) and check for errors on:
  - landing page
  - main site (search header, left filter menu, results view, details views, about page, help page)
  - 508 search page (to be removed)
  - 508 results page (to be removed)

- [ ] Run screen reader software in a Windows VM environment
  - TBD

## Code verification

- [ ] update libraries to the latest, if possible
- [ ] Run retire -p on client code [Retire JS](https://retirejs.github.io/retire.js/)
- [ ] OWASP - Run /gradlew dependencyCheckAnalyze --info
- [ ] Ensure that included images are compressed in the git repo
