### ISSUE TITLE
Search endpoint tech debt

### ISSUE THREAD

**Issue by ajakz** [cedardevs/onestop#499]
The search endpoints aren't following any consistent pattern and could easily get out of hand if we add more features in the future. Makes more sense to:
- [x] ~Organize endpoints (controllers) by data type~
- [x] Move counts endpoints under data types
- [x] Group integration tests by data type
- [x] ~Adjust source fields for summary results by type? (Works including fields not present in ES requests but not the cleanest way to do that)~
