### ISSUE TITLE
EPIC: Allow search of flattened granules

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#531]
Search index should support search of granules via the API with inherited/flattened metadata.

A secondary goal of this epic is to make sure external partners have the documentation they need to use the API successfully.

# Flattened Granules

- [x] ETL (Parent of #581)
- [x] management of index (Parent of #580)
- [x] test improvement (Parent of #499)

# Partner Support

- [x] swagger docs (Parent of #582) (see also #51)
- [x] host api docs (Parent of #585)
