### ISSUE TITLE
Spike: ICAM see #145

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#540]
- [x] Read google doc in Epic
- [x] Generate SP metadata
- [x] Learn about SAML

Acceptance Criteria:
 generate follow on user stories as needed for implementation

**Comment by forgo** [comment]
For future stories:

- [ ] Obtain public and private (if needed) certs for sciapps to use with  spring-boot-security-saml.
- [ ] Generate dummy ICAM/SAML endpoint on API-metadata 
- [ ] Recreate SAML login behavior on api-metadata, using a new SSO service (try to minimize dependencies/configuration needed directly within api-metadata)
