### ISSUE TITLE
Zeb - checklist

### ISSUE THREAD

**Issue by zebdelk** [cedardevs/onestop#552]
### Set up the test environment

- [x] Deploy the latest candidate to the SciApps demo site
- [x] Reset the indices and reload the data.

### General checks
- [x] Landing page functionality
  - [x] Correct Version # (visible in the footer of the page)
  - [x] "About Us" page lists expected number of collections (414) and granules (51). These numbers are reflective of the test data from Ansible (clean CU deployment with empty ElasticSearch); otherwise, they will likely be different values.
  - [x] Links in the header menu and footer work
- [ ] Verify CSS changes work across browsers
  - [ ] IE 11
    - [ ] on AdminLan
    - [x] on Windows
    - note for css on IE (VirtualBox): You may have to manually clear the IE cache.
  - [ ] Firefox latest
    - [x] on Mac
    - [ ] on AdminLan
  - [ ] Chrome Latest
    - [x] on Mac
    - [ ] on AdminLan
  - [x] Safari
  - [ ] Confirm supported browser docs: [Supported Browsers](https://github.com/cedardevs/onestop/wiki/OneStop-Client-Supported-Browsers)
- [x] Use chrome devtools mobile view to check how it looks on mobile devices and custom dimensions.
  - rotate to landscape views
- [x] General page responsiveness (adjust window size between large and small)
  - [x] Does landing page adjust gracefully?
  - [x] Do header and footer elements maintain a reasonable placement in the page layout? 
  - [x] If all keyword categories are expanded on search page, do they stay visible (push footer down without clipping)? 
  - [x] Do result cards respond to page adjustments (proper flex behaviors)? 
  - [x] Does an open collection detail view realign elements cleanly on each tab?

#### Keywords

  - [x] From landing page, click 'Weather' in Search By Topic. Results count is 25. Confirm clicking `Show More Results` button loads 20 additional results, after 1 click button disappears and section header states 'Search Results (showing 25 of 25)'
  - [x] All cards show thumbnail images or black overlay in event image is slow to load/not available (external service; either of these are okay)
  - [x] Keywords Data Theme shows:
    - Agriculture (1)
    - Atmosphere (15)
    - Biological Classification (1)
    - Biosphere (1)
    - Climate Indicators (1)
    - Cryosphere (1)
    - Oceans (23)
    - Spectral/Engineering (1)
  - [x] Confirm keyword labels are rendered and functioning accurately:
    - Drill down through Data Theme, verifying labels match 'Atmosphere' > 'Atmospheric Winds' > 'Surface Winds' > 'U/V Wind Components'.
    - Select keyword above. Tag above collection cards reads 'U/V Wind Components'.
    - Open collection card. Verify tag appears as 'U/V Wind Components' in 'Themes' section.
    - Back to Keywords, confirm 'Anemometers' and 'MOCNESS Plankton Net' under 'Instruments' category have correct capitalization.
    - Select both in facet menu. Confirm string format is consistent in tags.
    - Open collection card and confirm format again under 'Instruments' category.
    - Look for last `search` request in browser dev tools. Confirm request payload is: 
{"queries":[{"type":"queryText","value":"weather"}],"filters":[{"type":"facet","name":"science","values":["Atmosphere > Atmospheric Winds > Surface Winds > U/V Wind Components"]},{"type":"facet","name":"instruments","values":["ANEMOMETERS","MOCNESS > MOCNESS Plankton Net"]}],"facets":true,"page":{"max":20,"offset":0}}

#### Time Filter (Temporal)

- [x] Overlapping Allowed
    - Start with a fresh search by searching 'Tutuila' on Landing Page -- 4 results returned
    - In time filter, set start to any day in 2010 and apply -- now 1 result, 'Tutuila, American Samoa [...]' (AKA Return data covering anytime after {day}, 2010)
    - Clear time filter (X button) and initiate new search again -- back to 4 results
    - Apply new time filter by selecting end to any day in 1990 and apply -- 3 result, 'Tutuila, American Samoa [...]' (AKA Return data covering anytime before {day}, 1990)
- [ ] Overlapping Restricted
    - TBD
- [ ] Paleo Dates
    - TBD

#### Location Filter (Spatial)

- [x] Rendering across dateline
    - Search `"southern alaska coastal relief"` -- 1 result returned. 
    - Inside collection summary tab, bounding coordinates read: 'Bounding box covering 170°, 48.5°, -130°, 66.5° (W, N, E, S).' 
    - Map image shows enclosed area of Alaska.
- [x] Rendering across prime meridian
    - Search `mediterranean` -- 17 results returned.
    - Open GHRSST ODYSSEA collection (should be second result). Bounding coordinates read: 'Bounding box covering -18.5°, 30°, 36.5°, 46.5° (W, N, E, S).'
    - Map image shows enclosed area of Mediterranean region in Europe.
- [x] Searching by geometry
    - Search `water` -- 351 results returned.
    - Using map filter, draw a bounding box over the Mediterranean region and initiate new search -- 32 results returned.
    - In bounding box text fields, enter: -32,-1,120,60 -- 32 results returned
    - Apply 'Exclude Global' filter -- 10 results returned

#### Collection View

- [x] Confirm url changes to collections/details/UUID
- [x] Search `ghrsst`
  - Confirm collection has 0 total matching files and therefore no link
  - Overview tab displays bounding box
  - Shows DSMM rating
- [x] Search `co-ops`
  - Confirm first result has 22 matching files
  - No end date so displays as "2013-03-01 to Present"
- [x] Search `weather`
  - First result has start and end date (2007-10-13 to 2016-02-14)
- [x] Search `glacier`
  - first result has point geometry on summary tab (Point at -49.815°, 69.222° (longitude, latitude))
  - themes has a show all link
  - only one instrument listed (no show all link)
- [x] Search `little rock`
  - First result has line geometry on Overview tab ("Line from -7.7°, 51.5° (WS) to -7.7°, 51.6° (EN).")
- [x] Search `suvi`
  - No spatial bounding provided. World map shown with no red bounding box.
  - videos tab exists
  - DSMM not available
  - themes has only 3 keywords, and no show all link
  - instrument and platforms both say 'none provided'
- [x] the search above for weather with U/V Wind Components keyword lists 'show all' for instruments as well
  - tip: paste in the query q=weather&f=science:Atmosphere%20%3E%20Atmospheric%20Winds%20%3E%20Surface%20Winds%20%3E%20U%2FV%20Wind%20Components
- [x] Search `paleoclimatology`
  - 2 results returned
  - For 'NOAA/WDS Paleoclimatology - A global planktic foraminifer census data set for the Pliocene ocean' collection, confirm date range: '-617905000 to -1601050-01-01'.  

Data we should add to the test set:
- [ ] No time range (in normal fields) 
- [ ] no spatial bounding or thumbnail

Description Tab
- [x] Thumbnail image (most everything has these)
- [x] No thumbnail image but spatial bounding available
  - search Nikolski, the 2nd result should have a map only, in both collection result card and description tab
- [ ] Results with no spatial bounding & no thumbnail show world map
  - TBD?
- [ ] Description 

Matching Files (Granule View)
- [x] Map rendering & data types
    - Search `ghrsst viirs ACSPO`. 2nd result should be "GHRSST GDS2 Level 2P Global Skin Sea Surface Temperature from the Visible Infrared Imaging Radiometer Suite (VIIRS) on the Suomi NPP satellite created by the NOAA Advanced Clear-Sky Processor for Ocean (ACSPO) (GDS version 2)"
    - Confirm Citation Info is present and identifier value is 'gov.noaa.nodc:GHRSST-VIIRS_NPP-OSPO-L2P'.
    - On Matching Files/granule view page, multiple granules with a variety of bounding boxes appear. Confirm in search request total count in 29.
    - Access Protocols show Download, FTP, OPeNDAP, THREDDS and Web
    - Show all granules. Look for granule with fileIdentifier of 'GHRSST-VIIRS_NPP-OSPO-L2P-v2.4.20151225190000-OSPO-L2P_GHRSST-SSTskin-VIIRS_NPP-ACSPO_V2.40-v02.0-fv01.0.nc' (helps to find on page '190' as this will be the only match). Confirm in search request response that parentIdentifier value is 'doi:10.7289/V5PR7SX5'.
- [x] Filtering granules -- time
    - NOTE: this time filter will fail because we're no longer searching the flattened granules, and unconstrained end dates are a known issue with how we filter time
    - Search `co-ops`
    - Open collection and go to 'Matching Files' tab. Search request shows 22 total granules matching.
    - Apply time filter to search, filtering between 2016-12-01 and 2016-12-31. 
    - TBD for finishing granule view (current granule search always drops filters): Open collection and go to 'Matching Files' tab again. Search request now shows 10 total granules matching.
- [x] Filtering granules -- space
    - Follow first two steps from above.
    - Apply spatial filter to search with a bounding box enclosed around Hawaii.
    - Open collection and go to 'Matching Files' tab again. Search request now shows `TBD` total granules matching.

Access Tab
- [x] Confirm 3 rows in table of this tab -- Information, Download Data, and Distribution Formats

#### Text Search Errors

- [x] entering with a blank text search field will result in an error message
- [x] starting a search with an asterisk '*' or question mark '?' will result in a corresponding error message
- [x] using an escape character \\ in the search field will result in a parsing error

#### Spatial Search Errors

- [x] entering invalid bounding box coordinates, for example, West: -191, South: 90, East: 90, North: 90, will result in a relevant error message upon hitting the "Apply" button
- [x] leaving coordinates blank, for example, West: -180, South: *empty*, East: *empty*, North: *empty*, will result in a relevant error message upon hitting the "Apply" button
- [x] entering a word 'foo' instead of a value

### Accessibility and 508 compliance

- [x] Run Chrome plugin WAVE (Web Accessibility Evaluation Tool) and check for errors on:
  - landing page
  - main site (search header, left filter menu, results view, details views, about page, help page)
  - 508 search page (to be removed)
  - 508 results page (to be removed)

- [ ] Run screen reader software in a Windows VM environment
  - TBD

## Code verification

- [ ] update libraries to the latest, if possible
- [ ] Run retire -p on client code [Retire JS](https://retirejs.github.io/retire.js/)
- [ ] OWASP - Run /gradlew dependencyCheckAnalyze --info
- [ ] Ensure that included images are compressed in the git repo

**Comment by zebdelk** [comment]
- landing page topic buttons - bigger on hover is buggy on safari and IE

**Comment by zebdelk** [comment]
Instructions "Open GHRSST ODYSSEA collection (should be second result). Bounding coordinates read: 'Bounding box covering -18.5°, 30°, 36.5°, 46.5° (W, N, E, S).'" might not be accurate - I suspect the record has a tied DSMM score, so exact ordering may not be known.

**Comment by zebdelk** [comment]
video tab is not very accessible - both the list items for videos are strange, and the video plays (but has no sound) - and worse, steals focus and doesn't seem to give it back.

**Comment by zebdelk** [comment]
We should show the doi as a link in the collection details (under "identifiers" instead of "identifier") or doi: none

**Comment by zebdelk** [comment]
Ran into the bug with identical rankings and next-page request on the granules tab, and it might be a more significant bug there for collections with around 30 granules (hit it multiple tries with the GRHSST VIIRS example). Additionally: it causes a bug with the "show more results" button, since it sees 28/29 loaded and always tries to load more (by going to result 40-60, then 60-80, and never being able to complete the load with all data)

**Comment by zebdelk** [comment]
"using an escape character \ in the search field will result in a parsing error" doesn't seem to be an issue?
I tried `co\-ops` and `co\n-ops` and got the same results as with `co-ops`

**Comment by zebdelk** [comment]
508 automated (WAVE):

- [ ] contrast issues:
  - it looks like white text on our lighter-blue theme color (space and time filters) is still an issue, but our new styling has resolved the other ones.
  - details page, white on the medium blue
  - link colors
  - granules list - some of the badge colors
- [ ] ERROR - detail view has errors on the tabs from multiple form labels

**Comment by zebdelk** [comment]
Checked off discovered issues that we fixed for the release candidate and wrote up stories in the backlog to cover other issues.
