### ISSUE TITLE
EPIC: UI Tweaks

### ISSUE THREAD

**Issue by zebdelk** [cedardevs/onestop#563]
- [ ] Collection detail: 'back to search' breadcrumb (parent of #443)
- [ ] Matching Files view: breadcrumbs (parent of #446)
- [ ] reiterating the citation info /collection title at the top of the granule file list?
- [ ] Move Download Data section above Information on access tab (parent of #556)
- [ ] Flip tab color selected tab is blue, non selected white

Media Current 2.0 rollover tasks
- [ ] Search result page: add list view toggle (parent of #682)
- [ ] Featured Data sets (parent of #532)
- [ ] Cleanup of UI (Parent of #627)

**Comment by dneufeldcu** [comment]
- Reiterating the citation info /collection title at the top of the granule file list?  Why??  Has anybody requested this?
