### ISSUE TITLE
API versioning

### ISSUE THREAD

**Issue by zebdelk** [cedardevs/onestop#583]
To support external partners using the api (such as for thin clients), we should have some sort of versioning scheme.

The main goals are to communicate breaking api changes. Ideally, this would be in a rolling fashion that would still support former versions of the api and marking those deprecated to encourage consumers of that api version to upgrade.

At minimum, it would make it clear to api consumers that things are not working because a new api has been deployed and the version they are using is no longer supported, instead of api changes happening invisibly.

The api version only needs to change when breaking changes are made (for example, defaulting to summary information instead of full documents would have been a case of this) but not purely additive changes.

All the api endpoints should have the version number in them, such as:

version today:
- /api

version 1:
- v1/api

### Tasks
- [ ] Add v1 api endpoint
- [ ] Consider versioning strategy and checklist of things to update when api version changes
  - eg: hosting multiple openapi specs
- [ ] Consider establish v1 endpoint for API in parallel to non-versioned API
