### ISSUE TITLE
EPIC: Login.gov initial implementation and design

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#611]
- [x] SAML or OpenId authentication works (Parent of #612)
- [ ] Saved search UI mockups for authenticated user workflows (Parent of #610)
- [ ] Rank dataset UI mockups (Parent of #613)
- [ ] Implement saved search UI worklow
- [ ] Implement rank dataset workflow

Notes from sprint review discussion on 5/23/2018
https://docs.google.com/document/d/1mwicO6JJXTvEFArDnbqaesHqHFOpHY9uxm97sshYhag/edit?usp=sharing

*CAPTURING THIS INFORMATION IN OVERALL LOGIN EPIC*
