### ISSUE TITLE
EPIC: Tech Debt

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#630]
- [ ] test improvement (Parent of #460)
- [x] Blank query bug (Parent of #528)
- [x] Backslash should be handled (Parent of #278)
