### ISSUE TITLE
EPIC: UI Design for User Preferences

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#636]
## Context
With the ability to log in from ICAM (employee w/role) or login.gov (anonymous public user), the OneStop UI may be improved for saving user-specific settings. For now, we are not considering a persistent database, so these features should persist as long as the session and cached information exist. We can consider the ability to persist this data later.

## Acceptance Criteria

Depends on #697

- [ ] Rank dataset UI mockups (Parent of #613)
- [ ] Font preference (Parent of #663)
- [ ] Color preference (Parent of #664)
- [ ] Contrast preference (Parent of #665)
