### ISSUE TITLE
EPIC: Design and Build Extract UI Changes

### ISSUE THREAD

**Issue by forgo** [cedardevs/onestop#641]
## Context
First we'll approach this with downloading in the browser vs. a middle-ware zip & ship.

## User Stories
-   As a user, I want to be able to select granules for download and submit an order so that I don't have to manually download each file.
- As a user I want to enter my email address after click the order button so that I can be notified once my granule files order is available for pick-up.

## Assumptions
- Assumption that HTTP link (download property in metadata) 
- Assumption max 100 downloads

## Acceptance Criteria
- [x] wireframe select granules (Parent of #651)
- [x] wireframe shopping cart (Parent of #652)
- [x] feature toggle UI (Parent of #693)
- [x] discuss and generate tasks from CA wireframing (Parent of #653)
- [x] UI: Select granules for download (Parent of #638)
- [x] UI: Header link to shopping cart (Parent of #683)
- [x] UI: Create cart page (URL/route) (Parent of #684)
- [x] UI: display file cards in cart context (Parent of #685)
- [x] local storage of selected granule/filters (Parent of #722)
- [x] WGET script (Parent of #759)

**Comment by forgo** [comment]
- [ ] UI updates to allow user selection of granules (Parent of #638)
- [ ] UI updates to capture email address (Parent of #639)
