### ISSUE TITLE
EPIC: Autocomplete Search Suggestions

### ISSUE THREAD

**Issue by rongxanh88** [cedardevs/onestop#648]
- [ ] Suggestions populate search field (Parent of #647)
- [ ] Suggestions use trending data (Parent of #646)
- [ ] Suggestions Wireframe (Parent of #645)
- [ ] Suggestions based on search history (Parent of #644)
