### ISSUE TITLE
EPIC: Geometric Region Named Search / Suggestions

### ISSUE THREAD

**Issue by CoopTang** [cedardevs/onestop#649]
##User Statement
As a user, I want to filter based on regions such as "Mediterranean", "Alaska, etc.

##Acceptance Critera
- [ ] Text box searches apply appropriate filters for regions
- [ ] Filter based on 'region' keyword
- [ ] Swagger doc API changes
