### ISSUE TITLE
EPIC: Time Filter Enhancement - API

### ISSUE THREAD

**Issue by rongxanh88** [cedardevs/onestop#660]
A Time Filter will enhance the UI/UX for OneStop.

- [x] ~Collections with no end date (Parent of #657)~
- [x] Time Filter API Supports INTERSECTS, CONTAINS, WITHIN, DISJOINT relation operators (Parent of #656)
- [x] Time Filter API swagger docs (Parent of #655)
- [x] Paleo date filter added to API (parent of #793)
- [x] Update wiki (parent of #833)
