### ISSUE TITLE
EPIC: Saved User Searches

### ISSUE THREAD

**Issue by zebdelk** [cedardevs/onestop#662]
## Context

We want to provide useful features to users who are logged in. Being able to save ("bookmark") complex but important searches for future reference is a way to help users.

## User Stories

- [ ] As a logged in user, I can bookmark important searches.
- [ ] As a logged in user, I can perform basic CRUD operations on my bookmarked searches.
- [ ] As a logged in user, I can easily redo a bookmarked search.

## Acceptance Criteria

Depends on #697

- [ ] saved searches wireframes (Parent of #610)
- [ ] user saved search api (Parent of #673)
- [ ] the collection results page has a Bookmark Search option (Parent of #674)
- [ ] Bookmarked searches appear on the home page (Parent of #675)
- [ ] Bookmarked searches view (Parent of #676)

**Comment by dneufeldcu** [comment]
Duplicate #1121
