### ISSUE TITLE
EPIC: Deploy ICAM login feature to test env

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#694]
## Context
Today metadata loading occurs from a script where a single user is able to run that script, and authentication is handled via basicAuth configured in Apache.

*Notes from sprint review discussion on 5/23/2018*
https://docs.google.com/document/d/1mwicO6JJXTvEFArDnbqaesHqHFOpHY9uxm97sshYhag/edit?usp=sharing

## User Stories

- [ ] As a 'logged-in' user (via ICAM with the role of METADATA_CURATOR), I want to know when I have successfully loaded metadata via a response.

## Reference
https://docs.google.com/document/d/10Bh1VVIZzzebhG5njhRvP5vhNkTMG0kQnT0AcNW3oLM/edit

## MVP
A single user is able to authenticate with ICAM and be authorized to update the metadata using email/pwd. In general, assume email is the main source of identification of the user.

## Acceptance Criteria

- [x] Prettify upload form (Parent of #712)
- [x] Move SAML idp to yml (Parent of #695)
- [x] Complete Security documentation (Parent of #696)
