### ISSUE TITLE
EPIC: Postgres Deployment (dev/test)

### ISSUE THREAD

**Issue by zebdelk** [cedardevs/onestop#697]
## Context
Several new features that are in progress/planned require a storage tier. We expect to be able to use Postgres in production, so we need to set it up in our dev environment.

## User Stories
- [ ] As a developer, I can run postgres locally
- [ ] As a developer, I can use postgres on sciapps

## Acceptance Criteria
- [ ] Include Postgres in skaffold for local development (Parent of #698)
- [ ] Deploy Postgres to sciapps (Parent of #699)

## TODO
- [ ] create an epic for updating featured datasets

**Comment by dneufeldcu** [comment]
Guidance from ITB to use Oracle for now.

**Comment by ajakz** [comment]
OBE related to User module, closing
