### ISSUE TITLE
EPIC: Login.gov

### ISSUE THREAD

**Issue by mcquinne** [cedardevs/onestop#709]
# User Stories

- [x] As a OneStop user, I want to easily trigger a login via the Onestop UI and know that I succeeded ( Parent of #737 )

- [x] As a OneStop user, I want to easily log out of the OneStop UI and know I have succeeded. ( Parent of #738 )

- [x] login.gov with OpenID ( Parent of #723 )

- [x] Nonce clean-up  ( Parent of #769 )
- [x] Deployed to sciapps

# Assumptions
- This is a search-api related concern
