### ISSUE TITLE
Generate sitemap as a file

### ISSUE THREAD

**Issue by forgo** [cedardevs/onestop#726]
### Summary
<table>
  <tr>
    <td><b>As an</b></td>
    <td>external search engine</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       list all collections
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>fully index the onestop site</td>
  </tr>
</table>

### Description
External search engines like Google need to be able to harvest the data collections in OneStop so that they reflect OneStop pages in their searches. Currently we support a `sitemap.xml` via an [endpoint in the Search API](https://github.com/cedardevs/onestop/blob/master/search/src/main/groovy/org/cedar/onestop/api/search/controller/SitemapController.groovy#L41) which dynamically generates the sitemap by querying a special Elasticsearch index which in turn is updated periodically by a reindex job.

Instead, we'd like to simplify the process by periodically generating the sitemap as a file. This is the first step in that process.

### Tasks
- [x] Create a new subproject to hold the generator
- [x] Decide on a language:
    - Groovy/Java: Opportunity to share code w/ API to host new collection formats, ES Java library
    - Javascript/Typescript: Can leverage existing json-ld code eventually
    - ~Python: Simplicity~ 
- [x] Use Elasticsearch `search_after` pagination to loop through all collections and generate output (see [Paginate Search Results](https://www.elastic.co/guide/en/elasticsearch/reference/7.x/paginate-search-results.html#search-after))
    - Or maybe using `search_after` support built into our search api now is even cleaner?
- [x] Output should conform to the [sitemap protocol](https://www.sitemaps.org/protocol.html)
    - ignore `<priority>` because they're all the same?
    - use `<changefreq>monthly</changefreq>`?
    - if necessary, produce multiple sitemaps and a corresponding [sitemap index file](https://www.sitemaps.org/protocol.html#index)
- [x] Accepts runtime parameters as args and/or env vars and/or config file (ES URL/credentials, **collection base URL**, etc.)
- [ ] Determine file outputs location (Follow-on story)

**Comment by mcquinne** [comment]
oops

**Comment by uniyalVJ** [comment]
Sitemap Generator Meeting Vijay-Chris-Evan

- Decided to not use Python

- Utilizing JavaScript with existing JSONLD code or Java so Search API does JSONLD transformation

-  Utilizing searchAfter parameter to prevent updates to Search Engine from changing the order of our results page while we generate them.

- Making our root sitemap XML file a list of sub-indexed pages can prevent our root file from getting to large. Data cap of 50mb on individual sitemap pages.

- Creating a new JS application script that will query our search API, churn through collections(pagination), & build an XML file. 

- **CRON** job with docker/kubernetes. (Want to generate XML/JSONLD files periodically)

- **Future:** Add Support for searchAfter in CLI since that'll do queries and once we're in cloud with multiple satellites we will receive granuals every second meaning the "Point in Time" ID is better for keeping track of order with a constantly updating collection.

**Comment by uniyalVJ** [comment]
Credit to **@mcquinne / Picasso** for the diagram. Current envisioned state of how OneStop will function with Sitemap Generator. 
![Sitemap 12-14-2020.png](https://images.zenhubusercontent.com/5fc7ceb73fc13464278725db/ce0fce64-6ff5-40a9-8876-cb0be14432ba)

**Comment by uniyalVJ** [comment]
Added proper time stamps in W3 compliance

**Comment by uniyalVJ** [comment]
Story split into creating unit tests for TDD. Developing tests for collection crawler & pagination.

**Comment by uniyalVJ** [comment]
Unit testing & helper methods to process the body done. Currently working on the crawler recursion with api pagination. Getting a demo ready for other departments interested in the sitemap generator. Refactored generator to be more scalable/modular once other departments showed interest.

**Comment by uniyalVJ** [comment]
Demo ready, crawler recursion works, & just need to gzip files to generate sitemap index. More complicated part of story with few solutions but understand way forward use a git sitemap library.

**Comment by dneufeldcu** [comment]
Last step generate index to file

**Comment by uniyalVJ** [comment]
Can generate local sitemap index file with gzipped sitemap files off of local test repo. Next step is to get it working vs cedardevs.org & clean up before release. Story evolved into a lot of different steps throughout the process:


[X] Changed sorting approach from stagedDate & beginDate as docs showed not all collections have a beginDate.
[X] Develop unit tests & learn JES
[X] Isolate all helper methods to process the body & convert to XML into transformUtils.js for modular TDD design
[X] More clear concise unit tests for helper methods
[X] Research body.data docs to understand how granuals are work and can be tested
[X] Handle pagination within generator (Used crawlerCollection method)
[X] Recursively iterate through entire collection's pages & Print to file
[X] Module.Exports circular dependency loop created from modular exporting design to other files. Lots of debugging
[X] 1st Demo - Good but refocused on making it more scalable.
[X] Mock payloads inside transformUtils.test.js to understand input/output better & test outside of local repo
[X] Refactor tests to incorporate mocked payload
[X] Approached sitemapIndex & had pair programming sessions with Chris on how to move forward (big design choice)
[X] Incorporate sitemap library on github (sizeable refactor of all files)
[X] Create gzipped sitemap files
[X] Create sitemapIndex files that point to the sitemap files
[X] Demo 2 Sprint Review 2/10/2021
[ ] Test XML generation against cedardevs.org (Debugging required)
[ ] Clean up

Future tasks for story mainly include:
[ ] JSON LD file generation
[ ] Hosting sitemap XML & JSON
[ ] Scaling use of code outside of just onestop (other departments)
[ ] CRON job + Dockerfile (Script should run daily to generate XML/JSON)

**Comment by uniyalVJ** [comment]
UPDATE: [ ] Test XML generation against cedardevs.org (Debugging required)

Fetch library used to make API Post calls was deprecated. Swapped to Axios. Lot of documentation diving but migrated it successfully. Axios has nuance regarding how to structure the response & the response body you get back that required a decent refactor. Took it a step further and did a larger refactor that changed how I approach generator.js recursion making it a lot cleaner. 



Drew a diagram detailing my pre-refactor components, how they worked, and the problems I was facing regarding the refactor. Helped me design an ideal solution using closures inside of getCollectionPage().

![sitemapGenDrawing.png](https://images.zenhubusercontent.com/5fc7ceb73fc13464278725db/3668178b-0c11-4f26-bca4-1b799945dfa5)

Next steps:
Finish recursive refactor (axios already working)
Test sitemap XML generation
Test against cedar devs
Test against Data.Noaa.Gov

**Comment by uniyalVJ** [comment]
Sitemap files fully generate locally.


Testing against cedar devs & data.noaa.gov are for future story progress.


Story continued on:

Sitemap Integration#1464 https://app.zenhub.com/workspaces/onestop-5caf5b03e94905314d5883a8/issues/cedardevs/onestop/1464

Project Open Data output#1412 https://app.zenhub.com/workspaces/onestop-5caf5b03e94905314d5883a8/issues/cedardevs/onestop/1412
