### ISSUE TITLE
Determine Granule vs Collection

### ISSUE THREAD

**Issue by forgo** [cedardevs/onestop#731]
Anna brought to our attention that data scientists have an expected behavior with distinguishing a granule vs a collection that is more consistent with other line-offices:

```
if (hierarchyLevelName != granule) {
  -> collection
}
else {
  if (parentIdentifier != exists) {
    -> error
  }
  else {
    -> granule
  }
}
```

### Tasks
- [x] Update logic for IdentificationAnalysis (schemas)
- [x] Update Indexer validation logic (onestop)
- [x] Update Indexer ParsedRecord --> Elasticsearch document logic (onestop) 
- [x] Update collection mappings and pipelines to allow parentIdentifier field (onestop)
