### ISSUE TITLE
Select granules (for cart) based on search filters

### ISSUE THREAD

**Issue by zebdelk** [cedardevs/onestop#736]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>user of OneStop who wants to order data</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       select non-duplicated granules for the cart feature based on what exists in the collection filter, granule filter, or combination thereof
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>quickly collect and order data that is relevant to my needs</td>
  </tr>
</table>

### Tasks
- [x] [DISCUSS] remove "Add to Cart" checkbox from each granule (can't we still keep this as long as we ensure no duplication)?
- [x] [DISCUSS] display summary of a granule search (filters, number of results) instead of individual granule cards on Cart page (we could still select individual granules and group them by collection or in their own "one-of" section if they didn't fall into an applied filter)
- [x] determine ES friendly threshold for in-memory delivery of results (5000 - 10000?)
- [x] granule list view has an Add Search Results to Cart button at the top, which is disabled if total results exceeds threshold
- [x] deliver URL results using in-memory ES for all results in search

### Potential
- [ ] [DISCUSS] UI somewhere contains ability to "apply collection filter to cart", "apply granule filter to cart", and "apply collection and granule filter" to cart if they are within delivery threshold of total results

**Comment by StrayCat1** [comment]
It seems there need to be discussion around what exactly the requirements for this story will be.
