### ISSUE TITLE
EPIC: Updated MediaCurrent Recommendations on Accessibility

### ISSUE THREAD

**Issue by zebdelk** [cedardevs/onestop#794]
**Summary**
<table>
  <tr>
    <td><b>As a</b></td>
    <td>developer of OneStop</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>highlight OneStop's accessibility support</td>
  </tr>
  <tr>
    <td><b>So that</b></td>
    <td>all of my users are able to find NOAA's earth science data</td>
  </tr>
</table>

### Description
MediaCurrent's latest accessibility report gave us a list of requirements and suggestions.

### Tasks
# A & AA findings (Required to meet 508)
- [x] Orphaned Form Label (parent of #795)
- [x] Missing label on search field (parent of #796)
- [x] Hover Contrast (parent of #797)
- [x] Location Filter Focus (parent of #798)
- [x] NOAA Logo link text unclear (parent of #799)
- [x] Search Results Pages - context and order (parent of #800)
- [x] After A & AA are complete, contact MediaCurrent for statement to put on Accessibility Statement of page, indicating the site was reviewed by external partner on given date. From Ken C. ~"We have completed a 3rd party review that the site is Level AA accessibility for all of our features. We will continue to make improvements across our entire site aiming for AAA compliance where possible."

# AAA findings (optional - quick wins)
- [ ] link contrast (parent of #801)
- [ ] Maximum Line Length and Line Spacing (parent of #802)

**Comment by dneufeldcu** [comment]
Moving AAA stories to follow-on 508 epic
