### ISSUE TITLE
EPIC: Updated MediaCurrent Usability Recommendations

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#806]
- [x] Add improved mobile support with meta tag (Parent of #813)
- [ ] Home page updates (Parent of #807)
- [ ] Keyword UI changes (Parent of #808)
- [ ] Search result improvements (Parent of #809)
- [ ] Collection detail enhancements (Parent of #810)
- [ ] Abstract text formatting (Parent of #811)
- [x] Improve error handling, custom 404 (Parent of #812)
