### ISSUE TITLE
EPIC: Time Filter Enhancement - UI

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#814]
A Time Filter will enhance the UI/UX for OneStop.

- [ ]  Wireframe (Parent of #658)
- [ ] Time filter on UI supports intersects and within operators (parent of #792)
- [ ] Paleo date time searches in UI (Parent of #654)
