### ISSUE TITLE
EPIC Microservices: Split API into a set of microservices that cover existing functionality, can easily integrate with future microservices, and are adaptable to underlying architecture changes.

### ISSUE THREAD

**Issue by ajakz** [cedardevs/onestop#83]
This epic issue represents the microservices feature branch work, which will encompass multiple issues before it's ready to be merged via pull request into ~master~ develop:
- [x] Separate API into distinct microservices, maintaining current functionality initially (issue #47)
- [x] Remove cross-API class dependencies from integration tests (issue #47)
- [ ] Refactoring APIs to be ready for a metadata database instead of a staging index (issues TBD)
- [ ] API documentation (issue #51)
- [ ] Fix gradle build scripts (issue TBD)

Efforts should be made to keep this branch as up-to-date as possible with ~master~ develop, and incorporate any API bug fixes/enhancements that come along until this pull request is complete.

Bugs included: 
- [x] #67 Metadata endpoints
- [x] #69 Fix sure check
- [ ] #73 
- [ ] #74 
- [ ] TBD

Enhancements included:
- [ ] #66 Configurable SSL connection to elasticsearch
- [ ] #97 multinode transport client connections
- [ ] #92 support isGlobal 
- [ ] TBD

**Comment by ajakz** [comment]
Can't address #73 without a refactor -- resolved on master by ensuring staging index exists (and if not, properly building it with the correct mappings), which can't be done right now without replicating code or creating a dependency between APIs.

The microservices should treat the search index and staging index as separate resources so that when a metadata database (or something that's at least not the staging index...) exists, the transition to it is easier.

**Comment by ajakz** [comment]
Noting here so hopefully it's not forgotten when we work on the microservices EPIC again --
In the "manager" app, we should have a function to re-ingest GCMD keywords periodically (currently hard-coded top level science & location keywords)

**Comment by ajakz** [comment]
Work on this epic was done in concert with the Elasticsearch upgrade work (#48). 

Main related issues are: #169 and #172 with #191 to improve gradle build.
