### ISSUE TITLE
EPIC: Granule filtering

### ISSUE THREAD

**Issue by zebdelk** [cedardevs/onestop#837]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>user of OneStop's UI</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       <p>find subsets of granules I'm interested in based on:</p>
       <ul>
         <li>geometry</li><li>time</li><li>filetype</li><li>download protocol</li>
       </ul>
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>more intuitively and easily navigate to data I care about</td>
  </tr>
</table>

### Sprint
TBD - TBD

### Assumptions
- we have refactored the UI code to make separating granule-specific filtering and log **very** clearly distinct (READY TO REVIEW) 

### Tasks
- [ ] Clean up 508 (if applicable) (Parent of #733)
- [x] UI: Granule search filtering capability (Parent of #447)
- [ ] UI: Remove file from cart (if applicable)  (Parent of #686)
- [x] Select granules based on filters (Parent of #736)
- [x] granule specific facets and filters (Parent of #839)
- [x] granule filter styling (Parent of #921)
- [ ] granule filter enhancements (Parent of #920)
- [x] better load indicator handling (Parent of #922)
- [x] granule map filter bugs (Parent of #923)
- [x] granule handling on details page efficiency / enhancements  (Parent of #925)
- [x] DESIGN: query filter for granule search (Parent of #926)
### References
<table>
  <tr>
    <td><b>Point of contact</b></td>
    <td>{name|email|room#|phone}</td>
  </tr>
  <tr>
    <td><b>Doc, Spreadsheet, etc.</b></td>
    <td>{link}</td>
  </tr>
</table>
