### ISSUE TITLE
EPIC: Hardening - ideas

### ISSUE THREAD

**Issue by zebdelk** [cedardevs/onestop#855]
### Summary
<table>
  <tr>
    <td><b>As an</b></td>
    <td>active maintainer of the OneStop project</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       <p>improve OneStop's:</p>
       <ul>
         <li>Build & Deployment</li>
         <li>Unit & Integration Tests</li>
         <li>Performance & Optimization</li>
         <li>Code Quality</li>
         <li>Error Handling</li>
         <li>Documentation</li>
         <li>UI & JavaScript</li>
         <li>Miscellaneous</li>
       </ul>
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>confidently promote OneStop and improve productivity/morale</td>
  </tr>
</table>

### Sprints
**Current HIP:** April 14 - April 26
**Next HIP:** ?

### Assumptions
- Unless otherwise prioritized, **tasks in this epic are for HIP sprints only**
- **New tasks in this epic should only be created by consensus**
- Maintaining a well-polished product is a **continuous effort**

### HIP Priorities
1. TBD
2. TBD

### Issues Created
  - [ ] #

### Build & Deployment
- CircleCI
  - [ ] further caching improvements between builds/workflows/jobs
- Gradle
  - [ ] standardize individual build tasks among independent modules
  - [ ] clean up high-level build tasks and create more generic Gradle tasks to perform common operations with latest OneStop ecosystem
  - [ ] ensure we are using up-to-date practices in Gradle scripts (removing deprecations, etc)
- `cu-server-admin`
  - [ ] sciapps: admin module should have ingress with basic auth, ansible should use that for os-load instead of copying tar
- Federal Alignment
  - [ ] use AJP to talk to tomcat from the client container, do SSL through ingress
- Helm
  - [ ] helm template test connections - are there any useful things we want to do there, or just skip having those?

### Unit & Integration Tests
  - [ ] trending feature has a config that is in one directory, but belongs to a different package. move the file so that's consistent.

### Performance & Optimization
- improve response times of browser client
  - [ ] profile client
  - [ ] code splitting
  - [ ] reduce the size of our JS bundle via image/icon compression, not importing monolithic library objects when not used (i18n, lodash, moment, etc)
  - [ ] image-caching service (is this even feasible in prod if we had the time to do it?)

### Code Quality
- [ ] don't do crazy logs (unless with TRACE) that output insane amounts of data (for example: upload full XML content)
- [ ] eliminate unused trending search feature

### Error Handling
- [ ] client should give at least some context when it encounters major errors (use a strict table of custom error codes that can be documented and have user-friendly messages in addition to tech-friendly logs/console)

### Documentation
- [ ] Create docs directory parallel to PSI, make clear practices of where to find docs for various dev issues (eg: explaining the test cases chosen for a complicated test, or what the edge cases are for, when the tests are not self describing)
  - [ ] api-search has a readme next to some integration test data. move this to the right place in the general docs area, and add a comment in the integration test code to indicate where that doc lives and to keep it in sync with the test.
- [ ] opensource startup style docs (requirements, start commands)
- [ ] openapi spec for admin endpoints

### UI & JavaScript
- [ ] upgrade React
- [ ] more intelligent spinners ("net" spinner in common location like header, granular spinner for specific components/routes, animated spinners -- not just static "loading...")
- [ ] add PropTypes too all components
- [ ] adhere to latest React lifecycle practices
- [ ] storyboarding

### Miscellaneous
- [ ] noticed admin endpoint to recreate sitemap index (analogous to recreating staging or search indices) is missing. add that
- [ ] index / homepage of client is calling collection endpoint. Why? It doesn't seem obvious that it should be. (I think this is essentially the total collection & granules query used on the "Catalog Information" section of the "About" page -Elliott)
- [ ] consider changing ES service logs so that an error isn't reported when ensuring indices (need a little more context before we create a task out of this -Elliott)
- [ ] put google dev console ownership validation file back in place, but do it for all of sciapps instead of just onestop this time
