### ISSUE TITLE
Add services to ES index mappings

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#860]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>metadata content developer and user of OneStop</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       quickly and easily locate services associated with a collection or granule metadata record,</td>
  </tr>
  <tr>
    <td><b>so that I can</b></td>
    <td>access the most up date information available for this dataset.</td>
  </tr>
</table>

### Description
Specifically, we want to support links coming from the ISO service metadata fields that NCEI has.

/gmi:MI_Metadata/gmd:identificationInfo/srv:SV_ServiceIdentification/srv:containsOperations/srv:SV_OperationMetadata/srv:connectPoint/gmd:CI_OnlineResource/.... 

SV_ServiceIdentification, containsOperations and connectPoint elements are repeatable.

Example: 
[Metadata record](https://ferret.pmel.noaa.gov/uafwaf/iso/granule/thredds_dodsC_ersstv3Agg.xml)

### Tasks
- [X] Review fields with Anna (metadata experts) determine what is stored
- [x] Update metadata parsing code to retrieve data from xPath and load into ElasticSearch
- [x] Add `serviceLinks` to collection and granule indices, schemas, and pipelines
- [x] Capture story on PSI board
- [ ] Update the [mapping documentation](https://github.com/cedardevs/onestop/blob/master/docs/design/iso-indexing-mapping.md#services) to indicate how services are now parsed

**Comment by StrayCat1** [comment]
These changes include supporting service metadata for collections and granules through api-metadata and api-search, but do not include changes to the client. 

Parse and index 
https://github.com/cedardevs/onestop/commit/87264fb11050c629a8edbafcfcc1e8142d218de1

Update indices and pipelines
https://github.com/cedardevs/onestop/commit/059073ce1c57814e7e397aaa6fe532dfcde20831

Update e2e's (still can't get to run!)
https://github.com/cedardevs/onestop/commit/491d459f37ee73bbca083fe4376b50d83f83d571

Update api-search integration test
https://github.com/cedardevs/onestop/commit/bac26a27852cf9c368f3c7cc8fbe2f58a688515c

Still to do:
- [ ] get e2e's running
- [ ] create pull request

**Comment by StrayCat1** [comment]
Created PSI story- 
https://app.zenhub.com/workspaces/psi-5cad1a9f5c8c32288a938748/issues/cedardevs/psi/313

**Comment by StrayCat1** [comment]
https://github.com/cedardevs/onestop/pull/885

**Comment by zebdelk** [comment]
This issue is blocked by refactoring a common library out of PSI

**Comment by StrayCat1** [comment]
ES5- 
Collection staging -  https://github.com/cedardevs/onestop/blob/897-sharedParsingUtils/elastic-common/src/main/resources/mappings/ES5/staging_collectionIndex.json#L619

Collection search -  https://github.com/cedardevs/onestop/blob/897-sharedParsingUtils/elastic-common/src/main/resources/mappings/ES5/search_collectionIndex.json#L264

Granule staging -  https://github.com/cedardevs/onestop/blob/897-sharedParsingUtils/elastic-common/src/main/resources/mappings/ES5/staging_granuleIndex.json#L622

Granule search - https://github.com/cedardevs/onestop/blob/897-sharedParsingUtils/elastic-common/src/main/resources/mappings/ES5/search_granuleIndex.json#L147

Flattened granule search - https://github.com/cedardevs/onestop/blob/897-sharedParsingUtils/elastic-common/src/main/resources/mappings/ES5/search_flattened_granuleIndex.json#L270

ES6- 
Collection staging -  https://github.com/cedardevs/onestop/blob/897-sharedParsingUtils/elastic-common/src/main/resources/mappings/ES6/staging_collectionIndex.json#L616

Collection search -  https://github.com/cedardevs/onestop/blob/897-sharedParsingUtils/elastic-common/src/main/resources/mappings/ES6/search_collectionIndex.json#L261

Granule staging -  https://github.com/cedardevs/onestop/blob/897-sharedParsingUtils/elastic-common/src/main/resources/mappings/ES6/staging_granuleIndex.json#L619

Granule search - https://github.com/cedardevs/onestop/blob/897-sharedParsingUtils/elastic-common/src/main/resources/mappings/ES6/search_granuleIndex.json#L143
