### ISSUE TITLE
Update Sciapps configs to support ES6

### ISSUE THREAD

**Issue by forgo** [cedardevs/onestop#868]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>OneStop developer</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       keep our remote development server in sync with ES6
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>keep in sync with the known federally deployed version</td>
  </tr>
</table>

### Tasks
- [ ] ensure backward compatibility with ES5
- [ ] playbooks in cu-server-admin and deployment to sciapps.colorado.edu
- [ ] defaults our Elasticsearch version to ES6 moving forward
- [ ] there are no old ES versions lingering on sciapps

Should be done in parallel with other ES6 tasks to prevent any conflicts.

**Comment by StrayCat1** [comment]
This story and a newer one #913 were similar enough that I collapsed this one into . 913
