### ISSUE TITLE
Update Developer Defaults to ES6

### ISSUE THREAD

**Issue by forgo** [cedardevs/onestop#869]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>developer of OneStop</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       have my version of Elasticsearch default to the expected ES6 version
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>align with our deployment configuration as well as know my local builds are consistent with other developers</td>
  </tr>
</table>

### Tasks
- [x] skaffold changes
- [x] helm chart changes
- [x] search onestop project for image/version usage and keep consistent

**Comment by dneufeldcu** [comment]
- [ ] testing skaffolding changse
