### ISSUE TITLE
Drop version from war naming convention

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#878]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>jenkins build process</td>
  </tr>
  <tr>
    <td><b>I rely on</b></td>
    <td>
       a consistent naming convention to move built artifacts into deployment
    </td>
  </tr>
  <tr>
    <td><b>So that I have</b></td>
    <td>an automated process</td>
  </tr>
</table>

### Description
The gradle build job outputs war filenames that include version. This is problematic for automated deployment because it requires updating the jenkins job with each version change.

For example currently we build - onestop-search-2.1.0.war which can be simplified to onestop-search.war,  onestop-metadata-2.1.0.war to onestop-metadata.war, and onestop-client-2.1.0.tar.gz to onestop-client.tar.gz

### Tasks
- [ ] Change artifact name onestop-search-2.1.0.war to onestop-search.war
- [ ] Change artifact name onestop-metadata-2.1.0.war to onestop-metadata.war
- [ ] Change artifact name onestop-client-2.1.0.tar.gz to onestop-client.tar.gz
