### ISSUE TITLE
Requested upgrades to OneStop v2.1.1

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#904]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>reviewer</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       have the latest libraries in place
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>be confident in app sec</td>
  </tr>
</table>

## Tasks
Review security feedback via here: 
https://drive.google.com/file/d/1CwRZ2lKG_9SSTBnZgKA2ZdogVZiHCcm8/view?usp=sharing

Based on that feedback, here is a todo list- 
Code concerns- 
- [x] the ‘/metadata-form’ endpoint is not restricted to admins. Was this an oversight?
- [x] if yes, fix it
- [x] if not, explain why
- [x] Wouldn't this line secure it? https://github.com/cedardevs/onestop/blob/master/api-metadata/src/main/groovy/org.cedar.onestop.api.metadata/authorization/configs/SpringSecurityConfig.groovy#L47

Vulnerabilities
- [x] Bcprov-jdk15on 1.59 – CVE-2018-1000613 [critical], CVE-2018-1000180 [high] – can be
resolved by updating to 1.60 or higher.

Due this if it's a quick fix, otherwise wait.
- [x] guava 11.0.2 – CVE-2018-10247 [low] – recommended to upgrade to 24.1.1 or higher to
mitigate potential DoS vulnerabilities, but can be deferred if desired.

Time estimate: less than 1 day

**Comment by forgo** [comment]
The issue of `/metadata-form` was actually an oversight, we changed that endpoint so that it wouldn't conflict with other similarly named endpoints according to the last change there. Although the custom ICAM security filter used a regex `/\/metadata.*$/` which should catch this, we failed to add the following to the WebSecurityConfigurerAdapter:

`.antMatchers("/metadata-form").hasAuthority('ADMIN')`

whereas the existing rule that we probably assumed caught it was:

`.antMatchers("/metadata/**").hasAuthority('ADMIN')`

In other words, the POST endpoint for the upload form was secure from an ICAM authentication perspective, but it did not provide any authorization mechanism.

**Comment by forgo** [comment]
`org.bouncycastle:bcprov-jdk15on:1.59` is a downstream dependency of `org.opensaml:opensaml-saml-api:3.4.2`

the latest opensaml version we can upgrade to by directly using the following repository:
`maven { url "https://build.shibboleth.net/nexus/content/repositories/releases" }`

is `3.4.3`

When analyzing the downstream dependencies of upgrading opensaml related libraries, I found the resulting version of `org.bouncycastle:bcprov-jdk15on` is not actually changed to `1.6.0` or greater.

So I used gradles `dependencyResolution` to enforce the upgrade:

```
if (details.requested.group == 'org.bouncycastle' && details.requested.name == 'bcprov-jdk15on') {
  if (details.requested.version.startsWith('1.5') && details.requested.version <= '1.59') {
    details.useVersion '1.62'
    details.because 'fixes vulnerability in 1.5.x before 1.6'
  }
}
```

**Comment by forgo** [comment]
we're already overriding the `guava` dependency with this version in both APIs (is this an issue on the PSI project):

```
  // version to override another library's dependency to solve a CVE:
  compile 'com.google.guava:guava:27.0.1-jre'
```

I'm seeing us update to `27.0.1-jre` from `16.0.1` which should be far from the version `11` which the vulnerability references:
`com.google.guava:guava:16.0.1 -> 27.0.1-jre`
