### ISSUE TITLE
EPIC: Migration simulation on sciapps (ES6 + service reindex + rekey) 

### ISSUE THREAD

**Issue by StrayCat1** [cedardevs/onestop#912]
We need to deploy the changes for ES6 as well as the re-key

- [x] make image for api-metadata, and api-search based off the [sharedParsingUtils branch](https://github.com/cedardevs/onestop/tree/897-sharedParsingUtils) and publish to dockerhub 
- [x] before we deploy that, we want to make sure ES has some data in it (it should)
- [ ] run [Upgrade Assistant](https://www.elastic.co/guide/en/kibana/6.0/xpack-upgrade-assistant.html) 
- [x] deploy image to sciapps by modifying the image tag in api-search and metadata Deployments (this will allow us to easily roll back) 
- [x] make sure everything still works to confirm ES5 compatibility remains unchanged 
     - [x] search
     - [x] upload
     - [x] refresh
- [x] submit a collection to PSI that is already in the index. 
- [x] confirm that existing document is deleted and new document inserted
- [x] make sure collections and granules in search are updated
- [x] UPGRADE to ES6!
- [x] make sure everything still works 
     - [x] search
     - [x] upload
     - [x] refresh
- [x] try another re-key (upgrade to ES6 shouldn't change anything there) 

- [x] document all this as best we can

- [x] Parent of #913 : ES5 -> ES6 on sciapps + documentation
- [x] Parent of #916 : Inventory Manager re-key migration
- [x] Parent of #918 : ServiceLinks
