### ISSUE TITLE
ES5 index to ES6 index migration

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#913]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>metadata content developer and elasticsearch administrator</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       migrate the ES5 cluster to ES6
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>I don't have to reload millions of metadata records.</td>
  </tr>
</table>

### Tasks
- [x] Learn about ES migration strategies.
- [x] Document an approach for our partner on migration.
- [x] How will we do this in fed space (new hardware etc.)

Collapsing in an older story about migrating the ES cluster on sciapps- 
- [x] deploy code changes (image from sharedParsingUtils branch)
- [x] ensure backward compatibility with ES5
- [x] playbooks in cu-server-admin and deployment to sciapps.colorado.edu
- [x] defaults our Elasticsearch version to ES6 moving forward
- [x] there are no old ES versions lingering on sciapps
- [x] make sure everything still works
- [x] search
- [ ] upload
- [ ] refresh

**Comment by StrayCat1** [comment]
Kibana indices needed migrating 
```
curl -X PUT  http://es-elasticsearch:9200/.kibana/_settings -d '{"index.blocks.write": "true"}' -H "Content-Type:application/json"

{"acknowledged":true}
```

```
curl -X PUT "es-elasticsearch:9200/.kibana-6" -H 'Content-Type: application/json' -d'
{
  "settings" : {
    "number_of_shards" : 1,
    "index.mapper.dynamic": false
  },
  "mappings" : {
    "doc": {
      "properties": {
        "type": {
          "type": "keyword"
        },
        "updated_at": {
          "type": "date"
        },
        "config": {
          "properties": {
            "buildNum": {
              "type": "keyword"
            }
          }
        },
        "index-pattern": {
          "properties": {
            "fieldFormatMap": {
              "type": "text"
            },
            "fields": {
              "type": "text"
            },
            "intervalName": {
              "type": "keyword"
            },
            "notExpandable": {
              "type": "boolean"
            },
            "sourceFilters": {
              "type": "text"
            },
            "timeFieldName": {
              "type": "keyword"
            },
            "title": {
              "type": "text"
            }
          }
        },
        "visualization": {
          "properties": {
            "description": {
              "type": "text"
            },
            "kibanaSavedObjectMeta": {
              "properties": {
                "searchSourceJSON": {
                  "type": "text"
                }
              }
            },
            "savedSearchId": {
              "type": "keyword"
            },
            "title": {
              "type": "text"
            },
            "uiStateJSON": {
              "type": "text"
            },
            "version": {
              "type": "integer"
            },
            "visState": {
              "type": "text"
            }
          }
        },
        "search": {
          "properties": {
            "columns": {
              "type": "keyword"
            },
            "description": {
              "type": "text"
            },
            "hits": {
              "type": "integer"
            },
            "kibanaSavedObjectMeta": {
              "properties": {
                "searchSourceJSON": {
                  "type": "text"
                }
              }
            },
            "sort": {
              "type": "keyword"
            },
            "title": {
              "type": "text"
            },
            "version": {
              "type": "integer"
            }
          }
        },
        "dashboard": {
          "properties": {
            "description": {
              "type": "text"
            },
            "hits": {
              "type": "integer"
            },
            "kibanaSavedObjectMeta": {
              "properties": {
                "searchSourceJSON": {
                  "type": "text"
                }
              }
            },
            "optionsJSON": {
              "type": "text"
            },
            "panelsJSON": {
              "type": "text"
            },
            "refreshInterval": {
              "properties": {
                "display": {
                  "type": "keyword"
                },
                "pause": {
                  "type": "boolean"
                },
                "section": {
                  "type": "integer"
                },
                "value": {
                  "type": "integer"
                }
              }
            },
            "timeFrom": {
              "type": "keyword"
            },
            "timeRestore": {
              "type": "boolean"
            },
            "timeTo": {
              "type": "keyword"
            },
            "title": {
              "type": "text"
            },
            "uiStateJSON": {
              "type": "text"
            },
            "version": {
              "type": "integer"
            }
          }
        },
        "url": {
          "properties": {
            "accessCount": {
              "type": "long"
            },
            "accessDate": {
              "type": "date"
            },
            "createDate": {
              "type": "date"
            },
            "url": {
              "type": "text",
              "fields": {
                "keyword": {
                  "type": "keyword",
                  "ignore_above": 2048
                }
              }
            }
          }
        },
        "server": {
          "properties": {
            "uuid": {
              "type": "keyword"
            }
          }
        },
        "timelion-sheet": {
          "properties": {
            "description": {
              "type": "text"
            },
            "hits": {
              "type": "integer"
            },
            "kibanaSavedObjectMeta": {
              "properties": {
                "searchSourceJSON": {
                  "type": "text"
                }
              }
            },
            "timelion_chart_height": {
              "type": "integer"
            },
            "timelion_columns": {
              "type": "integer"
            },
            "timelion_interval": {
              "type": "keyword"
            },
            "timelion_other_interval": {
              "type": "keyword"
            },
            "timelion_rows": {
              "type": "integer"
            },
            "timelion_sheet": {
              "type": "text"
            },
            "title": {
              "type": "text"
            },
            "version": {
              "type": "integer"
            }
          }
        },
        "graph-workspace": {
          "properties": {
            "description": {
              "type": "text"
            },
            "kibanaSavedObjectMeta": {
              "properties": {
                "searchSourceJSON": {
                  "type": "text"
                }
              }
            },
            "numLinks": {
              "type": "integer"
            },
            "numVertices": {
              "type": "integer"
            },
            "title": {
              "type": "text"
            },
            "version": {
              "type": "integer"
            },
            "wsState": {
              "type": "text"
            }
          }
        }
      }
    }
  }
}
'
{"acknowledged":true,"shards_acknowledged":true,"index":".kibana-6"}
```

```
curl -X POST "es-elasticsearch:9200/_reindex" -H 'Content-Type: application/json' -d'
 {
   "source": {
     "index": ".kibana"
   },
   "dest": {
     "index": ".kibana-6"
   },
   "script": {
     "inline": "ctx._source = [ ctx._type : ctx._source ]; ctx._source.type = ctx._type; ctx._id = ctx._type + \":\" + ctx._id; ctx._type = \"doc\"; ",
     "lang": "painless"
   }
 }
 '
{"took":1248,"timed_out":false,"total":39,"updated":0,"created":39,"deleted":0,"batches":1,"version_conflicts":0,"noops":0,"retries":{"bulk":0,"search":0},"throttled_millis":0,"requests_per_second":-1.0,"throttled_until_millis":0,"failures":[]}
```
```
curl -X POST "es-elasticsearch:9200/_aliases" -H 'Content-Type: application/json' -d'
{
  "actions" : [
    { "add":  { "index": ".kibana-6", "alias": ".kibana" } },
    { "remove_index": { "index": ".kibana" } }
  ]
}
'
{"acknowledged":true}
```

**Comment by StrayCat1** [comment]
Notes for federal partners- 

Important: Not a substitute for reading this - https://www.elastic.co/guide/en/elastic-stack/6.0/upgrading-elastic-stack.html

1) Be on >5.6.x 
2)The OneStop indices do not require a special migration.
3) ES automatically handles all the changes necessary when it starts 
4) we used kubernetes to update each node, so the exact steps are obfuscated from us. 
5) But the procedure should be as easy as starting a ES6 nodes with the same config we had for the ES5 nodes (pointed to the same persistent storage). 
6)start the ES6 nodes and take down the ES5 nodes one at a time for zero downtime
7 ) restart api-admin and api-search

**Comment by StrayCat1** [comment]
Only change I had to make on sciapps to migrate the cluster- 

https://github.com/cedardevs/cu-server-admin/blob/master/roles/cedar-chart-deploy/files/templates/elasticsearch.j2#L7
