### ISSUE TITLE
Update DEM metadata used by sciapps

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#931]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>tester of OneStop</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       run through my ORR tests and be confident my results reflect the production environment
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>be confident in the latest release</td>
  </tr>
</table>

## Description
DEM metadata records have switched to static thumbnails and the map image in the old metadata is going to be retired.

Download metadata from WAF and update our test metadata tar ball

## Tasks
- [x] Download new metadata files from WAF:
    - https://data.noaa.gov/waf/NOAA/NESDIS/NGDC/MGG/DEM/iso/xml/  
- [x] Update test tarball with new metadata
- [x] Verify updated tarball is giving expected results after load.

**Comment by StrayCat1** [comment]
Updated the tar and the gradle task to upload it. 

Noticed that only 308 of 384. I have not yet looked into why some failed.

**Comment by dneufeldcu** [comment]
When searching DEM records on sciapps

I search for DEM records on sciapps:

The thumbnails for DEM records are still pointing to mapservices as opposed to static thumbnails.

e.g.

https://gis.ngdc.noaa.gov/arcgis/rest/services/DEM_global_mosaic_hillshade/ImageServer/exportImage?bbox=-90.75,28.50,-85.00,31.25&size=300,300&format=png32&interpolation=%20RSP_BilinearInterpolation&renderingRule=%7B%22rasterFunction%22:%22ColorHillshade%22%7D&f=image"

should be pointing to:
https://gis.ngdc.noaa.gov/arcgis/rest/services/DEM_global_mosaic_hillshade/ImageServer/exportImage?bbox=-90.75,28.50,-85.00,31.25&size=300,300&format=png32&interpolation=%20RSP_BilinearInterpolation&renderingRule=%7B%22rasterFunction%22:%22ColorHillshade%22%7D&f=image"

Is it possible we haven't loaded the updated tar ball on sciapps?

Moving back to review.

AC: Searching for DEMs on sciapps returns results that reflect the updated thumbnail links.

**Comment by StrayCat1** [comment]
Just uploaded the latest DEM to sciapps via IM -> OS (kafka ingest), with this data- 
https://github.com/cedardevs/onestop-test-data/tree/master/DEM

And here is the Elfin Cove data- 

https://sciapps.colorado.edu/onestop/collections?q=Elfin%20Cove

**Comment by dneufeldcu** [comment]
AC -

Confirm metadata is up to date on sciapps via OS by looking at the following record for example by reviewing thumbnail attribute here:

https://data.noaa.gov/waf/NOAA/NESDIS/NGDC/MGG/DEM/iso/xml/249.xml

and here:

https://sciapps.colorado.edu/onestop/collections?q=fileIdentifier%3A%22gov.noaa.ngdc.mgg.dem%3A249%22

**Comment by StrayCat1** [comment]
https://sciapps.colorado.edu/onestop/collections?q=fileIdentifier%3A%22gov.noaa.ngdc.mgg.dem%3A249%22 

`"thumbnail": "https://maps.ngdc.noaa.gov/thumbnails/DEM/249.png"`

**Comment by dneufeldcu** [comment]
Confirmed updated on 9/23/2019
