### ISSUE TITLE
EPIC: HIP

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#937]
### Summary
<table>
  <tr>
    <td><b>As an</b></td>
    <td>agile team</td>
  </tr>
  <tr>
    <td><b>we value HIP sprints</b></td>
    <td>so that stuff works in the long term</td>
  </tr>
  <tr>
    <td><b>So that we can</b></td>
    <td>feel motivate and smile</td>
  </tr>
</table>

### Tasks
- [x] Hardening - Metadata test tarball cleanup (https://github.com/cedardevs/cu-server-admin/issues/62)
- [x] Hardening - Versioning improvements see promote.sh (https://github.com/cedardevs/onestop/issues/896)
- [x] Hardening - Snapshot determination logic (https://github.com/cedardevs/onestop/issues/944)
- [ ] Innovate - cesium (https://github.com/cedardevs/onestop/issues/940)
- [x] Rook (https://github.com/cedardevs/cu-server-admin/issues/60)
- [x] Planning - Plan the migration (https://github.com/cedardevs/onestop/issues/941)
