### ISSUE TITLE
Support default indexing strategy for base-level granules from CI

### ISSUE THREAD

**Issue by mcquinne** [cedardevs/onestop#972]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>member of the public</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       find all NCEI's ingested data in OneStop
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>access and use it</td>
  </tr>
</table>

### Background
The granules which are published into PSI from CI contain no discovery information. They only have [fileInformation](https://github.com/cedardevs/schemas/blob/master/schemas-core/src/main/resources/avro/psi/fileInformation.avsc), [fileLocations](https://github.com/cedardevs/schemas/blob/master/schemas-core/src/main/resources/avro/psi/fileLocation.avsc), and potentially [relationships](https://github.com/cedardevs/schemas/blob/master/schemas-core/src/main/resources/avro/psi/relationship.avsc) specified. While this is obviously not ideal for searching, we still think that granules which are publicly accessible should be discoverable in OneStop, and should be associated with their collection if a relationship is provided.

### Considerations

Currently `internalParentIdentifier` is only present in the search indices and is set during the ETL process. Also, these raw CI granules only know the UUID of their parents, not the `fileIdentifier` or `doi` that we use to look up parent collections currently. There are lots of potential paths here to consider...

- Add `internalParentIdentifier` to the staging index and update ETL to use it if it's there
- Insert it directly into the search index, flatten immediately if possible
- Look up the `fileIdentifier` and/or `doi` from the given collection and set the `parentIdentifier` with it/them
- Add support for using the collection's UUID in the granule's `parentIdentifer` field in addition to `fileIdentifier` and `doi`
- Defer this story until after we get to a place where we just skip staging always 
- Should we add a field that indicates that the granule only had default info available?
- ???

### AC:
- [x] Granules which are accessible (i.e. have a non-restricted, non-deleted, non-asynchronous fileLocation) should be discoverable
    - Create a access links from the linkInformation objects
    - Set the fileIdentifier and title to be the file's name
- [x] Granules with a COLLECTION relationship should be associated with the collection using the `id` of the relationship as the `internalParentId` of the collection

### Tasks:
- [x] Build indexable object with extra data from `ParsedRecord` object
  - Requires: `fileIdentifier`, `parentIdentifier`, `hierarchyLevelName`, `title`, and `links`
  - cedardevs/schemas#16
  - Appropriate tests
- [x] ETL granules with a collection's `id` in addition to current `fileIdentifier`/`doi` behavior
- [x] Include spatial validation in validation check
- [x] Follow best practices for identify granules & collections (#731)
- [x] Update indexing tests
- [x] Update ETL tests

child of cedardevs/psi#275

**Comment by amilan17** [comment]
> "Also, these raw CI granules only know the UUID of their parents, not the fileIdentifier or doi". 

Where does the UUID for a parent collection originate from?

**Comment by dneufeldcu** [comment]
Collection UUID is configured as part of the datastream set-up in Common Ingest. Specifiically in a new metadata-scraper engine.
