### ISSUE TITLE
ElasticSearch 7.x upgrade

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#974]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>devops engineer</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       use the latest features that Elastic has to offer
</td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>wow my users and feel confident that my app won't EOL soon based on older versions of ES</td>
  </tr>
</table>

## Tasks
- [x] Test OneStop Search with ES 7.x (latest)
- [x] Test OneStop Admin/Metadata with ES 7.x (latest)
- [x] Capture breaking changes as a new story

**Comment by forgo** [comment]
**Documenting Deprecations and Decisions:**

1. “the default number of shards will change from [5] to [1] in 7.0.0; if you wish to continue using the default of [5] shards, you must manage this on the create index request or with an index template”
    - we should be able to let this default change without any explicit action because: `we want enable that to be controlled at the cluster admin level, because the number of shards that you want is dictated by the size of your nodes (mostly)`
