### ISSUE TITLE
Toggle on sitemap feature in partner test env

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#979]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>metadata team member</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       decommission legacy geoportal instance
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>become more efficient and secure</td>
  </tr>
</table>

### Tasks
- [x] Review and update documentation of this feature if needed (https://github.com/cedardevs/onestop/blob/master/docs/operator/deployment/v2/onestop/feature-toggles.md)
- [x] Toggle on sitemap feature locally
- [ ] Toggle on sitemap feature in the cloud
- [ ] Toggle on sitemap feature in partner test env (asheville test tier) to see if it functions correctly

**Comment by erinreeves** [comment]
Locally did:
export SPRING_PROFILES_ACTIVE="sitemap"
./gradlew search:bootRun

With printout in terminal indicated it worked:
2020-06-03 08:24:06.912  INFO 4177 --- [  restartedMain] o.cedar.onestop.api.search.Application   : The following profiles are active: sitemap

**Comment by mcquinne** [comment]
I enabled the sitemap in the cloud and have discovered some significant deficiencies:

- v2 docs were updated but not v3
- v3 docs make no mention of the indexer settings to enable sitemap building
- the root sitemap is returned as an html document
- sitemap is located under `/onestop-search` as opposed to `/onestop`, are we sure that works?
