### ISSUE TITLE
Improve Indexer and its tests 

### ISSUE THREAD

**Issue by ajakz** [cedardevs/onestop#989]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>developer</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       make sure the Indexer tests are thorough and clean
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>minimize tech debt going into OneStop 3.0 work</td>
  </tr>
</table>

### Description
The IndexerTest class currently has lingering remnants of MetadataParser (since moved to the Schemas repo as ISOParser), making it a bit more reliant on XML than necessary. Focus should be on verifying ParsedRecords --> Elasticsearch documents is as expected, and that all code routes are tested (i.e., errors thrown when expected, specific validation messages received when invalid records encountered, etc.).

### Tasks
- [ ] Create an Enum class out of the validation error messages to improve testability and ease of updating
- [x] Test each validation error in isolation
- [x] Use ParsedRecords instead of XML in tests when testing any method other than `xmlToParsedRecord()`
- [x] Migrate RecordType determination logic to Schemas repo once OneStop no longer accepts XML directly
- [x] Migrate any direct XML parsing tests to Schemas repo if logic isn't already covered in existing tests between schemas-parse and schemas-analyze (OneStop isn't parsing XML, Schemas is)
- [x] Address FIXME and TODO notes in IndexerTest 
- [ ] TBD
